# -*- coding: utf-8 -*-
"""graph_rag_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l1OqeHPjGRlo7oI__U_dMrdk-5BDiBG7

!pip -q install -U transformers accelerate sentencepiece safetensors
"""



import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

model_name = "Qwen/Qwen2.5-0.5B-Instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype="auto",
    device_map="auto"
)

print("model loaded")

def generate_answer(context, question):
    prompt = f"""
あなたはRAG回答エンジンです。
以下のコンテキストだけを根拠に、質問に日本語で簡潔に答えてください。
根拠が足りない場合は「コンテキストだけでは判断できません」と答えてください。

## コンテキスト
{context}

## 質問
{question}

## 回答
"""

    messages = [
        {"role": "system", "content": "あなたは根拠に忠実な日本語アシスタントです。"},
        {"role": "user", "content": prompt}
    ]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    inputs = tokenizer([text], return_tensors="pt").to(model.device)

    outputs = model.generate(
        **inputs,
        max_new_tokens=256,
        do_sample=False
    )

    generated = outputs[0][inputs.input_ids.shape[-1]:]
    return tokenizer.decode(generated, skip_special_tokens=True)


documents = [
    {"id": "doc1", "text": "山田部長はネコプロジェクトの責任者である。"},
    {"id": "doc2", "text": "ネコプロジェクトはCRM基盤に影響する。"},
    {"id": "doc3", "text": "山田部長は営業企画部に所属している。"},
    {"id": "doc4", "text": "CRM基盤は顧客情報を管理する社内システムである。"}
]

question = "山田部長が責任を持つプロジェクトは、どのシステムに影響しますか？"

# 通常のRAG
def simple_keyword_score(question, doc):
    keywords = ["山田部長", "責任", "プロジェクト", "システム", "影響"]
    return sum(1 for kw in keywords if kw in question and kw in doc)

def simple_retrieve(question, documents, top_k=1):
    scored = []
    for d in documents:
        score = simple_keyword_score(question, d["text"])
        scored.append((score, d))
    scored = sorted(scored, key=lambda x: x[0], reverse=True)
    return [d for score, d in scored[:top_k] if score > 0]

plain_docs = simple_retrieve(question, documents, top_k=2)

plain_context = "\n".join([f"{d['id']}: {d['text']}" for d in plain_docs])

print("=== 通常RAG風コンテキスト ===")
print(plain_context)

print("\n=== LLM回答 ===")
print(generate_answer(plain_context, question))

ontology = {
    "entities": {
        "Person": "人物",
        "Project": "プロジェクト",
        "Department": "部署",
        "System": "システム"
    },
    "relations": {
        "responsible_for": "人物がプロジェクトの責任者である",
        "affects": "プロジェクトがシステムに影響する",
        "belongs_to": "人物が部署に所属する"
    }
}

triples = [
    ("山田部長", "type", "Person"),
    ("ネコプロジェクト", "type", "Project"),
    ("CRM基盤", "type", "System"),
    ("営業企画部", "type", "Department"),

    ("山田部長", "responsible_for", "ネコプロジェクト"),
    ("ネコプロジェクト", "affects", "CRM基盤"),
    ("山田部長", "belongs_to", "営業企画部")
]

for s, r, o in triples:
    print(f"{s} --{r}--> {o}")

def find_objects(subject, relation, triples):
    return [o for s, r, o in triples if s == subject and r == relation]

def build_graph_context_for_question(person_name):
    facts = []
    paths = []

    projects = find_objects(person_name, "responsible_for", triples)

    for project in projects:
        facts.append(f"{person_name} は {project} の責任者である。")

        systems = find_objects(project, "affects", triples)

        for system in systems:
            facts.append(f"{project} は {system} に影響する。")
            paths.append(f"{person_name} --responsible_for--> {project} --affects--> {system}")

    context = f"""
## オントロジー
- Person は人物を表す。
- Project はプロジェクトを表す。
- System はシステムを表す。
- responsible_for は「人物がプロジェクトの責任者である」関係を表す。
- affects は「プロジェクトがシステムに影響する」関係を表す。

## グラフから取得した事実
{chr(10).join(f"- {fact}" for fact in facts)}

## 導出パス
{chr(10).join(f"- {path}" for path in paths)}
"""
    return context

graph_context = build_graph_context_for_question("山田部長")

print("=== GraphRAG風コンテキスト ===")
print(graph_context)

print("=== LLM回答: オントロジー + GraphRAG風 ===")
print(generate_answer(graph_context, question))

# 問題2
question = "ネコプロジェクトはどのシステムに影響しますか？"
print("\n=== 従来RAG回答 ===")
print(generate_answer(plain_context, question))
print("=== LLM回答: オントロジー + GraphRAG風 ===")
print(generate_answer(graph_context, question))

# 問題1
question = "山田部長が責任を持つプロジェクトは、どのシステムに影響しますか？"
print("\n=== 従来RAG回答 ===")
print(generate_answer(plain_context, question))
print("=== LLM回答: オントロジー + GraphRAG風 ===")
print(generate_answer(graph_context, question))

