# -*- coding: utf-8 -*-
"""Entity_Resolution_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12k3GXBgbCx5l9QhcZt6l19wypSzF4Pe3
"""

# Commented out IPython magic to ensure Python compatibility.
# Colab上で
!git clone https://github.com/jiny1623/DynamicER.git
# %cd DynamicER
!pip install -e .  # もしsetup.pyがあれば
# Cythonのビルド
!python setup.py build_ext --inplace

!pip show  sentence-transformers scikit-learn

# ============================================================
# TempCCA 簡易版 PoC（Google Colab用）
# ============================================================

import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

# 1. エンコーダの準備（軽量モデル）
model = SentenceTransformer('all-MiniLM-L6-v2')  # Colabでも高速

# 2. 模擬データ（社内RAGを想定）
# 時間セグメントT1: 立ち上げ期
mentions_t1 = [
    "新規プロジェクトの猫のやつ",
    "Project Neko",
    "ネコ型AI開発",
]
# 既知エンティティ（KB登録済み）
entities = {
    "Q001": "Project Nekoは社内の新規AI開発プロジェクト。コードネームはNeko。",
    "Q002": "Lighthouseは既存の検索基盤プロジェクト。",
    "Q003": "山田太郎は営業部の部長。",
}

# 3. ベクトル化
mention_vecs_t1 = model.encode(mentions_t1)
entity_vecs = {qid: model.encode(desc) for qid, desc in entities.items()}

# 4. 静的エンティティ表現
static_entity_vecs = np.array(list(entity_vecs.values()))
entity_ids = list(entity_vecs.keys())

# 5. T1: クラスタリング（単純な最近傍）
def resolve_mentions(mention_vecs, entity_vecs, entity_ids, alpha=0.5, prev_mentions=None):
    """
    TempCCAの簡易版
    alpha: 静的表現 vs 動的表現のバランス
    prev_mentions: 過去にリンクされたメンションのベクトルリスト
    """
    # エンティティの動的表現を計算
    dynamic_entity_vecs = []
    for i, qid in enumerate(entity_ids):
        static = entity_vecs[qid]
        if prev_mentions and qid in prev_mentions and len(prev_mentions[qid]) > 0:
            # 継続的適応: 過去メンションの平均を混ぜる
            dynamic = alpha * static + (1 - alpha) * np.mean(prev_mentions[qid], axis=0)
        else:
            dynamic = static
        dynamic_entity_vecs.append(dynamic)

    dynamic_entity_vecs = np.array(dynamic_entity_vecs)

    # Affinity計算（コサイン類似度）
    similarities = cosine_similarity(mention_vecs, dynamic_entity_vecs)

    # 各メンションを最も近いエンティティに割り当て
    assignments = []
    for i, sim_row in enumerate(similarities):
        best_idx = np.argmax(sim_row)
        assignments.append((mentions_t1[i], entity_ids[best_idx], sim_row[best_idx]))

    return assignments, dynamic_entity_vecs

# T1の解決
assignments_t1, dynamic_vecs_t1 = resolve_mentions(
    mention_vecs_t1, entity_vecs, entity_ids, alpha=0.7, prev_mentions=None
)

print("=== T1 結果 ===")
for mention, qid, score in assignments_t1:
    print(f"'{mention}' → {qid} (score: {score:.3f})")

# 6. T2: 新しいメンションが出現（略称が定着）
mentions_t2 = [
    "PNJ",  # Project Neko Junior? → いいえ、Project Nekoの略
    "猫PJ",  # 新しい呼び方
    "ネコプロ",
]

# T1でProject Neko(Q001)に割り当てられたメンションを収集
prev_mentions = {
    "Q001": [mention_vecs_t1[i] for i, (_, qid, _) in enumerate(assignments_t1) if qid == "Q001"],
    "Q002": [],
    "Q003": [],
}

mention_vecs_t2 = model.encode(mentions_t2)

assignments_t2, dynamic_vecs_t2 = resolve_mentions(
    mention_vecs_t2, entity_vecs, entity_ids, alpha=0.5, prev_mentions=prev_mentions
)

print("\n=== T2 結果（継続的適応あり） ===")
for mention, qid, score in assignments_t2:
    print(f"'{mention}' → {qid} (score: {score:.3f})")

# 7. 比比較：継続的適応なし（alpha=1.0 = 静的のみ）
assignments_t2_static, _ = resolve_mentions(
    mention_vecs_t2, entity_vecs, entity_ids, alpha=1.0, prev_mentions=None
)

print("\n=== T2 結果（継続的適応なし = 従来手法） ===")
for mention, qid, score in assignments_t2_static:
    print(f"'{mention}' → {qid} (score: {score:.3f})")

!pip install llama-index-embeddings-huggingface

!pip install llama-index llama-index-embeddings-huggingface

# ============================================================
# 2. インポート
# ============================================================
import numpy as np
import os
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from llama_index.core import VectorStoreIndex, Document, Settings
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

# HuggingFaceの警告を抑制（任意）
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# ============================================================
# 3. ローカル埋め込みモデルの設定（OpenAI不要）
# ============================================================
# 軽量で高精度なモデルを指定
local_embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

# LlamaIndexのデフォルト設定を上書き
Settings.embed_model = local_embed_model

# 名寄せ用のSentence-BERTも別途準備（日本語対応なら別モデルも可）
sbert = SentenceTransformer('all-MiniLM-L6-v2')

# ============================================================
# 4. 模擬データ（社内RAGを想定）
# ============================================================
# 時間セグメントT1: 立ち上げ期
docs_t1 = [
    Document(text="Project Nekoは新規AI開発プロジェクトです。2024年1月に立案された。",
             metadata={"time": "T1", "source": "meeting"}),
    Document(text="Lighthouseは既存の検索基盤プロジェクト。社内の文書検索を支えている。",
             metadata={"time": "T1", "source": "doc"}),
    Document(text="山田太郎は営業部の部長。2020年から営業部を率いている。",
             metadata={"time": "T1", "source": "hr"}),
]

# 時間セグメントT2: 略称定着期
docs_t2 = [
    Document(text="PNJの進捗は良好です。第2四半期のマイルストーンを達成。",
             metadata={"time": "T2", "source": "slack"}),
    Document(text="猫PJの予算が承認されました。来年度から本格開発開始。",
             metadata={"time": "T2", "source": "mail"}),
    Document(text="ネコプロのチームが拡大。新たに5名が配属された。",
             metadata={"time": "T2", "source": "wiki"}),
]

# エンティティKB（正規名と説明）
entity_kb = {
    "Q001": "Project Nekoは社内の新規AI開発プロジェクト。コードネームはNeko。",
    "Q002": "Lighthouseは既存の検索基盤プロジェクト。",
    "Q003": "山田太郎は営業部の部長。",
}

# T1で収集されたメンション履歴（継続的適応用）
entity_history = {
    "Q001": ["Project Neko", "新規AI開発プロジェクト", "ネコ型AI"],  # T1で使われた呼び方
    "Q002": ["Lighthouse"],
    "Q003": ["山田太郎", "山田部長"],
}

# ============================================================
# 5. ベクトルインデックス構築（ローカル埋め込み）
# ============================================================
all_docs = docs_t1 + docs_t2
index = VectorStoreIndex.from_documents(all_docs)

print("✅ インデックス構築完了（ローカル埋め込み使用）")

# ============================================================
# 6. TempCCA的名寄せモジュール
# ============================================================
def resolve_query_entities(query: str, entity_kb: dict, entity_history: dict,
                           alpha: float = 0.5, threshold: float = 0.5):
    """
    クエリ中のメンションをKBエンティティに解決（TempCCA的アプローチ）

    Parameters:
        query: ユーザーの質問文
        entity_kb: {entity_id: 正規説明文}
        entity_history: {entity_id: [過去に使われたメンションリスト]}
        alpha: 静的表現 vs 動的表現のバランス（0~1）
        threshold: リンク確定の閾値

    Returns:
        resolved_query: 名寄せ後の正規化クエリ
        best_entity: 最も近いエンティティID
        confidence: 信頼度スコア
    """
    query_vec = sbert.encode([query])

    best_match = None
    best_score = -1

    print(f"\n🔍 クエリ: '{query}'")
    print("--- Affinityスコア ---")

    for eid, desc in entity_kb.items():
        # 静的エンティティ表現（KBの説明文）
        static_vec = sbert.encode([desc])

        # 継続的適応: 過去メンションの平均を混ぜる
        if eid in entity_history and len(entity_history[eid]) > 0:
            hist_vecs = sbert.encode(entity_history[eid])
            dynamic_vec = alpha * static_vec + (1 - alpha) * np.mean(hist_vecs, axis=0)
        else:
            dynamic_vec = static_vec

        # Affinity計算（コサイン類似度）
        sim = cosine_similarity(query_vec, dynamic_vec.reshape(1, -1))[0][0]

        entity_name = desc.split("は")[0] if "は" in desc else desc[:20]
        print(f"  φ({entity_name}, query) = {sim:.4f}")

        if sim > best_score:
            best_score = sim
            best_match = eid

    # 閾値チェック
    if best_score < threshold:
        print(f"⚠️ 閾値({threshold})を下回るため、名寄せをスキップ")
        return query, None, best_score

    # 正規化（クエリ内の略称を正規名に置換）
    canonical_name = entity_kb[best_match].split("は")[0]
    # 簡易的な置換: クエリ中の単語を正規名に置換（実際はもっと賢く必要）
    resolved_query = query  # ここでは単純化

    print(f"✅ 名寄せ結果: '{query}' → {best_match}({canonical_name}), 信頼度={best_score:.3f}")

    return resolved_query, best_match, best_score


def retrieve_with_resolution(query: str, index: VectorStoreIndex,
                             entity_kb: dict, entity_history: dict,
                             alpha: float = 0.5, top_k: int = 3):
    """
    名寄せを挟んでからRetrieverを実行するRAGパイプライン
    """
    # Step 1: 名寄せ
    resolved_query, entity_id, confidence = resolve_query_entities(
        query, entity_kb, entity_history, alpha=alpha
    )

    # Step 2: 名寄せ成功時は正規名で検索
    if entity_id:
        canonical_name = entity_kb[entity_id].split("は")[0]
        # クエリ中の略称らしき部分を正規名に置換して検索
        search_query = canonical_name + " " + query
        print(f"🔎 検索クエリ: '{search_query}'")
    else:
        search_query = query
        print(f"🔎 検索クエリ（名寄せなし）: '{search_query}'")

    # Step 3: Retriever実行
    retriever = VectorIndexRetriever(index, similarity_top_k=top_k)
    nodes = retriever.retrieve(search_query)

    return nodes, entity_id, confidence


# ============================================================
# 7. 実行テスト
# ============================================================

print("=" * 60)
print("【テスト1】T1の正規名で検索")
print("=" * 60)
nodes, eid, conf = retrieve_with_resolution(
    "Project Nekoの進捗は？", index, entity_kb, entity_history, alpha=0.5
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text[:50]}... (出典: {node.metadata['source']})")

print("\n" + "=" * 60)
print("【テスト2】T2の新しい略称「PNJ」で検索（継続的適応あり）")
print("=" * 60)
nodes, eid, conf = retrieve_with_resolution(
    "PNJの予算は？", index, entity_kb, entity_history, alpha=0.5
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text[:50]}... (出典: {node.metadata['source']})")

print("\n" + "=" * 60)
print("【テスト3】T2の新しい略称「猫PJ」で検索（継続的適応あり）")
print("=" * 60)
nodes, eid, conf = retrieve_with_resolution(
    "猫PJのチーム規模は？", index, entity_kb, entity_history, alpha=0.5
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text[:50]}... (出典: {node.metadata['source']})")

print("\n" + "=" * 60)
print("【テスト4】継続的適応なし（alpha=1.0 = 従来手法）で「PNJ」を検索")
print("=" * 60)
nodes, eid, conf = retrieve_with_resolution(
    "PNJの予算は？", index, entity_kb, entity_history, alpha=1.0
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text[:50]}... (出典: {node.metadata['source']})")

# ============================================================
# 8. エンティティ履歴の更新（新しいメンションを追加）
# ============================================================
# T2の検索結果から新しいメンションを学習
if eid:
    entity_history[eid].append("PNJ")
    print(f"\n📝 エンティティ履歴を更新: {eid} に 'PNJ' を追加")
    print(f"   現在の履歴: {entity_history[eid]}")

# ============================================================
# 修正版：日本語対応 + クエリ前処理 + alpha調整
# ============================================================
import numpy as np
import re
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from llama_index.core import VectorStoreIndex, Document, Settings
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
import os
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# ============================================================
# 1. 日本語対応の埋め込みモデルに変更（最重要）
# ============================================================
# インデックス用
local_embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
)
Settings.embed_model = local_embed_model

# 名寄せ用（日本語対応）
sbert = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

# ============================================================
# 2. データ準備（同じ）
# ============================================================
docs_t1 = [
    Document(text="Project Nekoは新規AI開発プロジェクトです。2024年1月に立案された。",
             metadata={"time": "T1", "source": "meeting"}),
    Document(text="Lighthouseは既存の検索基盤プロジェクト。社内の文書検索を支えている。",
             metadata={"time": "T1", "source": "doc"}),
    Document(text="山田太郎は営業部の部長。2020年から営業部を率いている。",
             metadata={"time": "T1", "source": "hr"}),
]
docs_t2 = [
    Document(text="PNJの進捗は良好です。第2四半期のマイルストーンを達成。",
             metadata={"time": "T2", "source": "slack"}),
    Document(text="猫PJの予算が承認されました。来年度から本格開発開始。",
             metadata={"time": "T2", "source": "mail"}),
    Document(text="ネコプロのチームが拡大。新たに5名が配属された。",
             metadata={"time": "T2", "source": "wiki"}),
]

entity_kb = {
    "Q001": "Project Nekoは社内の新規AI開発プロジェクト。コードネームはNeko。",
    "Q002": "Lighthouseは既存の検索基盤プロジェクト。",
    "Q003": "山田太郎は営業部の部長。",
}

# T1で収集されたメンション履歴
entity_history = {
    "Q001": ["Project Neko", "新規AI開発プロジェクト", "ネコ型AI"],
    "Q002": ["Lighthouse"],
    "Q003": ["山田太郎", "山田部長"],
}

# インデックス構築
all_docs = docs_t1 + docs_t2
index = VectorStoreIndex.from_documents(all_docs)
print("✅ インデックス構築完了\n")

# ============================================================
# 3. クエリからエンティティ候補を抽出する前処理
# ============================================================
def extract_mention_candidates(query: str) -> list:
    """
    クエリから「固有名詞っぽい部分」を抽出
    簡易版：助詞「の」「は」「を」などで分割して先頭の名詞句を抽出
    """
    # 「の」「は」「が」「を」「に」「で」で分割
    parts = re.split(r'[のはがをにで]', query)
    candidates = [p.strip() for p in parts if len(p.strip()) >= 2]
    return candidates

# ============================================================
# 4. 修正版名寄せモジュール
# ============================================================
def resolve_query_entities_v2(query: str, entity_kb: dict, entity_history: dict,
                              alpha: float = 0.3, threshold: float = 0.4):
    """
    修正版：日本語対応 + クエリ前処理 + 動的表現を強化

    Parameters:
        alpha: 静的表現の重み。低いほど過去メンション（動的）を重視
               新しい略称が多い場合は 0.2〜0.4 が推奨
        threshold: 閾値。日本語モデルでは0.4程度が現実的
    """
    # クエリから候補メンションを抽出
    candidates = extract_mention_candidates(query)
    print(f"🔍 クエリ: '{query}'")
    print(f"   抽出候補: {candidates}")

    # 候補ごとにエンティティとの類似度を計算
    best_match = None
    best_score = -1
    best_candidate = None

    print("--- Affinityスコア ---")

    for candidate in candidates:
        candidate_vec = sbert.encode([candidate])

        for eid, desc in entity_kb.items():
            # 静的エンティティ表現
            static_vec = sbert.encode([desc])

            # 継続的適応（動的エンティティ表現）
            if eid in entity_history and len(entity_history[eid]) > 0:
                hist_vecs = sbert.encode(entity_history[eid])
                # alphaを下げる = 過去メンションの影響を強める
                dynamic_vec = alpha * static_vec + (1 - alpha) * np.mean(hist_vecs, axis=0)
            else:
                dynamic_vec = static_vec

            sim = cosine_similarity(candidate_vec, dynamic_vec.reshape(1, -1))[0][0]

            entity_name = desc.split("は")[0] if "は" in desc else desc[:20]
            print(f"  φ({entity_name}, '{candidate}') = {sim:.4f}")

            if sim > best_score:
                best_score = sim
                best_match = eid
                best_candidate = candidate

    # 閾値チェック
    if best_score < threshold:
        print(f"⚠️ 最高スコア{best_score:.3f}が閾値({threshold})を下回るため、名寄せをスキップ")
        return query, None, best_score, None

    canonical_name = entity_kb[best_match].split("は")[0]
    print(f"✅ 名寄せ: '{best_candidate}' → {best_match}({canonical_name}), 信頼度={best_score:.3f}")

    # 正規化クエリ：候補を正規名に置換
    resolved_query = query.replace(best_candidate, canonical_name)

    return resolved_query, best_match, best_score, best_candidate


def retrieve_with_resolution_v2(query: str, index: VectorStoreIndex,
                                 entity_kb: dict, entity_history: dict,
                                 alpha: float = 0.3, threshold: float = 0.4, top_k: int = 3):
    """
    修正版RAGパイプライン
    """
    # 名寄せ
    resolved_query, entity_id, confidence, mention = resolve_query_entities_v2(
        query, entity_kb, entity_history, alpha=alpha, threshold=threshold
    )

    # 検索クエリ決定
    if entity_id:
        print(f"🔎 検索クエリ: '{resolved_query}'")
        search_query = resolved_query
    else:
        print(f"🔎 検索クエリ（名寄せスキップ）: '{query}'")
        search_query = query

    # Retriever実行
    retriever = VectorIndexRetriever(index, similarity_top_k=top_k)
    nodes = retriever.retrieve(search_query)

    return nodes, entity_id, confidence, mention

# ============================================================
# 5. 実行テスト
# ============================================================

print("=" * 60)
print("【テスト1】alpha=0.3（動的表現重視）で「PNJ」を検索")
print("=" * 60)
nodes, eid, conf, mention = retrieve_with_resolution_v2(
    "PNJの予算は？", index, entity_kb, entity_history, alpha=0.3, threshold=0.4
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text} (出典: {node.metadata['source']})")

print("\n" + "=" * 60)
print("【テスト2】「猫PJ」を検索")
print("=" * 60)
nodes, eid, conf, mention = retrieve_with_resolution_v2(
    "猫PJのチーム規模は？", index, entity_kb, entity_history, alpha=0.3, threshold=0.4
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text} (出典: {node.metadata['source']})")

print("\n" + "=" * 60)
print("【テスト3】比較：alpha=1.0（静的のみ = 従来手法）")
print("=" * 60)
nodes, eid, conf, mention = retrieve_with_resolution_v2(
    "PNJの予算は？", index, entity_kb, entity_history, alpha=1.0, threshold=0.4
)
for i, node in enumerate(nodes, 1):
    print(f"  {i}. {node.text} (出典: {node.metadata['source']})")

# ============================================================
# 6. エンティティ履歴の更新（T2の新しいメンションを学習）
# ============================================================
if eid and mention:
    entity_history[eid].append(mention)
    print(f"\n📝 エンティティ履歴を更新: {eid} に '{mention}' を追加")
    print(f"   現在の履歴: {entity_history[eid]}")

def retrieve_with_backward_resolution(query: str, index: VectorStoreIndex,
                                      entity_kb: dict, entity_history: dict,
                                      alpha: float = 0.3, threshold: float = 0.4,
                                      top_k: int = 5):
    """
    2段階推定：
    Step 1: 通常のRetrieverで上位文書を取得（名寄せなし）
    Step 2: 取得した文書の内容から、どのエンティティに近いか再判定
    Step 3: 再判定結果でクエリを正規化して再検索 or Generatorに渡す
    """
    print(f"\nPoC用クエリ: '{query}'")

    # Step 1: 名寄せなしでRetriever実行（広く検索）
    retriever = VectorIndexRetriever(index, similarity_top_k=top_k)
    initial_nodes = retriever.retrieve(query)

    print("--- 初回検索結果 ---")
    for i, node in enumerate(initial_nodes[:3], 1):
        print(f"  {i}. {node.text[:40]}... (出典: {node.metadata['source']})")

    # Step 2: 検索結果の文書とエンティティのAffinityを計算
    print("--- 検索結果からの逆推定 ---")

    best_match = None
    best_score = -1

    # 検索結果上位3件のテキストを結合して1つの文脈ベクトルに
    context_text = " ".join([n.text for n in initial_nodes[:3]])
    context_vec = sbert.encode([context_text])

    for eid, desc in entity_kb.items():
        static_vec = sbert.encode([desc])

        # 継続的適応
        if eid in entity_history and len(entity_history[eid]) > 0:
            hist_vecs = sbert.encode(entity_history[eid])
            dynamic_vec = alpha * static_vec + (1 - alpha) * np.mean(hist_vecs, axis=0)
        else:
            dynamic_vec = static_vec

        # 文脈とエンティティの類似度
        sim = cosine_similarity(context_vec, dynamic_vec.reshape(1, -1))[0][0]
        entity_name = desc.split("は")[0] if "は" in desc else desc[:20]
        print(f"  文脈 vs {entity_name} = {sim:.4f}")

        if sim > best_score:
            best_score = sim
            best_match = eid

    # Step 3: 閾値チェック
    if best_score < threshold:
        print(f"⚠️ 逆推定スコア{best_score:.3f}が閾値を下回るため、正規化をスキップ")
        return initial_nodes, None, best_score

    # 正規化して再検索 or そのまま返す
    canonical_name = entity_kb[best_match].split("は")[0]
    resolved_query = query  # 必要に応じて置換

    print(f"オレオレ逆推定: 検索文脈 → {best_match}({canonical_name}), 信頼度={best_score:.3f}")

    # 再検索（正規名を追加）
    retriever2 = VectorIndexRetriever(index, similarity_top_k=top_k)
    final_nodes = retriever2.retrieve(f"{canonical_name} {query}")

    return final_nodes, best_match, best_score


# 実行
print("=" * 60)
print("【逆推定テスト】alpha=1.0（静的のみ）+ Backward Resolution")
print("=" * 60)
nodes, eid, conf = retrieve_with_backward_resolution(
    "PNJの予算は？", index, entity_kb, entity_history, alpha=1.0, threshold=0.4
)
for i, node in enumerate(nodes[:3], 1):
    print(f"  {i}. {node.text[:50]}... (出典: {node.metadata['source']})")

