# -*- coding: utf-8 -*-
"""ortho_create_laz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZLHJAFmcwDec-RCn4X2wELKzHJmnF5v
"""

# 1. 必要なライブラリのインストール
!pip install -q laspy[lazrs] numpy rasterio matplotlib open3d

import urllib.request

# 確実に直リンクでダウンロード可能な直URL
url = "https://gsj-seamless.jp/pointCloud/sample/crater/las/08ME3562.las"

req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
with urllib.request.urlopen(req) as resp, open("sample.las", "wb") as f:
    f.write(resp.read())

!unzip /content/sample.zip

import laspy
import numpy as np
import plotly.graph_objects as go

las = laspy.read("08ME3562.las")

# 描画負荷を軽くするため100点に1点抽出（ダウンサンプリング）
skip = 100
x = las.x[::skip]
y = las.y[::skip]
z = las.z[::skip]

# RGBカラーの生成 (0-255表記に変換)
r = (las.red[::skip] / 256).astype(int)
g = (las.green[::skip] / 256).astype(int)
b = (las.blue[::skip] / 256).astype(int)
color_strings = [f'rgb({r_i},{g_i},{b_i})' for r_i, g_i, b_i in zip(r, g, b)]

# Plotlyで3D散布図を描画
fig = go.Figure(data=[go.Scatter3d(
    x=x, y=y, z=z,
    mode='markers',
    marker=dict(
        size=1.5,
        color=color_strings,
        opacity=0.8
    )
)])

fig.update_layout(
    scene=dict(aspectmode='data'),
    title="富士山火口 3D点群プレビュー (Plotly)"
)

fig.show()

import os
import laspy
import numpy as np
import rasterio
from rasterio.transform import from_origin
import matplotlib.pyplot as plt

laz_file = "08ME3562.las"

# 3. LAZファイルの読み込み
las = laspy.read(laz_file)

# 座標の取得
x = las.x
y = las.y

# RGB情報の取得（16bitから8bitへ変換）
# ※データによってはRGBがなくIntensity（反射強度）のみの場合もあります
r = (las.red / 256).astype(np.uint8)
g = (las.green / 256).astype(np.uint8)
b = (las.blue / 256).astype(np.uint8)

# 4. 2Dグリッド（ピクセル）の設定
pixel_size = 1.0  # 1ピクセル = 1m （処理を軽量化するため1mに設定）

x_min, x_max = np.min(x), np.max(x)
y_min, y_max = np.min(y), np.max(y)

width = int(np.ceil((x_max - x_min) / pixel_size))
height = int(np.ceil((y_max - y_min) / pixel_size))

# ピクセルインデックスの計算
col_idx = np.floor((x - x_min) / pixel_size).astype(int)
row_idx = np.floor((y_max - y) / pixel_size).astype(int)

# 範囲外のインデックスを制限
col_idx = np.clip(col_idx, 0, width - 1)
row_idx = np.clip(row_idx, 0, height - 1)

# 5. グリッドへRGBを配置
ortho_image = np.zeros((height, width, 3), dtype=np.uint8)

# 点群の色を割り当て
ortho_image[row_idx, col_idx, 0] = r
ortho_image[row_idx, col_idx, 1] = g
ortho_image[row_idx, col_idx, 2] = b

# 6. GeoTIFFとして保存
transform = from_origin(x_min, y_max, pixel_size, pixel_size)
output_tif = "output_ortho.tif"

with rasterio.open(
    output_tif,
    'w',
    driver='GTiff',
    height=height,
    width=width,
    count=3,
    dtype=ortho_image.dtype,
    crs=las.header.parse_crs() if las.header.parse_crs() else "EPSG:2992", # フォールバック座標系
    transform=transform,
) as dst:
    dst.write(ortho_image[:, :, 0], 1)
    dst.write(ortho_image[:, :, 1], 2)
    dst.write(ortho_image[:, :, 2], 3)

print("GeoTIFFの生成が完了しました！")

# 7. 生成したオルソ画像のプレビュー表示
plt.figure(figsize=(10, 10))
plt.imshow(ortho_image)
plt.title("Generated Ortho Image from LAZ")
plt.axis('off')
plt.show()

