# -*- coding: utf-8 -*-
"""GNN_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ExTjHkJS6uXbd71NTfUQAatf_ngawI7R
"""

!pip install torch_geometric
!pip install torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.1.0+cu121.html

from torch_geometric.datasets import Planetoid

dataset = Planetoid(root='/tmp/Cora', name='Cora')
# dataset = Planetoid(root='/tmp/Citeseer', name='CiteSeer')
# dataset = Planetoid(root='/tmp/PubMed', name='PubMed')

data = dataset[0]  # 1つのグラフとして扱う
print(data)
# Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

import time
import matplotlib.pyplot as plt
import networkx as nx
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from IPython.display import clear_output

# =====================================================================
# 1. データの準備（公開データセット：空手クラブ）
# =====================================================================
# 34人のメンバー（ノード）と、その友情関係（エッジ）のグラフ
G = nx.karate_club_graph()
num_nodes = G.number_of_nodes()

# 隣接行列 A の作成 [34, 34]
adj = nx.to_numpy_array(G)
adj = torch.tensor(adj, dtype=torch.float32)

# 特徴量行列 X の作成 [34, 34]
# 今回は個人のプロファイルがないため、単位行列（ID情報）を初期特徴量とします
features = torch.eye(num_nodes)

# 正解ラベルの作成 (Mr. Hiの派閥=0, John A.の派閥=1)
labels = torch.tensor([0 if G.nodes[i]['club'] == 'Mr. Hi' else 1 for i in range(num_nodes)])

# ★GNNの凄さを体感するポイント★
# 34人中、わずか「2人（リーダー2人）」の正解だけを訓練データとし、残り32人を予測（テスト）します
train_mask = torch.zeros(num_nodes, dtype=torch.bool)
train_mask[0] = True   # Mr. Hi (コミュニティ1のリーダー)
train_mask[33] = True  # John A. (コミュニティ2のリーダー)

test_mask = ~train_mask

# =====================================================================
# 2. ミニマルなGNN（GCN）モデルの定義
# =====================================================================
class GCNLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.FloatTensor(in_features, out_features))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, x, adj):
        # 自己ループと対称正規化のシミュレート
        adj_tilde = adj + torch.eye(adj.size(0))
        degree = torch.sum(adj_tilde, dim=1)
        D_inv_sqrt = torch.diag(torch.pow(degree, -0.5))
        adj_norm = torch.mm(torch.mm(D_inv_sqrt, adj_tilde), D_inv_sqrt)

        # メッセージパッシング
        return torch.mm(adj_norm, torch.mm(x, self.weight))

class KarateGNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()
        self.conv1 = GCNLayer(input_dim, hidden_dim)
        self.conv2 = GCNLayer(hidden_dim, num_classes)

    def forward(self, x, adj):
        # 1層目を通した後の、ノードの2次元空間プロット用特徴量を保持
        self.embedding = self.conv1(x, adj)
        x = F.relu(self.embedding)
        x = self.conv2(x, adj)
        return F.log_softmax(x, dim=1)

# =====================================================================
# 3. 訓練ループとリアルタイム可視化
# =====================================================================
model = KarateGNN(input_dim=num_nodes, hidden_dim=4, num_classes=2)
optimizer = optim.Adam(model.parameters(), lr=0.05)
criterion = nn.NLLLoss()

pos = nx.spring_layout(G, seed=42) # グラフの描画レイアウトを固定

print("学習を開始します...")
for epoch in range(1, 31):
    model.train()
    optimizer.zero_grad()

    output = model(features, adj)

    # わずか2人のリーダーの損失（エラー）だけで学習！
    loss = criterion(output[train_mask], labels[train_mask])
    loss.backward()
    optimizer.step()

    # 予測結果の取得
    preds = output.max(1)[1].numpy()

    # --- Colab上での動的グラフ描画 ---
    clear_output(wait=True)
    plt.figure(figsize=(8, 6))

    # 予測されたクラス（0=紫、1=黄色など）でノードを色分け
    nx.draw(
        G, pos, with_labels=True,
        node_color=preds, cmap=plt.cm.coolwarm,
        node_size=500, font_color="white", font_weight="bold"
    )

    # リーダー2人を強調表示（四角形にする）
    nx.draw_networkx_nodes(G, pos, nodelist=[0], node_shape="s", node_size=700, node_color=[preds[0]], cmap=plt.cm.coolwarm, edgecolors="black", linewidths=2)
    nx.draw_networkx_nodes(G, pos, nodelist=[33], node_shape="s", node_size=700, node_color=[preds[33]], cmap=plt.cm.coolwarm, edgecolors="black", linewidths=2)

    plt.title(f"GNN Training - Epoch: {epoch:02d} | Loss: {loss.item():.4f}", fontsize=14)
    plt.show()
    time.sleep(0.2) # アニメーション速度の調整

# 最終結果の評価
model.eval()
final_output = model(features, adj)
final_preds = final_output.max(1)[1]
correct = final_preds[test_mask].eq(labels[test_mask]).sum().item()
accuracy = correct / test_mask.sum().item()

print(f"【実験結果】")
print(f"正解を知らされていなかった32人に対する予測正解率: {accuracy * 100:.1f}%")

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from sklearn.datasets import load_digits
from sklearn.metrics import pairwise_distances
import numpy as np
import matplotlib.pyplot as plt

# =====================================================================
# 1. 内蔵データセット（Digits）の読み込みとグラフ構造の自動構築
# =====================================================================
print("内蔵データセットを読み込んでいます...")
digits = load_digits()

# =====================================================================
# 読み込んだデータ（画像とラベル）を10枚並べて表示
# =====================================================================
plt.figure(figsize=(15, 3))

# 先頭から10枚の画像を表示
for index in range(10):
    # 8x8のグリッド状にサブプロットを配置 (1行10列)
    plt.subplot(1, 10, index + 1)

    # digits.images には、すでに 8x8 の行列データが入っています
    # cmap=plt.cm.gray_r で「白黒反転（文字を黒、背景を白）」にして見やすくします
    plt.imshow(digits.images[index], cmap=plt.cm.gray_r, interpolation='nearest')

    # 各画像の上部に、対応するラベル（目的変数）を表示
    plt.title(f"Label: {digits.target[index]}", fontsize=12, fontweight="bold")

    # グラフの目盛り（軸の数字）は邪魔なので非表示にします
    plt.axis('off')

plt.suptitle("Input Data (Features: 8x8 Pixels) & Target Labels", fontsize=14, y=1.1, fontweight="bold")
plt.show()

# =====================================================================
# データの「中身の形状（次元）」もテキストで確認
# =====================================================================
print("\n=== データ構造の詳細 ===")
print(f"1枚目の画像（行列）の形状: {digits.images[0].shape} (縦8ピクセル × 横8ピクセル)")
print(f"GNNに入力した説明変数（1次元化）の形状: {digits.data[0].shape} (64次元のベクトル)")
print(f"1枚目の画像の実データ（ピクセル値の一例）:\n{digits.data[0].round().astype(int).reshape(8,8)}")

# 説明変数 X: 各ノード（画像）のプロフィール（8x8マスのピクセル値 = 64次元）
features = torch.tensor(digits.data, dtype=torch.float32)

# 目的変数 Y: 各ノードの正解ラベル（0 〜 9 の数字クラス）
labels = torch.tensor(digits.target, dtype=torch.long)

num_nodes = features.shape[0]   # 1797枚の画像ノード
input_dim = features.shape[1]   # 64次元の説明変数
num_classes = 10                # 10クラス分類

print(f"データ読み込み完了! 画像数(ノード): {num_nodes}, 説明変数の次元: {input_dim}, クラス数: {num_classes}")

print("画像同士の類似度からネットワーク（エッジ）を構築中...")
# 各画像間の距離を計算し、「特に見た目が似ている画像トップ5」同士を線（エッジ）で結ぶ
dist_matrix = pairwise_distances(digits.data, metric='euclidean')
adj_matrix = torch.zeros((num_nodes, num_nodes), dtype=torch.float32)

top_k = 5
for i in range(num_nodes):
    # 自分自身を除外して、最も近い（似ている）インデックスを取得
    nearest_neighbors = np.argsort(dist_matrix[i])[1:top_k+1]
    for n in nearest_neighbors:
        adj_matrix[i, n] = 1.0
        adj_matrix[n, i] = 1.0 # 無向グラフ

# 訓練用（100個）とテスト用（残りの1000個）のマスクを作成
train_mask = torch.zeros(num_nodes, dtype=torch.bool)
train_mask[:100] = True
test_mask = torch.zeros(num_nodes, dtype=torch.bool)
test_mask[100:1100] = True

# =====================================================================
# 2. GCNモデルの定義
# =====================================================================
class GCNLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.FloatTensor(in_features, out_features))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, x, adj):
        # 対称正規化隣接行列の計算
        adj_tilde = adj + torch.eye(adj.size(0))
        degree = torch.sum(adj_tilde, dim=1)
        D_inv_sqrt = torch.diag(torch.pow(degree, -0.5))
        D_inv_sqrt[torch.isinf(D_inv_sqrt)] = 0.0
        adj_norm = torch.mm(torch.mm(D_inv_sqrt, adj_tilde), D_inv_sqrt)

        # メッセージパッシング
        return torch.mm(adj_norm, torch.mm(x, self.weight))

class DigitsGNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()
        self.gcn1 = GCNLayer(input_dim, hidden_dim)
        self.gcn2 = GCNLayer(hidden_dim, num_classes)

    def forward(self, x, adj):
        x = F.relu(self.gcn1(x, adj))
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.gcn2(x, adj)
        return F.log_softmax(x, dim=1)

# =====================================================================
# 3. 訓練と評価の実行
# =====================================================================
# 64次元(画素値) -> 32次元(隠れ層) -> 10次元(予測数字)
model = DigitsGNN(input_dim=input_dim, hidden_dim=32, num_classes=num_classes)
optimizer = optim.Adam(model.parameters(), lr=0.01, weight_decay=5e-4)
criterion = nn.NLLLoss()

print("\nGNNの学習を開始します...")
for epoch in range(1, 101):
    model.train()
    optimizer.zero_grad()

    output = model(features, adj_matrix)
    loss = criterion(output[train_mask], labels[train_mask])

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0 or epoch == 1:
        model.eval()
        with torch.no_grad():
            preds = output.max(1)[1]
            correct = preds[test_mask].eq(labels[test_mask]).sum().item()
            acc = correct / test_mask.sum().item()
            print(f"Epoch: {epoch:03d} | 訓練データの損失: {loss.item():.4f} | 未知のデータに対する予測精度: {acc*100:.1f}%")

import matplotlib.pyplot as plt
import networkx as nx

# =====================================================================
# 可視化用の設定（最初の100ノードに絞る）
# =====================================================================
num_viz_nodes = 100

# 1. モデルを評価モードにして、最終的な予測結果（クラス）を取得
model.eval()
with torch.no_grad():
    all_output = model(features, adj_matrix)
    all_preds = all_output.max(1)[1].numpy()  # AIの予測した数字 (0〜9)

# 2. 最初の100ノード分の部分隣接行列を切り出し
sub_adj = adj_matrix[:num_viz_nodes, :num_viz_nodes].numpy()
sub_preds = all_preds[:num_viz_nodes]
sub_labels = labels[:num_viz_nodes].numpy()

# 3. NetworkXのグラフオブジェクトを構築
G_viz = nx.from_numpy_array(sub_adj)

# =====================================================================
# グラフの描画
# =====================================================================
plt.figure(figsize=(12, 10))

# ノードの配置ルール（春モデルレイアウト：繋がりの強いノードほど近くに配置される）
pos_viz = nx.spring_layout(G_viz, k=0.3, seed=42)

# ノードを描画（色はAIが予測した「数字クラス」に基づいて10色に色分け）
# coolwarmやtab10などのカラーマップを使用
scatter = nx.draw_networkx_nodes(
    G_viz, pos_viz,
    node_color=sub_preds,
    cmap=plt.cm.tab10,
    node_size=350,
    edgecolors="black",
    linewidths=0.8
)

# ノードの中に「実際の正解の数字」をテキストとして描画
labels_dict = {i: str(sub_labels[i]) for i in range(num_viz_nodes)}
nx.draw_networkx_labels(G_viz, pos_viz, labels=labels_dict, font_size=8, font_color="black", font_weight="bold")

# エッジ（画像同士の類似度の線）を描画（少し薄くして見やすくします）
nx.draw_networkx_edges(G_viz, pos_viz, alpha=0.2, edge_color="gray")

# カラーバー（どの色が何の数字を表すか）を表示
cbar = plt.colorbar(scatter, ticks=range(10), label="AI Predicted Digits (0-9)")
cbar.set_ticklabels([str(i) for i in range(10)])

plt.title("GNN Classification Result Visualized (First 100 Nodes)", fontsize=14, fontweight="bold")
plt.axis("off") # 軸は非表示
plt.show()

import matplotlib.pyplot as plt

# 学習ログ（エポック, 損失, 精度）
epochs = [1, 20, 40, 60, 80, 100]
train_loss = [11.0581, 0.4705, 0.1629, 0.0796, 0.0372, 0.0153]
test_acc = [13.6, 68.5, 74.1, 79.4, 79.5, 78.4]

fig, ax1 = plt.subplots(figsize=(8, 5))

# 損失（左軸）
color = 'tab:red'
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Train Loss', color=color)
ax1.plot(epochs, train_loss, marker='o', color=color, label='Train Loss')
ax1.tick_params(axis='y', labelcolor=color)
ax1.set_yscale('log')  # 損失が大きく変化するため対数スケール推奨

# 精度（右軸）
ax2 = ax1.twinx()
color = 'tab:blue'
ax2.set_ylabel('Test Accuracy (%)', color=color)
ax2.plot(epochs, test_acc, marker='s', color=color, label='Test Accuracy')
ax2.tick_params(axis='y', labelcolor=color)
ax2.set_ylim(0, 100)

plt.title('GNN Training Progress (Digits Graph)')
fig.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx

# =====================================================================
# 1. 疑似ECサイトデータの作成（プロフィール ＋ 共同購入ネットワーク）
# =====================================================================
np.random.seed(42)
torch.manual_seed(42)

num_products = 90  # 全商品数
# カテゴリ: 0=電子機器(Gadget), 1=書籍(Book), 2=ファッション(Cloth)
labels_np = np.array([0]*30 + [1]*30 + [2]*30)
labels = torch.tensor(labels_np, dtype=torch.long)

# 説明変数 X: [価格(正規化), レビューの星(1~5)] の2次元プロフィール
# ※わざとカテゴリ間で価格とレビューに大きな差が出ないように設定（プロフィールだけでは分類困難にする）
features_np = np.random.randn(num_products, 2) * 2 + 3
features = torch.tensor(features_np, dtype=torch.float32)

# 隣接行列 A: 共同購入ネットワークの構築
adj_matrix = torch.zeros((num_products, num_products), dtype=torch.float32)

# 同じカテゴリ同士は「一緒に買われやすい」リンクをランダムに作成
for i in range(num_products):
    for j in range(i + 1, num_products):
        if labels_np[i] == labels_np[j]:
            if np.random.rand() < 0.25: # 同カテゴリの共同購入確率
                adj_matrix[i, j] = 1.0
                adj_matrix[j, i] = 1.0
        else:
            if np.random.rand() < 0.01: # 異カテゴリ間の偶発的な共同購入確率
                adj_matrix[i, j] = 1.0
                adj_matrix[j, i] = 1.0

# 訓練用（各カテゴリ3個ずつ、計9個だけ正解を教える）
train_mask = torch.zeros(num_products, dtype=torch.bool)
train_mask[[0, 1, 2, 30, 31, 32, 60, 61, 62]] = True
test_mask = ~train_mask

# =====================================================================
# 2. GCNモデルの定義
# =====================================================================
class GCNLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.FloatTensor(in_features, out_features))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, x, adj):
        adj_tilde = adj + torch.eye(adj.size(0))
        degree = torch.sum(adj_tilde, dim=1)
        D_inv_sqrt = torch.diag(torch.pow(degree, -0.5))
        D_inv_sqrt[torch.isinf(D_inv_sqrt)] = 0.0
        adj_norm = torch.mm(torch.mm(D_inv_sqrt, adj_tilde), D_inv_sqrt)
        return torch.mm(adj_norm, torch.mm(x, self.weight))

class ECommerceGNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, num_classes):
        super().__init__()
        self.gcn1 = GCNLayer(input_dim, hidden_dim)
        self.gcn2 = GCNLayer(hidden_dim, num_classes)

    def forward(self, x, adj):
        x = F.relu(self.gcn1(x, adj))
        x = F.dropout(x, p=0.2, training=self.training)
        x = self.gcn2(x, adj)
        return F.log_softmax(x, dim=1)

# =====================================================================
# 3. 訓練の実行
# =====================================================================
model = ECommerceGNN(input_dim=2, hidden_dim=16, num_classes=3)
optimizer = optim.Adam(model.parameters(), lr=0.02, weight_decay=5e-4)
criterion = nn.NLLLoss()

print("ECサイトのレコメンドネットワークでのGNN学習開始...")
for epoch in range(1, 151):
    model.train()
    optimizer.zero_grad()
    output = model(features, adj_matrix)
    loss = criterion(output[train_mask], labels[train_mask])
    loss.backward()
    optimizer.step()

model.eval()
with torch.no_grad():
    final_output = model(features, adj_matrix)
    all_preds = final_output.max(1)[1].numpy()
    correct = final_output.max(1)[1][test_mask].eq(labels[test_mask]).sum().item()
    print(f"最終予測精度 (未知の商品81個に対して): {correct / test_mask.sum().item() * 100:.1f}%")

# =====================================================================
# 4. 共同購入グラフの可視化
# =====================================================================
G_viz = nx.from_numpy_array(adj_matrix.numpy())
plt.figure(figsize=(10, 8))
pos_viz = nx.spring_layout(G_viz, k=0.25, seed=42)

# ノードを描画（色は予測カテゴリ: 赤=ガジェット、青=本、緑=服 のように3色に分かれます）
scatter = nx.draw_networkx_nodes(
    G_viz, pos_viz, node_color=all_preds, cmap=plt.cm.Set1,
    node_size=200, edgecolors="black", linewidths=0.6
)

# 訓練に使ったわずか9個の「ヒント商品」を大きな四角で囲って強調
train_indices = np.where(train_mask.numpy() == True)[0]
nx.draw_networkx_nodes(G_viz, pos_viz, nodelist=list(train_indices), node_shape="s", node_size=400, node_color=all_preds[train_indices], cmap=plt.cm.Set1, edgecolors="black", linewidths=2)

# 共同購入の結びつき（エッジ）を描画
nx.draw_networkx_edges(G_viz, pos_viz, alpha=0.15, edge_color="gray")

plt.title("E-Commerce Product Network (Square = Trained Hint Products)", fontsize=12, fontweight="bold")
plt.axis("off")
plt.show()

features

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from sklearn.metrics import roc_auc_score

# =====================================================================
# 1. 疑似データの構築と「未来のリンク（検証用）」の隠蔽
# =====================================================================
np.random.seed(42)
torch.manual_seed(42)

num_products = 60  # 分かりやすさのためノード数を60に調整
labels_np = np.array([0]*20 + [1]*20 + [2]*20) # 3カテゴリ

# 説明変数 X: 2次元のダミープロフィール
features = torch.tensor(np.random.randn(num_products, 2) * 2 + 3, dtype=torch.float32)

# 本来のすべてのリンク（グラウンドトゥルース）を定義
edges = []
for i in range(num_products):
    for j in range(i + 1, num_products):
        if labels_np[i] == labels_np[j] and np.random.rand() < 0.3:
            edges.append((i, j))
        elif labels_np[i] != labels_np[j] and np.random.rand() < 0.01:
            edges.append((i, j))

all_edges = np.array(edges)
num_edges = len(all_edges)

# 20%のリンクを「未来（テスト用）」として隠し、80%を「現在（学習用）」とする
shuffled_indices = np.random.permutation(num_edges)
train_edge_idx = shuffled_indices[:int(num_edges * 0.8)]
test_edge_idx = shuffled_indices[int(num_edges * 0.8):]

train_edges = all_edges[train_edge_idx]
test_edges = all_edges[test_edge_idx]

# 学習用の隣接行列 A を構築（隠されたリンクは0になっている）
adj_train = torch.zeros((num_products, num_products), dtype=torch.float32)
for u, v in train_edges:
    adj_train[u, v] = 1.0
    adj_train[v, u] = 1.0

# 同数の「絶対に繋がらないペア（負例）」をテスト用にサンプリング
negative_edges = []
while len(negative_edges) < len(test_edges):
    u, v = np.random.randint(0, num_products, size=2)
    if u != v and (u, v) not in edges and (v, u) not in edges and (u, v) not in negative_edges:
        negative_edges.append((u, v))
negative_edges = np.array(negative_edges)

# =====================================================================
# 2. リンク予測用 GNN（GCN）モデルの定義
# =====================================================================
class GCNLayer(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = nn.Parameter(torch.FloatTensor(in_features, out_features))
        nn.init.xavier_uniform_(self.weight)

    def forward(self, x, adj):
        adj_tilde = adj + torch.eye(adj.size(0))
        degree = torch.sum(adj_tilde, dim=1)
        D_inv_sqrt = torch.diag(torch.pow(degree, -0.5))
        D_inv_sqrt[torch.isinf(D_inv_sqrt)] = 0.0
        adj_norm = torch.mm(torch.mm(D_inv_sqrt, adj_tilde), D_inv_sqrt)
        return torch.mm(adj_norm, torch.mm(x, self.weight))

class LinkPredictionGNN(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.gcn1 = GCNLayer(input_dim, hidden_dim)
        self.gcn2 = GCNLayer(hidden_dim, hidden_dim) # 最終ノードベクトルを出力

    def forward(self, x, adj):
        x = F.relu(self.gcn1(x, adj))
        return self.gcn2(x, adj)

    def compute_link_score(self, z, edge_list):
        # 2つのノードベクトルの内積（類似度）を計算し、リンクの存在確率（0〜1）にする
        u_embed = z[edge_list[:, 0]]
        v_embed = z[edge_list[:, 1]]
        scores = torch.sum(u_embed * v_embed, dim=1)
        return torch.sigmoid(scores)

# =====================================================================
# 3. 訓練ループ（リンクの有無を当てるバイナリ分類として学習）
# =====================================================================
model = LinkPredictionGNN(input_dim=2, hidden_dim=16)
optimizer = optim.Adam(model.parameters(), lr=0.02, weight_decay=5e-4)

print("隠された未来の購入リンクを予測する学習を開始...")
for epoch in range(1, 151):
    model.train()
    optimizer.zero_grad()

    # 1. GNNで全ノードの構造ベクトル（z）を生成
    z = model(features, adj_train)

    # 2. 存在するリンク（正例）と存在しないリンク（負例）のスコアを計算
    pos_scores = model.compute_link_score(z, train_edges)

    # 訓練用の負例をランダムサンプリング
    train_neg_edges = np.array([np.random.randint(0, num_products, size=2) for _ in range(len(train_edges))])
    neg_scores = model.compute_link_score(z, train_neg_edges)

    # 損失関数（存在するものは1に、存在しないものは0に近づける）
    loss = -torch.mean(torch.log(pos_scores + 1e-15) + torch.log(1.0 - neg_scores + 1e-15))

    loss.backward()
    optimizer.step()

    if epoch % 30 == 0:
        # 検証：隠されていたテスト用リンクの予測精度（AUCスコア）を測定
        model.eval()
        with torch.no_grad():
            z_eval = model(features, adj_train)
            test_pos_preds = model.compute_link_score(z_eval, test_edges).numpy()
            test_neg_preds = model.compute_link_score(z_eval, negative_edges).numpy()

            y_true = np.ones(len(test_pos_preds))
            y_true = np.concatenate([y_true, np.zeros(len(test_neg_preds))])
            y_pred = np.concatenate([test_pos_preds, test_neg_preds])

            auc = roc_auc_score(y_true, y_pred)
            print(f"Epoch: {epoch:03d} | Train Loss: {loss.item():.4f} | 未来のリンク予測精度 (AUC): {auc*100:.1f}%")

# =====================================================================
# 4. 「未来のリンク」の予測結果をビジュアル確認
# =====================================================================
model.eval()
with torch.no_grad():
    z_final = model(features, adj_train)
    # 隠されていた未来のリンクの予測確率をトップ5だけ表示してみる
    test_scores = model.compute_link_score(z_final, test_edges).numpy()

print("\n=== AIが見つけた【未来のあわせて買いたいペア】TOP 5 ===")
top_5_idx = np.argsort(test_scores)[::-1][:5]
for idx in top_5_idx:
    u, v = test_edges[idx]
    print(f"商品 {u:02d} と 商品 {v:02d} -> AIの予測共同購入確率: {test_scores[idx]*100:.1f}%  (正解: 実際に未来で購入された)")

import matplotlib.pyplot as plt
import networkx as nx

# =====================================================================
# 1. GNNが予測した「未来のリンク（確率90%以上）」を抽出
# =====================================================================
model.eval()
with torch.no_grad():
    # 全ノードの最終ベクトル（埋め込み）を取得
    z_final = model(features, adj_train)

    # すべての商品ペアの組み合わせに対して相性スコア（確率）を計算
    predicted_edges = []
    for i in range(num_products):
        for j in range(i + 1, num_products):
            # すでに「現在わかっているリンク（学習用）」は除外
            if adj_train[i, j] == 0:
                # 商品iと商品jの相性をGNNベクトルから計算
                score = model.compute_link_score(z_final, np.array([[i, j]]))[0].item()
                # AIが「90%以上の確率で将来一緒に買われる！」と予言したペアを抽出
                if score > 0.90:
                    predicted_edges.append((i, j))

print(f"AIが強く予言した『未来の購入リンク』の数: {len(predicted_edges)}本")

# =====================================================================
# 2. グラフオブジェクトの構築
# =====================================================================
# 学習に使った既存のグラフ（80%のリンク）をベースにする
G_future = nx.from_numpy_array(adj_train.numpy())

# AIが予言した「未来のリンク」を別の種類のエッジとしてグラフに追加
G_future.add_edges_from(predicted_edges)

# =====================================================================
# 3. グラフの描画
# =====================================================================
plt.figure(figsize=(12, 10))

# 繋がりの強さで配置を決める（同じジャンルが固まるレイアウト）
pos_future = nx.spring_layout(G_future, k=0.25, seed=42)

# ① ノードの描画（実際の商品カテゴリで色分け。0=赤, 1=青, 2=緑）
scatter = nx.draw_networkx_nodes(
    G_future, pos_future,
    node_color=labels_np,
    cmap=plt.cm.Set1,
    node_size=250,
    edgecolors="black",
    linewidths=0.8
)

# ② 既存のリンク（学習で見せていた80%の線）を細いグレーで描画
existing_edges = [(u, v) for u, v in G_future.edges() if (u, v) not in predicted_edges]
nx.draw_networkx_edges(G_future, pos_future, edgelist=existing_edges, alpha=0.15, edge_color="gray")

# ③ ★ここが主役★ AIが予言した「未来のリンク（隠されていた20%）」を太い赤線で描画
nx.draw_networkx_edges(G_future, pos_future, edgelist=predicted_edges, alpha=0.8, edge_color="red", width=2.0)

# ④ 【修正ポイント】ノード数60に合わせて、各カテゴリの先頭3ノード（計9個）を四角で強調
# カテゴリ0: 0,1,2 | カテゴリ1: 20,21,22 | カテゴリ2: 40,41,42
hint_nodes = [0, 1, 2, 20, 21, 22, 40, 41, 42]
nx.draw_networkx_nodes(
    G_future, pos_future,
    nodelist=hint_nodes,
    node_shape="s",
    node_size=350,
    node_color=labels_np[hint_nodes],
    cmap=plt.cm.Set1,
    edgecolors="black",
    linewidths=1.5
)

# 凡例の設定
plt.title("GNN Link Prediction Visualization\n(Gray lines = Existing Purchase, Red lines = AI Predicted Future Purchase)", fontsize=14, fontweight="bold")
plt.axis("off")
plt.show()

# 1. すべてのリンク（全100本あったとする）からランダムに分ける
train_edges = all_edges[train_edge_idx]  # 80本（現在わかっている購入履歴）
test_edges = all_edges[test_edge_idx]    # 20本（未来に起きる購入履歴：AIには隠す）

# 2. 80本だけで「学習用の隣接行列」を作る
adj_train = torch.zeros((num_products, num_products))
for u, v in train_edges:
    adj_train[u, v] = 1.0
    adj_train[v, u] = 1.0

adj_train

import matplotlib.pyplot as plt

import re
import matplotlib.pyplot as plt

# 提示されたログデータ
log_data_relu = """
Episode 0: Reward = -92.89, Captures = 0, Avg Reward = -92.89, Avg Captures = 0.00
Actor Loss: -0.0148 | Critic Loss: 0.0817 | Avg Entropy: 1.6078
Episode 1: Reward = -150.94, Captures = 0, Avg Reward = -121.92, Avg Captures = 0.00
Actor Loss: -0.0162 | Critic Loss: 0.0661 | Avg Entropy: 1.6080
Episode 2: Reward = -134.85, Captures = 0, Avg Reward = -126.23, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0492 | Avg Entropy: 1.6080
Episode 3: Reward = -120.37, Captures = 0, Avg Reward = -124.77, Avg Captures = 0.00
Actor Loss: -0.0159 | Critic Loss: 0.0512 | Avg Entropy: 1.6079
Episode 4: Reward = -94.46, Captures = 0, Avg Reward = -118.70, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.0488 | Avg Entropy: 1.6078
Episode 5: Reward = -125.08, Captures = 0, Avg Reward = -119.77, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.0542 | Avg Entropy: 1.6078
Episode 6: Reward = -136.06, Captures = 0, Avg Reward = -122.10, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0366 | Avg Entropy: 1.6077
Episode 7: Reward = -127.98, Captures = 0, Avg Reward = -122.83, Avg Captures = 0.00
Actor Loss: -0.0171 | Critic Loss: 0.0428 | Avg Entropy: 1.6076
Episode 8: Reward = -121.48, Captures = 0, Avg Reward = -122.68, Avg Captures = 0.00
Actor Loss: -0.0171 | Critic Loss: 0.0488 | Avg Entropy: 1.6077
Episode 9: Reward = -114.44, Captures = 0, Avg Reward = -121.86, Avg Captures = 0.00
Actor Loss: -0.0177 | Critic Loss: 0.0409 | Avg Entropy: 1.6076
Episode 10: Reward = -153.76, Captures = 0, Avg Reward = -124.76, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.0376 | Avg Entropy: 1.6076
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 11: Reward = -148.98, Captures = 0, Avg Reward = -126.78, Avg Captures = 0.00
Actor Loss: -0.0184 | Critic Loss: 0.0286 | Avg Entropy: 1.6076
Episode 12: Reward = -129.66, Captures = 0, Avg Reward = -127.00, Avg Captures = 0.00
Actor Loss: -0.0193 | Critic Loss: 0.0312 | Avg Entropy: 1.6072
Episode 13: Reward = -142.24, Captures = 0, Avg Reward = -128.09, Avg Captures = 0.00
Actor Loss: -0.0187 | Critic Loss: 0.0535 | Avg Entropy: 1.6074
Episode 14: Reward = -129.47, Captures = 0, Avg Reward = -128.18, Avg Captures = 0.00
Actor Loss: -0.0166 | Critic Loss: 0.0329 | Avg Entropy: 1.6073
Episode 15: Reward = -100.46, Captures = 0, Avg Reward = -126.45, Avg Captures = 0.00
Actor Loss: -0.0189 | Critic Loss: 0.0773 | Avg Entropy: 1.6071
Episode 16: Reward = -136.73, Captures = 0, Avg Reward = -127.05, Avg Captures = 0.00
Actor Loss: -0.0165 | Critic Loss: 0.0393 | Avg Entropy: 1.6072
Episode 17: Reward = -89.46, Captures = 0, Avg Reward = -124.96, Avg Captures = 0.00
Actor Loss: -0.0133 | Critic Loss: 0.0481 | Avg Entropy: 1.6072
Episode 18: Reward = -138.63, Captures = 0, Avg Reward = -125.68, Avg Captures = 0.00
Actor Loss: -0.0195 | Critic Loss: 0.0424 | Avg Entropy: 1.6072
Episode 19: Reward = -151.93, Captures = 0, Avg Reward = -126.99, Avg Captures = 0.00
Actor Loss: -0.0188 | Critic Loss: 0.0268 | Avg Entropy: 1.6073
Episode 20: Reward = -144.71, Captures = 0, Avg Reward = -127.84, Avg Captures = 0.00
Actor Loss: -0.0161 | Critic Loss: 0.0269 | Avg Entropy: 1.6073
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 21: Reward = -101.36, Captures = 0, Avg Reward = -126.63, Avg Captures = 0.00
Actor Loss: -0.0203 | Critic Loss: 0.0623 | Avg Entropy: 1.6071
Episode 22: Reward = -163.56, Captures = 0, Avg Reward = -128.24, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.0323 | Avg Entropy: 1.6071
Episode 23: Reward = -82.30, Captures = 0, Avg Reward = -126.33, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.0564 | Avg Entropy: 1.6071
Episode 24: Reward = -127.81, Captures = 0, Avg Reward = -126.39, Avg Captures = 0.00
Actor Loss: -0.0168 | Critic Loss: 0.0369 | Avg Entropy: 1.6071
Episode 25: Reward = -94.26, Captures = 0, Avg Reward = -125.15, Avg Captures = 0.00
Actor Loss: -0.0211 | Critic Loss: 0.0724 | Avg Entropy: 1.6069
Episode 26: Reward = -97.42, Captures = 0, Avg Reward = -124.12, Avg Captures = 0.00
Actor Loss: -0.0171 | Critic Loss: 0.0566 | Avg Entropy: 1.6070
Episode 27: Reward = -137.14, Captures = 0, Avg Reward = -124.59, Avg Captures = 0.00
Actor Loss: -0.0185 | Critic Loss: 0.0371 | Avg Entropy: 1.6071
Episode 28: Reward = -148.75, Captures = 0, Avg Reward = -125.42, Avg Captures = 0.00
Actor Loss: -0.0182 | Critic Loss: 0.0326 | Avg Entropy: 1.6070
Episode 29: Reward = -149.28, Captures = 0, Avg Reward = -126.22, Avg Captures = 0.00
Actor Loss: -0.0184 | Critic Loss: 0.0421 | Avg Entropy: 1.6070
Episode 30: Reward = -83.64, Captures = 0, Avg Reward = -124.84, Avg Captures = 0.00
Actor Loss: -0.0200 | Critic Loss: 0.0724 | Avg Entropy: 1.6070
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 31: Reward = -114.05, Captures = 0, Avg Reward = -124.51, Avg Captures = 0.00
Actor Loss: -0.0180 | Critic Loss: 0.0621 | Avg Entropy: 1.6069
Episode 32: Reward = -128.93, Captures = 0, Avg Reward = -124.64, Avg Captures = 0.00
Actor Loss: -0.0139 | Critic Loss: 0.0330 | Avg Entropy: 1.6071
Episode 33: Reward = -156.58, Captures = 0, Avg Reward = -125.58, Avg Captures = 0.00
Actor Loss: -0.0150 | Critic Loss: 0.0285 | Avg Entropy: 1.6073
Episode 34: Reward = -169.56, Captures = 0, Avg Reward = -126.84, Avg Captures = 0.00
Actor Loss: -0.0178 | Critic Loss: 0.0432 | Avg Entropy: 1.6072
Episode 35: Reward = -125.43, Captures = 0, Avg Reward = -126.80, Avg Captures = 0.00
Actor Loss: -0.0184 | Critic Loss: 0.0460 | Avg Entropy: 1.6072
Episode 36: Reward = -164.68, Captures = 0, Avg Reward = -127.82, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.0256 | Avg Entropy: 1.6072
Episode 37: Reward = -75.59, Captures = 0, Avg Reward = -126.45, Avg Captures = 0.00
Actor Loss: -0.0174 | Critic Loss: 0.0790 | Avg Entropy: 1.6072
Episode 38: Reward = -133.58, Captures = 0, Avg Reward = -126.63, Avg Captures = 0.00
Actor Loss: -0.0151 | Critic Loss: 0.0371 | Avg Entropy: 1.6071
Episode 39: Reward = -158.56, Captures = 0, Avg Reward = -127.43, Avg Captures = 0.00
Actor Loss: -0.0178 | Critic Loss: 0.0324 | Avg Entropy: 1.6072
Episode 40: Reward = -90.19, Captures = 0, Avg Reward = -126.52, Avg Captures = 0.00
Actor Loss: -0.0227 | Critic Loss: 0.0669 | Avg Entropy: 1.6073
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 41: Reward = -134.75, Captures = 0, Avg Reward = -126.71, Avg Captures = 0.00
Actor Loss: -0.0174 | Critic Loss: 0.0390 | Avg Entropy: 1.6073
Episode 42: Reward = -121.44, Captures = 0, Avg Reward = -126.59, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.0413 | Avg Entropy: 1.6073
Episode 43: Reward = -132.99, Captures = 0, Avg Reward = -126.74, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0317 | Avg Entropy: 1.6072
Episode 44: Reward = -143.59, Captures = 0, Avg Reward = -127.11, Avg Captures = 0.00
Actor Loss: -0.0153 | Critic Loss: 0.0296 | Avg Entropy: 1.6072
Episode 45: Reward = -136.20, Captures = 0, Avg Reward = -127.31, Avg Captures = 0.00
Actor Loss: -0.0198 | Critic Loss: 0.0421 | Avg Entropy: 1.6072
Episode 46: Reward = -129.43, Captures = 0, Avg Reward = -127.35, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0356 | Avg Entropy: 1.6071
Episode 47: Reward = -139.89, Captures = 0, Avg Reward = -127.62, Avg Captures = 0.00
Actor Loss: -0.0180 | Critic Loss: 0.0427 | Avg Entropy: 1.6071
Episode 48: Reward = -127.79, Captures = 0, Avg Reward = -127.62, Avg Captures = 0.00
Actor Loss: -0.0151 | Critic Loss: 0.0429 | Avg Entropy: 1.6072
Episode 49: Reward = -152.00, Captures = 0, Avg Reward = -128.11, Avg Captures = 0.00
Actor Loss: -0.0159 | Critic Loss: 0.0400 | Avg Entropy: 1.6070
Episode 50: Reward = -149.53, Captures = 0, Avg Reward = -128.53, Avg Captures = 0.00
Actor Loss: -0.0137 | Critic Loss: 0.0313 | Avg Entropy: 1.6070
"""

log_data_gelu = """
Episode 0: Reward = -126.81, Captures = 0, Avg Reward = -126.81, Avg Captures = 0.00
Actor Loss: -0.0154 | Critic Loss: 0.1027 | Avg Entropy: 1.6085
Episode 1: Reward = -96.68, Captures = 0, Avg Reward = -111.75, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.1005 | Avg Entropy: 1.6085
Episode 2: Reward = -125.40, Captures = 0, Avg Reward = -116.30, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0900 | Avg Entropy: 1.6085
Episode 3: Reward = -158.32, Captures = 0, Avg Reward = -126.80, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.1070 | Avg Entropy: 1.6085
Episode 4: Reward = -95.05, Captures = 0, Avg Reward = -120.45, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.1072 | Avg Entropy: 1.6086
Episode 5: Reward = -142.06, Captures = 0, Avg Reward = -124.05, Avg Captures = 0.00
Actor Loss: -0.0152 | Critic Loss: 0.0926 | Avg Entropy: 1.6085
Episode 6: Reward = -140.07, Captures = 0, Avg Reward = -126.34, Avg Captures = 0.00
Actor Loss: -0.0163 | Critic Loss: 0.0854 | Avg Entropy: 1.6086
Episode 7: Reward = -121.78, Captures = 0, Avg Reward = -125.77, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0947 | Avg Entropy: 1.6086
Episode 8: Reward = -149.45, Captures = 0, Avg Reward = -128.40, Avg Captures = 0.00
Actor Loss: -0.0142 | Critic Loss: 0.0880 | Avg Entropy: 1.6086
Episode 9: Reward = -116.19, Captures = 0, Avg Reward = -127.18, Avg Captures = 0.00
Actor Loss: -0.0142 | Critic Loss: 0.0961 | Avg Entropy: 1.6086
Episode 10: Reward = -148.00, Captures = 0, Avg Reward = -129.07, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.0856 | Avg Entropy: 1.6086
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 11: Reward = -133.20, Captures = 0, Avg Reward = -129.42, Avg Captures = 0.00
Actor Loss: -0.0155 | Critic Loss: 0.0845 | Avg Entropy: 1.6086
Episode 12: Reward = -133.22, Captures = 0, Avg Reward = -129.71, Avg Captures = 0.00
Actor Loss: -0.0152 | Critic Loss: 0.0966 | Avg Entropy: 1.6086
Episode 13: Reward = -72.73, Captures = 0, Avg Reward = -125.64, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.0961 | Avg Entropy: 1.6086
Episode 14: Reward = -139.48, Captures = 0, Avg Reward = -126.56, Avg Captures = 0.00
Actor Loss: -0.0142 | Critic Loss: 0.0665 | Avg Entropy: 1.6086
Episode 15: Reward = -143.87, Captures = 0, Avg Reward = -127.64, Avg Captures = 0.00
Actor Loss: -0.0168 | Critic Loss: 0.0616 | Avg Entropy: 1.6086
Episode 16: Reward = -116.86, Captures = 0, Avg Reward = -127.01, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0652 | Avg Entropy: 1.6086
Episode 17: Reward = -138.34, Captures = 0, Avg Reward = -127.64, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.0519 | Avg Entropy: 1.6086
Episode 18: Reward = -118.95, Captures = 0, Avg Reward = -127.18, Avg Captures = 0.00
Actor Loss: -0.0165 | Critic Loss: 0.0555 | Avg Entropy: 1.6086
Episode 19: Reward = -117.86, Captures = 0, Avg Reward = -126.72, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0448 | Avg Entropy: 1.6086
Episode 20: Reward = -148.68, Captures = 0, Avg Reward = -127.76, Avg Captures = 0.00
Actor Loss: -0.0160 | Critic Loss: 0.0433 | Avg Entropy: 1.6086
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 21: Reward = -111.50, Captures = 0, Avg Reward = -127.02, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.0430 | Avg Entropy: 1.6086
Episode 22: Reward = -141.88, Captures = 0, Avg Reward = -127.67, Avg Captures = 0.00
Actor Loss: -0.0159 | Critic Loss: 0.0384 | Avg Entropy: 1.6086
Episode 23: Reward = -141.98, Captures = 0, Avg Reward = -128.27, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0294 | Avg Entropy: 1.6086
Episode 24: Reward = -136.10, Captures = 0, Avg Reward = -128.58, Avg Captures = 0.00
Actor Loss: -0.0160 | Critic Loss: 0.0316 | Avg Entropy: 1.6086
Episode 25: Reward = -113.64, Captures = 0, Avg Reward = -128.00, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.0453 | Avg Entropy: 1.6086
Episode 26: Reward = -69.11, Captures = 0, Avg Reward = -125.82, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.0737 | Avg Entropy: 1.6086
Episode 27: Reward = -125.86, Avg Reward = -125.82, Avg Captures = 0.00
Actor Loss: -0.0154 | Critic Loss: 0.0458 | Avg Entropy: 1.6086
Episode 28: Reward = -114.83, Captures = 0, Avg Reward = -125.45, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0589 | Avg Entropy: 1.6085
Episode 29: Reward = -141.32, Captures = 0, Avg Reward = -125.97, Avg Captures = 0.00
Actor Loss: -0.0189 | Critic Loss: 0.0324 | Avg Entropy: 1.6085
Episode 30: Reward = -139.23, Captures = 0, Avg Reward = -126.40, Avg Captures = 0.00
Actor Loss: -0.0166 | Critic Loss: 0.0327 | Avg Entropy: 1.6085
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 31: Reward = -176.79, Captures = 0, Avg Reward = -127.98, Avg Captures = 0.00
Actor Loss: -0.0150 | Critic Loss: 0.0383 | Avg Entropy: 1.6084
Episode 32: Reward = -121.66, Captures = 0, Avg Reward = -127.79, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.0380 | Avg Entropy: 1.6084
Episode 33: Reward = -118.52, Captures = 0, Avg Reward = -127.51, Avg Captures = 0.00
Actor Loss: -0.0176 | Critic Loss: 0.0560 | Avg Entropy: 1.6083
Episode 34: Reward = -117.43, Captures = 0, Avg Reward = -127.23, Avg Captures = 0.00
Actor Loss: -0.0206 | Critic Loss: 0.0485 | Avg Entropy: 1.6083
Episode 35: Reward = -128.28, Captures = 0, Avg Reward = -127.25, Avg Captures = 0.00
Actor Loss: -0.0182 | Critic Loss: 0.0354 | Avg Entropy: 1.6082
Episode 36: Reward = -106.43, Captures = 0, Avg Reward = -126.69, Avg Captures = 0.00
Actor Loss: -0.0201 | Critic Loss: 0.0605 | Avg Entropy: 1.6080
Episode 37: Reward = -77.97, Captures = 0, Avg Reward = -125.41, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0656 | Avg Entropy: 1.6080
Episode 38: Reward = -139.04, Captures = 0, Avg Reward = -125.76, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0356 | Avg Entropy: 1.6080
Episode 39: Reward = -115.49, Captures = 0, Avg Reward = -125.50, Avg Captures = 0.00
Actor Loss: -0.0201 | Critic Loss: 0.0476 | Avg Entropy: 1.6078
Episode 40: Reward = -109.83, Captures = 0, Avg Reward = -125.12, Avg Captures = 0.00
Actor Loss: -0.0164 | Critic Loss: 0.0586 | Avg Entropy: 1.6078
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 41: Reward = -118.95, Captures = 0, Avg Reward = -124.97, Avg Captures = 0.00
Actor Loss: -0.0183 | Critic Loss: 0.0338 | Avg Entropy: 1.6076
Episode 42: Reward = -71.75, Captures = 0, Avg Reward = -123.74, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.0718 | Avg Entropy: 1.6079
Episode 43: Reward = -149.73, Captures = 0, Avg Reward = -124.33, Avg Captures = 0.00
Actor Loss: -0.0191 | Critic Loss: 0.0313 | Avg Entropy: 1.6079
Episode 44: Reward = -141.59, Captures = 0, Avg Reward = -124.71, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.0321 | Avg Entropy: 1.6080
Episode 45: Reward = -137.33, Captures = 0, Avg Reward = -124.98, Avg Captures = 0.00
Actor Loss: -0.0177 | Critic Loss: 0.0346 | Avg Entropy: 1.6080
Episode 46: Reward = -136.45, Captures = 0, Avg Reward = -125.23, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.0393 | Avg Entropy: 1.6081
Episode 47: Reward = -136.99, Captures = 0, Avg Reward = -125.47, Avg Captures = 0.00
Actor Loss: -0.0190 | Critic Loss: 0.0306 | Avg Entropy: 1.6080
Episode 48: Reward = -143.60, Captures = 0, Avg Reward = -125.84, Avg Captures = 0.00
Actor Loss: -0.0173 | Critic Loss: 0.0284 | Avg Entropy: 1.6079
Episode 49: Reward = -121.92, Captures = 0, Avg Reward = -125.76, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0450 | Avg Entropy: 1.6080
Episode 50: Reward = -111.40, Captures = 0, Avg Reward = -125.48, Avg Captures = 0.00
Actor Loss: -0.0196 | Critic Loss: 0.0332 | Avg Entropy: 1.6079
"""

def parse_logs(log_text):
    """ログからActor LossとCritic Lossを取り出す関数"""
    actor_losses = []
    critic_losses = []

    # 正規表現で数値を抽出
    pattern = r"Actor Loss:\s*([-\d.]+)\s*\|\s*Critic Loss:\s*([\d.]+)"
    matches = re.findall(pattern, log_text)

    for actor, critic in matches:
        actor_losses.append(float(actor))
        critic_losses.append(float(critic))

    return actor_losses, critic_losses

# データのパース
relu_actor, relu_critic = parse_logs(log_data_relu)
gelu_actor, gelu_critic = parse_logs(log_data_gelu)
episodes = list(range(len(relu_actor)))

# グラフ描画の設定
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# 1. Actor Loss のプロット
ax1.plot(episodes, relu_actor, label='before', color='blue', alpha=0.8)
ax1.plot(episodes, gelu_actor, label='after', color='orange', alpha=0.8)
ax1.set_title('Actor Loss Comparison', fontsize=14, fontweight='bold')
ax1.set_xlabel('Episode', fontsize=12)
ax1.set_ylabel('Loss', fontsize=12)
ax1.grid(True, linestyle='--', alpha=0.6)
ax1.legend(fontsize=11)

# 2. Critic Loss のプロット
ax2.plot(episodes, relu_critic, label='before', color='blue', alpha=0.8)
ax2.plot(episodes, gelu_critic, label='after', color='orange', alpha=0.8)
ax2.set_title('Critic Loss Comparison', fontsize=14, fontweight='bold')
ax2.set_xlabel('Episode', fontsize=12)
ax2.set_ylabel('Loss', fontsize=12)
ax2.grid(True, linestyle='--', alpha=0.6)
ax2.legend(fontsize=11)

plt.tight_layout()
plt.show()

import torch
import torch.nn as nn
import torch.nn.functional as F

# 簡単なグラフ例：4ノード、エッジは 0-1, 1-2, 2-3, 3-0
edge_index = torch.tensor([[0, 1, 2, 3],
                           [1, 2, 3, 0]], dtype=torch.long)  # shape: (2, num_edges)

# 各ノードの特徴量（例：2次元）
x = torch.tensor([[1.0, 0.0],
                  [0.0, 1.0],
                  [1.0, 1.0],
                  [0.0, 0.0]], dtype=torch.float)

num_nodes = x.size(0)

class SimpleMessagePassingLayer(nn.Module):
    def __init__(self, in_dim, out_dim):
        super().__init__()
        # メッセージ計算用の線形層（送信元ノード特徴を変換）
        self.msg_lin = nn.Linear(in_dim, out_dim)
        # 更新用の線形層（集約メッセージ＋自己ループを変換）
        self.update_lin = nn.Linear(in_dim + out_dim, out_dim)

    def forward(self, x, edge_index):
        """
        x: (num_nodes, in_dim)
        edge_index: (2, num_edges)
        """
        src, dst = edge_index  # src -> dst のエッジ

        # 1. メッセージ計算：各エッジについて送信元ノードの特徴を変換
        msg = self.msg_lin(x[src])  # (num_edges, out_dim)

        # 2. 集約：各ノードが受け取るメッセージを合計
        agg = torch.zeros(x.size(0), msg.size(1), device=x.device)
        agg = agg.index_add_(0, dst, msg)  # dstノードごとにmsgを加算

        # 3. 更新：自身の特徴と集約メッセージを結合して変換
        #    ここでは自己ループとして元の特徴 x も使う
        combined = torch.cat([x, agg], dim=-1)  # (num_nodes, in_dim + out_dim)
        new_x = self.update_lin(combined)

        return new_x

class SimpleGNN(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_layers=2):
        super().__init__()
        self.num_layers = num_layers

        # 入力層（最初のメッセージパッシング層）
        self.layers = nn.ModuleList()
        self.layers.append(SimpleMessagePassingLayer(input_dim, hidden_dim))

        # 中間層
        for _ in range(num_layers - 2):
            self.layers.append(SimpleMessagePassingLayer(hidden_dim, hidden_dim))

        # 出力層（最後のメッセージパッシング層）
        if num_layers > 1:
            self.layers.append(SimpleMessagePassingLayer(hidden_dim, output_dim))
        else:
            # num_layers == 1 の場合は input_dim -> output_dim
            self.layers.append(SimpleMessagePassingLayer(input_dim, output_dim))

    def forward(self, x, edge_index):
        h = x
        for layer in self.layers:
            h = layer(h, edge_index)
            # 非線形活性化（ReLUなど）を挟む
            h = F.relu(h)
        return h

# モデル定義
model = SimpleGNN(
    input_dim=2,   # xの特徴次元
    hidden_dim=16,
    output_dim=8, # 最終的なノード表現の次元
    num_layers=2
)

# フォワード計算
node_embeddings = model(x, edge_index)

print("入力特徴量 shape:", x.shape)           # (4, 2)
print("出力ノード埋め込み shape:", node_embeddings.shape)  # (4, 8)

class SimpleGNNWithReadout(nn.Module):
    def __init__(self, input_dim, hidden_dim, node_out_dim, graph_out_dim):
        super().__init__()
        # ノード表現を学習するGNN
        self.gnn = SimpleGNN(input_dim, hidden_dim, node_out_dim, num_layers=2)
        # グラフ読み出し用MLP（全ノードを集約してグラフ表現に変換）
        self.readout_mlp = nn.Sequential(
            nn.Linear(node_out_dim, graph_out_dim),
            nn.ReLU()
        )

    def forward(self, x, edge_index, batch=None):
        """
        x: (num_nodes, input_dim)
        edge_index: (2, num_edges)
        batch: 各ノードが属するグラフID（単一グラフの場合はNoneでOK）
        """
        # 1. ノード表現をGNNで更新
        node_emb = self.gnn(x, edge_index)  # (num_nodes, node_out_dim)

        # 2. グラフ読み出し（ここでは全ノードの平均を取る）
        if batch is None:
            # 単一グラフの場合：全ノード平均
            graph_emb = node_emb.mean(dim=0, keepdim=True)  # (1, node_out_dim)
        else:
            # 複数グラフが1つのバッチにまとまっている場合：グラフごとに平均
            # ここでは簡略化のため省略（実際は scatter_mean などを使う）
            raise NotImplementedError("batch処理は省略しています")

        # 3. グラフ表現をMLPで変換
        graph_out = self.readout_mlp(graph_emb)  # (1, graph_out_dim)

        return graph_out

!pip install torchviz

from torchviz import make_dot

# モデルとダミー入力
model = SimpleGNN(input_dim=2, hidden_dim=16, output_dim=8, num_layers=2)
x_dummy = torch.randn(4, 2)  # ノード数4, 特徴次元2
edge_index_dummy = torch.tensor([[0,1,2,3],[1,2,3,0]], dtype=torch.long)

# 一度フォワード計算してグラフを取得
out = model(x_dummy, edge_index_dummy)

# 計算グラフを可視化（出力ノードとパラメータを表示）
dot = make_dot(out, params=dict(model.named_parameters()))
dot.render("gnn_architecture", format="png")  # gnn_architecture.png が生成される

import re
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# 1. ログデータの流し込み
# ---------------------------------------------------------
# 提供されたログをそのままトリプルクォーテーション内に貼り付けています
log_data = """
Episode 0: Reward = -126.81, Captures = 0, Avg Reward = -126.81, Avg Captures = 0.00
Actor Loss: -0.0154 | Critic Loss: 0.1027 | Avg Entropy: 1.6085
Episode 1: Reward = -96.68, Captures = 0, Avg Reward = -111.75, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.1005 | Avg Entropy: 1.6085
Episode 2: Reward = -125.40, Captures = 0, Avg Reward = -116.30, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0900 | Avg Entropy: 1.6085
Episode 3: Reward = -158.32, Captures = 0, Avg Reward = -126.80, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.1070 | Avg Entropy: 1.6085
Episode 4: Reward = -95.05, Captures = 0, Avg Reward = -120.45, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.1072 | Avg Entropy: 1.6086
Episode 5: Reward = -142.06, Captures = 0, Avg Reward = -124.05, Avg Captures = 0.00
Actor Loss: -0.0152 | Critic Loss: 0.0926 | Avg Entropy: 1.6085
Episode 6: Reward = -140.07, Captures = 0, Avg Reward = -126.34, Avg Captures = 0.00
Actor Loss: -0.0163 | Critic Loss: 0.0854 | Avg Entropy: 1.6086
Episode 7: Reward = -121.78, Captures = 0, Avg Reward = -125.77, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0947 | Avg Entropy: 1.6086
Episode 8: Reward = -149.45, Captures = 0, Avg Reward = -128.40, Avg Captures = 0.00
Actor Loss: -0.0142 | Critic Loss: 0.0880 | Avg Entropy: 1.6086
Episode 9: Reward = -116.19, Captures = 0, Avg Reward = -127.18, Avg Captures = 0.00
Actor Loss: -0.0142 | Critic Loss: 0.0961 | Avg Entropy: 1.6086
Episode 10: Reward = -148.00, Captures = 0, Avg Reward = -129.07, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.0856 | Avg Entropy: 1.6086
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 11: Reward = -133.20, Captures = 0, Avg Reward = -129.42, Avg Captures = 0.00
Actor Loss: -0.0155 | Critic Loss: 0.0845 | Avg Entropy: 1.6086
Episode 12: Reward = -133.22, Captures = 0, Avg Reward = -129.71, Avg Captures = 0.00
Actor Loss: -0.0152 | Critic Loss: 0.0966 | Avg Entropy: 1.6086
Episode 13: Reward = -72.73, Captures = 0, Avg Reward = -125.64, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.0961 | Avg Entropy: 1.6086
Episode 14: Reward = -139.48, Captures = 0, Avg Reward = -126.56, Avg Captures = 0.00
Actor Loss: -0.0142 | Critic Loss: 0.0665 | Avg Entropy: 1.6086
Episode 15: Reward = -143.87, Captures = 0, Avg Reward = -127.64, Avg Captures = 0.00
Actor Loss: -0.0168 | Critic Loss: 0.0616 | Avg Entropy: 1.6086
Episode 16: Reward = -116.86, Captures = 0, Avg Reward = -127.01, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0652 | Avg Entropy: 1.6086
Episode 17: Reward = -138.34, Captures = 0, Avg Reward = -127.64, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.0519 | Avg Entropy: 1.6086
Episode 18: Reward = -118.95, Captures = 0, Avg Reward = -127.18, Avg Captures = 0.00
Actor Loss: -0.0165 | Critic Loss: 0.0555 | Avg Entropy: 1.6086
Episode 19: Reward = -117.86, Captures = 0, Avg Reward = -126.72, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0448 | Avg Entropy: 1.6086
Episode 20: Reward = -148.68, Captures = 0, Avg Reward = -127.76, Avg Captures = 0.00
Actor Loss: -0.0160 | Critic Loss: 0.0433 | Avg Entropy: 1.6086
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 21: Reward = -111.50, Captures = 0, Avg Reward = -127.02, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.0430 | Avg Entropy: 1.6086
Episode 22: Reward = -141.88, Captures = 0, Avg Reward = -127.67, Avg Captures = 0.00
Actor Loss: -0.0159 | Critic Loss: 0.0384 | Avg Entropy: 1.6086
Episode 23: Reward = -141.98, Captures = 0, Avg Reward = -128.27, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0294 | Avg Entropy: 1.6086
Episode 24: Reward = -136.10, Captures = 0, Avg Reward = -128.58, Avg Captures = 0.00
Actor Loss: -0.0160 | Critic Loss: 0.0316 | Avg Entropy: 1.6086
Episode 25: Reward = -113.64, Captures = 0, Avg Reward = -128.00, Avg Captures = 0.00
Actor Loss: -0.0179 | Critic Loss: 0.0453 | Avg Entropy: 1.6086
Episode 26: Reward = -69.11, Captures = 0, Avg Reward = -125.82, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.0737 | Avg Entropy: 1.6086
Episode 27: Reward = -125.86, Captures = 0, Avg Reward = -125.82, Avg Captures = 0.00
Actor Loss: -0.0154 | Critic Loss: 0.0458 | Avg Entropy: 1.6086
Episode 28: Reward = -114.83, Captures = 0, Avg Reward = -125.45, Avg Captures = 0.00
Actor Loss: -0.0158 | Critic Loss: 0.0589 | Avg Entropy: 1.6085
Episode 29: Reward = -141.32, Captures = 0, Avg Reward = -125.97, Avg Captures = 0.00
Actor Loss: -0.0189 | Critic Loss: 0.0324 | Avg Entropy: 1.6085
Episode 30: Reward = -139.23, Captures = 0, Avg Reward = -126.40, Avg Captures = 0.00
Actor Loss: -0.0166 | Critic Loss: 0.0327 | Avg Entropy: 1.6085
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 31: Reward = -176.79, Captures = 0, Avg Reward = -127.98, Avg Captures = 0.00
Actor Loss: -0.0150 | Critic Loss: 0.0383 | Avg Entropy: 1.6084
Episode 32: Reward = -121.66, Captures = 0, Avg Reward = -127.79, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.0380 | Avg Entropy: 1.6084
Episode 33: Reward = -118.52, Captures = 0, Avg Reward = -127.51, Avg Captures = 0.00
Actor Loss: -0.0176 | Critic Loss: 0.0560 | Avg Entropy: 1.6083
Episode 34: Reward = -117.43, Captures = 0, Avg Reward = -127.23, Avg Captures = 0.00
Actor Loss: -0.0206 | Critic Loss: 0.0485 | Avg Entropy: 1.6083
Episode 35: Reward = -128.28, Captures = 0, Avg Reward = -127.25, Avg Captures = 0.00
Actor Loss: -0.0182 | Critic Loss: 0.0354 | Avg Entropy: 1.6082
Episode 36: Reward = -106.43, Captures = 0, Avg Reward = -126.69, Avg Captures = 0.00
Actor Loss: -0.0201 | Critic Loss: 0.0605 | Avg Entropy: 1.6080
Episode 37: Reward = -77.97, Captures = 0, Avg Reward = -125.41, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0656 | Avg Entropy: 1.6080
Episode 38: Reward = -139.04, Captures = 0, Avg Reward = -125.76, Avg Captures = 0.00
Actor Loss: -0.0175 | Critic Loss: 0.0356 | Avg Entropy: 1.6080
Episode 39: Reward = -115.49, Captures = 0, Avg Reward = -125.50, Avg Captures = 0.00
Actor Loss: -0.0201 | Critic Loss: 0.0476 | Avg Entropy: 1.6078
Episode 40: Reward = -109.83, Captures = 0, Avg Reward = -125.12, Avg Captures = 0.00
Actor Loss: -0.0164 | Critic Loss: 0.0586 | Avg Entropy: 1.6078
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 41: Reward = -118.95, Captures = 0, Avg Reward = -124.97, Avg Captures = 0.00
Actor Loss: -0.0183 | Critic Loss: 0.0338 | Avg Entropy: 1.6076
Episode 42: Reward = -71.75, Captures = 0, Avg Reward = -123.74, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.0718 | Avg Entropy: 1.6079
Episode 43: Reward = -149.73, Captures = 0, Avg Reward = -124.33, Avg Captures = 0.00
Actor Loss: -0.0191 | Critic Loss: 0.0313 | Avg Entropy: 1.6079
Episode 44: Reward = -141.59, Captures = 0, Avg Reward = -124.71, Avg Captures = 0.00
Actor Loss: -0.0157 | Critic Loss: 0.0321 | Avg Entropy: 1.6080
Episode 45: Reward = -137.33, Captures = 0, Avg Reward = -124.98, Avg Captures = 0.00
Actor Loss: -0.0177 | Critic Loss: 0.0346 | Avg Entropy: 1.6080
Episode 46: Reward = -136.45, Captures = 0, Avg Reward = -125.23, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.0393 | Avg Entropy: 1.6081
Episode 47: Reward = -136.99, Captures = 0, Avg Reward = -125.47, Avg Captures = 0.00
Actor Loss: -0.0190 | Critic Loss: 0.0306 | Avg Entropy: 1.6080
Episode 48: Reward = -143.60, Captures = 0, Avg Reward = -125.84, Avg Captures = 0.00
Actor Loss: -0.0173 | Critic Loss: 0.0284 | Avg Entropy: 1.6079
Episode 49: Reward = -121.92, Captures = 0, Avg Reward = -125.76, Avg Captures = 0.00
Actor Loss: -0.0170 | Critic Loss: 0.0450 | Avg Entropy: 1.6080
Episode 50: Reward = -111.40, Captures = 0, Avg Reward = -125.48, Avg Captures = 0.00
Actor Loss: -0.0196 | Critic Loss: 0.0332 | Avg Entropy: 1.6079

reward evaluate team play

Episode 10: Reward = 372.71, Captures = 0, Avg Reward = 372.71, Avg Captures = 0.00
Actor Loss: -0.0156 | Critic Loss: 0.2885 | Avg Entropy: 1.6090
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 11: Reward = 433.66, Captures = 0, Avg Reward = 403.19, Avg Captures = 0.00
Actor Loss: -0.0162 | Critic Loss: 0.4005 | Avg Entropy: 1.6090
Episode 12: Reward = 388.98, Captures = 0, Avg Reward = 398.45, Avg Captures = 0.00
Actor Loss: -0.0150 | Critic Loss: 0.2632 | Avg Entropy: 1.6090
Episode 13: Reward = 421.15, Captures = 0, Avg Reward = 404.13, Avg Captures = 0.00
Actor Loss: -0.0150 | Critic Loss: 0.3387 | Avg Entropy: 1.6090
Episode 14: Reward = 407.61, Captures = 0, Avg Reward = 404.82, Avg Captures = 0.00
Actor Loss: -0.0161 | Critic Loss: 0.2681 | Avg Entropy: 1.6090
Episode 15: Reward = 459.86, Captures = 0, Avg Reward = 413.99, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.3423 | Avg Entropy: 1.6090
Episode 16: Reward = 419.74, Captures = 0, Avg Reward = 414.82, Avg Captures = 0.00
Actor Loss: -0.0164 | Critic Loss: 0.2845 | Avg Entropy: 1.6090
Episode 17: Reward = 452.44, Captures = 0, Avg Reward = 419.52, Avg Captures = 0.00
Actor Loss: -0.0169 | Critic Loss: 0.3028 | Avg Entropy: 1.6090
Episode 18: Reward = 401.61, Captures = 0, Avg Reward = 417.53, Avg Captures = 0.00
Actor Loss: -0.0171 | Critic Loss: 0.2398 | Avg Entropy: 1.6090
Episode 19: Reward = 444.40, Captures = 0, Avg Reward = 420.22, Avg Captures = 0.00
Actor Loss: -0.0160 | Critic Loss: 0.2387 | Avg Entropy: 1.6090
Episode 20: Reward = 397.86, Captures = 0, Avg Reward = 418.18, Avg Captures = 0.00
Actor Loss: -0.0172 | Critic Loss: 0.1992 | Avg Entropy: 1.6090
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 21: Reward = 409.27, Captures = 0, Avg Reward = 417.44, Avg Captures = 0.00
Actor Loss: -0.0176 | Critic Loss: 0.1969 | Avg Entropy: 1.6089
Episode 22: Reward = 420.36, Captures = 0, Avg Reward = 417.67, Avg Captures = 0.00
Actor Loss: -0.0167 | Critic Loss: 0.2046 | Avg Entropy: 1.6089
Episode 23: Reward = 403.41, Captures = 0, Avg Reward = 416.65, Avg Captures = 0.00
Actor Loss: -0.0174 | Critic Loss: 0.1649 | Avg Entropy: 1.6089
Episode 24: Reward = 412.87, Captures = 0, Avg Reward = 416.40, Avg Captures = 0.00
Actor Loss: -0.0193 | Critic Loss: 0.1705 | Avg Entropy: 1.6088
Episode 25: Reward = 394.27, Captures = 0, Avg Reward = 415.01, Avg Captures = 0.00
Actor Loss: -0.0204 | Critic Loss: 0.1373 | Avg Entropy: 1.6087
Episode 26: Reward = 420.40, Captures = 0, Avg Reward = 415.33, Avg Captures = 0.00
Actor Loss: -0.0192 | Critic Loss: 0.1375 | Avg Entropy: 1.6086
Episode 27: Reward = 383.56, Captures = 0, Avg Reward = 413.56, Avg Captures = 0.00
Actor Loss: -0.0212 | Critic Loss: 0.1177 | Avg Entropy: 1.6085
Episode 28: Reward = 472.43, Captures = 0, Avg Reward = 416.66, Avg Captures = 0.00
Actor Loss: -0.0235 | Critic Loss: 0.1513 | Avg Entropy: 1.6084
Episode 29: Reward = 385.57, Captures = 0, Avg Reward = 415.11, Avg Captures = 0.00
Actor Loss: -0.0247 | Critic Loss: 0.1289 | Avg Entropy: 1.6081
Episode 30: Reward = 488.29, Captures = 0, Avg Reward = 418.59, Avg Captures = 0.00
Actor Loss: -0.0199 | Critic Loss: 0.1280 | Avg Entropy: 1.6080
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 31: Reward = 554.19, Captures = 0, Avg Reward = 424.76, Avg Captures = 0.00
Actor Loss: -0.0224 | Critic Loss: 0.2417 | Avg Entropy: 1.6075
Episode 32: Reward = 415.82, Captures = 0, Avg Reward = 424.37, Avg Captures = 0.00
Actor Loss: -0.0243 | Critic Loss: 0.1457 | Avg Entropy: 1.6071
Episode 33: Reward = 437.09, Captures = 0, Avg Reward = 424.90, Avg Captures = 0.00
Actor Loss: -0.0230 | Critic Loss: 0.1556 | Avg Entropy: 1.6070
Episode 34: Reward = 400.89, Captures = 0, Avg Reward = 423.94, Avg Captures = 0.00
Actor Loss: -0.0267 | Critic Loss: 0.1740 | Avg Entropy: 1.6066
Episode 35: Reward = 401.85, Captures = 0, Avg Reward = 423.09, Avg Captures = 0.00
Actor Loss: -0.0268 | Critic Loss: 0.1140 | Avg Entropy: 1.6067
Episode 36: Reward = 372.28, Captures = 0, Avg Reward = 421.21, Avg Captures = 0.00
Actor Loss: -0.0218 | Critic Loss: 0.1351 | Avg Entropy: 1.6065
Episode 37: Reward = 463.51, Captures = 0, Avg Reward = 422.72, Avg Captures = 0.00
Actor Loss: -0.0202 | Critic Loss: 0.1646 | Avg Entropy: 1.6062
Episode 38: Reward = 450.87, Captures = 0, Avg Reward = 423.69, Avg Captures = 0.00
Actor Loss: -0.0246 | Critic Loss: 0.1203 | Avg Entropy: 1.6067
Episode 39: Reward = 567.83, Captures = 0, Avg Reward = 428.49, Avg Captures = 0.00
Actor Loss: -0.0260 | Critic Loss: 0.2477 | Avg Entropy: 1.6066
Episode 40: Reward = 417.55, Captures = 0, Avg Reward = 428.14, Avg Captures = 0.00
Actor Loss: -0.0234 | Critic Loss: 0.1536 | Avg Entropy: 1.6067
Checkpoint saved: /content/drive/MyDrive/rl_pursuit/mappo_episode.pth
Episode 41: Reward = 364.30, Captures = 0, Avg Reward = 426.15, Avg Captures = 0.00
Actor Loss: -0.0290 | Critic Loss: 0.1175 | Avg Entropy: 1.6069
Episode 42: Reward = 658.34, Captures = 0, Avg Reward = 433.18, Avg Captures = 0.00
Actor Loss: -0.0238 | Critic Loss: 0.3344 | Avg Entropy: 1.6068
Episode 43: Reward = 519.16, Pooling = 0, Avg Reward = 435.71, Avg Captures = 0.00
Actor Loss: -0.0285 | Critic Loss: 0.1981 | Avg Entropy: 1.6069
Episode 44: Reward = 459.94, Captures = 0, Avg Reward = 436.40, Avg Captures = 0.00
Actor Loss: -0.0226 | Critic Loss: 0.1403 | Avg Entropy: 1.6072
Episode 45: Reward = 610.95, Captures = 0, Avg Reward = 441.25, Avg Captures = 0.00
Actor Loss: -0.0280 | Critic Loss: 0.2423 | Avg Entropy: 1.6069
Episode 46: Reward = 486.87, Captures = 0, Avg Reward = 442.48, Avg Captures = 0.00
Actor Loss: -0.0298 | Critic Loss: 0.1489 | Avg Entropy: 1.6075
Episode 47: Reward = 386.94, Captures = 0, Avg Reward = 441.02, Avg Captures = 0.00
Actor Loss: -0.0254 | Critic Loss: 0.1293 | Avg Entropy: 1.6072
Episode 48: Reward = 561.70, Captures = 0, Avg Reward = 444.12, Avg Captures = 0.00
Actor Loss: -0.0272 | Critic Loss: 0.2120 | Avg Entropy: 1.6068
Episode 49: Reward = 619.12, Captures = 0, Avg Reward = 448.49, Avg Captures = 0.00
Actor Loss: -0.0297 | Critic Loss: 0.2478 | Avg Entropy: 1.6073
Episode 50: Reward = 431.19, Captures = 0, Avg Reward = 448.07, Avg Captures = 0.00
Actor Loss: -0.0308 | Critic Loss: 0.1478 | Avg Entropy: 1.6073
"""

# ---------------------------------------------------------
# 2. 正規表現を用いたデータの抽出
# ---------------------------------------------------------
# 各フェーズ（Gelu変更後、Team Play評価）に分けてデータを保持
phases = {"Gelu_Only": {}, "Team_Play": {}}
current_phase = "Gelu_Only"

# 正規表現パターン
ep_pattern = re.compile(r"Episode\s+(\d+):\s+Reward\s+=\s+([-\d.]+),\s+Captures.*Avg\s+Reward\s+=\s+([-\d.]+)")
loss_pattern = re.compile(r"Actor\s+Loss:\s+([-\d.]+)\s+\|\s+Critic\s+Loss:\s+([-\d.]+)\s+\|\s+Avg\s+Entropy:\s+([-\d.]+)")

lines = log_data.strip().split('\n')
for line in lines:
    if "reward evaluate team play" in line:
        current_phase = "Team_Play"
        continue

    ep_match = ep_pattern.search(line)
    if ep_match:
        ep = int(ep_match.group(1))
        rew = float(ep_match.group(2))
        avg_rew = float(ep_match.group(3))

        if ep not in phases[current_phase]:
            phases[current_phase][ep] = {}
        phases[current_phase][ep]['reward'] = rew
        phases[current_phase][ep]['avg_reward'] = avg_rew

    loss_match = loss_pattern.search(line)
    if loss_match:
        # 直前のEpisodeマッチと紐付けるため、現在のフェーズの最大（最新）のepを取得
        if phases[current_phase]:
            ep = max(phases[current_phase].keys())
            phases[current_phase][ep]['actor_loss'] = float(loss_match.group(1))
            phases[current_phase][ep]['critic_loss'] = float(loss_match.group(2))
            phases[current_phase][ep]['entropy'] = float(loss_match.group(3))

# ---------------------------------------------------------
# 3. グラフ描画用のリスト作成
# ---------------------------------------------------------
def dict_to_lists(d):
    # エピソード順にソートしてリスト化
    sorted_eps = sorted([k for k, v in d.items() if 'actor_loss' in v]) # 完全にデータが揃っているもの
    return {
        'ep': sorted_eps,
        'reward': [d[e]['reward'] for e in sorted_eps],
        'avg_reward': [d[e]['avg_reward'] for e in sorted_eps],
        'actor_loss': [d[e]['actor_loss'] for e in sorted_eps],
        'critic_loss': [d[e]['critic_loss'] for e in sorted_eps],
        'entropy': [d[e]['entropy'] for e in sorted_eps],
    }

gelu_data = dict_to_lists(phases["Gelu_Only"])
team_data = dict_to_lists(phases["Team_Play"])

# ---------------------------------------------------------
# 4. Matplotlibによる可視化
# ---------------------------------------------------------
fig, axs = plt.subplots(3, 2, figsize=(14, 12), sharex='col')
fig.suptitle('Training Metrics Comparison: Gelu Only vs Team Play', fontsize=16, fontweight='bold')

# --- 左列: Gelu Only フェーズ ---
# Reward
axs[0, 0].plot(gelu_data['ep'], gelu_data['reward'], label='Reward', color='lightblue', alpha=0.6, linestyle='--')
axs[0, 0].plot(gelu_data['ep'], gelu_data['avg_reward'], label='Avg Reward', color='blue', linewidth=2)
axs[0, 0].set_title('Hybrid Reward: Reward')
axs[0, 0].grid(True, linestyle=':')
axs[0, 0].legend()

# Losses
axs[1, 0].plot(gelu_data['ep'], gelu_data['actor_loss'], label='Actor Loss', color='darkorange')
axs[1, 0].plot(gelu_data['ep'], gelu_data['critic_loss'], label='Critic Loss', color='red')
axs[1, 0].set_title('Hybrid Reward: Loss')
axs[1, 0].grid(True, linestyle=':')
axs[1, 0].legend()

# Entropy
axs[2, 0].plot(gelu_data['ep'], gelu_data['entropy'], color='purple', marker='o', markersize=3)
axs[2, 0].set_title('Hybrid Reward: Avg Entropy')
axs[2, 0].set_xlabel('Episode')
axs[2, 0].grid(True, linestyle=':')


# --- 右列: Team Play フェーズ ---
# Reward
axs[0, 1].plot(team_data['ep'], team_data['reward'], label='Reward', color='lightgreen', alpha=0.6, linestyle='--')
axs[0, 1].plot(team_data['ep'], team_data['avg_reward'], label='Avg Reward', color='green', linewidth=2)
axs[0, 1].set_title('Team Play: Reward')
axs[0, 1].grid(True, linestyle=':')
axs[0, 1].legend()

# Losses
axs[1, 1].plot(team_data['ep'], team_data['actor_loss'], label='Actor Loss', color='darkorange')
axs[1, 1].plot(team_data['ep'], team_data['critic_loss'], label='Critic Loss', color='red')
axs[1, 1].set_title('Team Play: Loss')
axs[1, 1].grid(True, linestyle=':')
axs[1, 1].legend()

# Entropy
axs[2, 1].plot(team_data['ep'], team_data['entropy'], color='purple', marker='o', markersize=3)
axs[2, 1].set_title('Team Play: Avg Entropy')
axs[2, 1].set_xlabel('Episode')
axs[2, 1].grid(True, linestyle=':')

plt.tight_layout()
plt.show()

