# -*- coding: utf-8 -*-
"""how_to_use_tensorboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17x0p0iFdMRQ61bQFZFSrhGlLLktKohi8

TensorBoardはもともとTensorFlowのツールですが、PyTorchでもそのまま利用可能です。
"""

!pip install tensorboard

"""PyTorchの SummaryWriter というクラスを使用して、データを記録（ログ）していきます。"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.tensorboard import SummaryWriter  # 1. ライブラリのインポート

# ログを保存するディレクトリを指定してインスタンス作成
# 名前を変えることで、複数の実験（学習率違いなど）を比較できます
writer = SummaryWriter('runs/linear_regression_v1')

# ダミーのモデルとデータ
model = nn.Linear(1, 1)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)

# 学習ループ
for epoch in range(100):
    inputs = torch.randn(10, 1)
    targets = inputs * 2.0 + 0.5

    # Forward / Backward
    outputs = model(inputs)
    loss = criterion(outputs, targets)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # 2. スカラー値（損失など）を記録
    writer.add_scalar('Loss/train', loss.item(), epoch)

    # 3. 重みの分布を記録（ヒストグラム）
    writer.add_histogram('Weights', model.weight, epoch)

# 4. 書き込みを終了
writer.close()

"""ログが書き出されたら、ターミナル（コマンドプロンプト）で以下のコマンドを実行します。

Colabの場合はターミナルが使えないため、ノートブック内で以下のマジックコマンドを使います。

TensorBoardの**「Histograms（ヒストグラム）」**や**「Distributions（分布）」**タブで重みの動きを見ることは、モデルが「正しく学習できているか」を判断する非常に高度なデバッグ手法です。

重みの分布を見る際のポイントを3つのケースに分けて解説します。

---

### 1. 理想的な分布：徐々に変化している

学習がうまくいっている場合、重みのヒストグラムは**「時間の経過とともに少しずつ形を変えたり、横に広がったり」**します。

* **初期状態**: 通常、Xavier初期化やHe初期化などにより、0を中心としたきれいな正規分布（釣鐘型）から始まります。
* **学習中**: モデルが特徴を捉えるにつれ、特定の重みが大きく（または小さく）なり、分布がなだらかに変化します。

---

### 2. 要注意なサイン：分布が「全く動かない」

学習が進んでいるはずなのに、エポックを重ねてもヒストグラムの形が初期状態から全く変わらない場合があります。

* **原因**: **勾配消失（Vanishing Gradient）**が起きている可能性が高いです。
* **チェック点**: その層に勾配が届いておらず、重みが更新されていません。学習率が低すぎるか、活性化関数（Sigmoidなど）による飽和が起きているかもしれません。

---

### 3. 要注意なサイン：分布が「極端に広がる / 爆発する」

分布が左右に激しく広がり、値が非常に大きくなっている場合です。

* **原因**: **勾配爆発（Exploding Gradient）**が起きています。
* **チェック点**: 学習率が高すぎるか、Batch NormalizationやRMSNormなどの正規化が不足している可能性があります。そのまま放置すると、最終的に数値が `NaN`（非数）になり、学習が崩壊します。

---

### 4. 活性化関数の「死」を見つける

ReLUを使っている場合、分布が **0付近に極端に集中し、プラス側に全く広がらない** 状態になることがあります。

* **死んだReLU (Dead ReLU)**: ニューロンの入力が常にマイナスになり、一度も発火しなくなった状態です。そのニューロンは二度と学習に貢献しません。
* **対策**: 学習率を下げるか、Leaky ReLUなどの代替関数を検討するサインになります。

---

### 実装でのコツ：何を記録すべきか？

全ての層を記録するとログファイルが巨大になるため、まずは**「最初の方の層」と「最後の方の層」**を記録するのが効率的です。

```python
for name, param in model.named_parameters():
    # 重み(weight)の分布を記録。勾配(grad)も記録するとさらに詳細に分析可能
    writer.add_histogram(f'Weights/{name}', param, epoch)
    if param.grad is not None:
        writer.add_histogram(f'Gradients/{name}', param.grad, epoch)

```

### まとめ：重みの分布チェックリスト

| 現象 | 推測される状況 | 対策 |
| --- | --- | --- |
| **形が変わらない** | 勾配消失 / 学習が起きていない | 学習率を上げる、初期化法を見直す |
| **左右に激しく広がる** | 勾配爆発 | 学習率を下げる、勾配クリッピングを導入 |
| **0に一直線に固まる** | ニューロンの死滅 | 活性化関数をLeaky ReLU等に変更 |
| **なだらかに形が変わる** | **正常な学習** | 継続 |

**次は、これらの異常を自動で検知するために、重みの「ノルム（大きさの合計）」をスカラー値としてグラフ化して監視する方法について解説しましょうか？**
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs

