# -*- coding: utf-8 -*-
"""batch_normalization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCgruVB2uBISlQqTZletsT8jwFeryhUo
"""

import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons
from torch.utils.data import DataLoader, TensorDataset

# --- データ作成（わざと難しい“半月型”） ---
X, y = make_moons(n_samples=5000, noise=0.2)
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=64, shuffle=True)

# --- モデル定義（BNあり / BNなし） ---
class MLP(nn.Module):
    def __init__(self, use_bn=False):
        super().__init__()
        layers = []
        layers += [nn.Linear(2, 64)]
        if use_bn:
            layers += [nn.BatchNorm1d(64)]
        layers += [nn.ReLU()]

        layers += [nn.Linear(64, 64)]
        if use_bn:
            layers += [nn.BatchNorm1d(64)]
        layers += [nn.ReLU()]

        layers += [nn.Linear(64, 2)]
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)

# --- 2つのモデル ---
model_no_bn = MLP(use_bn=False)
model_bn    = MLP(use_bn=True)

opt1 = optim.Adam(model_no_bn.parameters(), lr=0.00002)
opt2 = optim.Adam(model_bn.parameters(), lr=0.00002)

criterion = nn.CrossEntropyLoss()

# --- 学習 ---
epochs = 50
loss_no_bn_list = []
loss_bn_list = []

for epoch in range(epochs):
    total_no_bn = 0
    total_bn    = 0

    for batch_x, batch_y in loader:
        # --- BNなしモデル ---
        opt1.zero_grad()
        preds1 = model_no_bn(batch_x)
        loss1 = criterion(preds1, batch_y)
        loss1.backward()
        opt1.step()
        total_no_bn += loss1.item()

        # --- BNありモデル ---
        opt2.zero_grad()
        preds2 = model_bn(batch_x)
        loss2 = criterion(preds2, batch_y)
        loss2.backward()
        opt2.step()
        total_bn += loss2.item()

    loss_no_bn_list.append(total_no_bn / len(loader))
    loss_bn_list.append(total_bn / len(loader))

    print(f"Epoch {epoch+1}/{epochs} | No BN Loss: {loss_no_bn_list[-1]:.4f}, BN Loss: {loss_bn_list[-1]:.4f}")

# --- Loss可視化 ---
plt.figure(figsize=(8,5))
plt.plot(loss_no_bn_list, label="No BatchNorm")
plt.plot(loss_bn_list, label="With BatchNorm")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Effect of Batch Normalization (Loss Comparison)")
plt.legend()
plt.show()

# --- 決定境界の可視化 ---
import numpy as np

def plot_decision_boundary(model, title):
    x_min, x_max = X[:,0].min() - .5, X[:,0].max() + .5
    y_min, y_max = X[:,1].min() - .5, X[:,1].max() + .5
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                         np.linspace(y_min, y_max, 200))
    grid = torch.tensor(np.c_[xx.ravel(), yy.ravel()], dtype=torch.float32)
    Z = model(grid).argmax(dim=1).reshape(xx.shape)

    plt.figure(figsize=(6,5))
    plt.contourf(xx, yy, Z, alpha=0.4)
    plt.scatter(X[:,0], X[:,1], c=y, s=10)
    plt.title(title)
    plt.show()

plot_decision_boundary(model_no_bn, "boundary decision(No BatchNorm)")
plot_decision_boundary(model_bn, "boundary decision(With BatchNorm)")

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt

# ----------------------
# MLP モデル（BNあり / なし）
# ----------------------
class MLP(nn.Module):
    def __init__(self, use_bn=False):
        super().__init__()
        layers = []

        layers += [nn.Linear(2, 64)]
        if use_bn:
            layers += [nn.BatchNorm1d(64)]
        layers += [nn.ReLU()]

        layers += [nn.Linear(64, 64)]
        if use_bn:
            layers += [nn.BatchNorm1d(64)]
        layers += [nn.ReLU()]

        layers += [nn.Linear(64, 2)]

        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


# ----------------------
# データ生成（例：2クラスのmoon）
# ----------------------
from sklearn.datasets import make_moons
from sklearn.preprocessing import StandardScaler

X, y = make_moons(n_samples=5000, noise=0.15)

# ★ データ標準化（必須）
scaler = StandardScaler()
X = scaler.fit_transform(X)

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

dataset = TensorDataset(X, y)
loader = DataLoader(dataset, batch_size=64, shuffle=True)


# ----------------------
# 学習関数
# ----------------------
def train(model, title):
    model.train()
    opt = optim.Adam(model.parameters(), lr=5e-5)
    criterion = nn.CrossEntropyLoss()

    losses = []

    for epoch in range(50):
        total_loss = 0
        for batch_x, batch_y in loader:
            opt.zero_grad()
            out = model(batch_x)
            loss = criterion(out, batch_y)
            loss.backward()
            opt.step()
            total_loss += loss.item()

        losses.append(total_loss / len(loader))

    # 学習曲線を表示
    plt.plot(losses, label=title)


# ----------------------
# 学習
# ----------------------
model_no_bn = MLP(use_bn=False)
model_bn    = MLP(use_bn=True)

train(model_no_bn, "No BatchNorm")
train(model_bn, "With BatchNorm")

plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("BatchNorm の有無による学習曲線の比較")
plt.show()

