# -*- coding: utf-8 -*-
"""SAM_trial_v.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pAgBgO9udpI7s6OsMZ_XGAY-jmAmW9Wb
"""

# Commented out IPython magic to ensure Python compatibility.
# 1. リポジトリのクローン
!git clone https://github.com/YiyuanLinXX/SAM-CLIP.git
# %cd SAM-CLIP

# 2. 必要なライブラリのインストール
!pip install -q git+https://github.com/facebookresearch/segment-anything.git
!pip install -q ftfy regex tqdm
!pip install -q git+https://github.com/openai/CLIP.git

# 入力用・出力用フォルダの作成
!mkdir -p input_images output_masks

!wget -q -O input_images/test_image.jpg "https://raw.githubusercontent.com/facebookresearch/segment-anything/main/notebooks/images/dog.jpg"
!mkdir -p ckpt

!wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth
!mv sam_vit_b_01ec64.pth ckpt/checkpoint_best.pth

!pip install asttokens executing icecream monai nptyping pynrrd SimpleITK slicerio torchio
!pip install tensorboardX

# データセット用フォルダの作成
!mkdir -p datasets/coco/images
!mkdir -p datasets/coco/annotations

# COCO val2017 画像とアノテーションのダウンロード
!wget http://images.cocodataset.org/zips/val2017.zip
!unzip -q val2017.zip -d datasets/coco/images/
!rm val2017.zip

!wget http://images.cocodataset.org/annotations/annotations_trainval2017.zip
!unzip -q annotations_trainval2017.zip -d datasets/coco/
!rm annotations_trainval2017.zip

import os
import json
import urllib.request
import numpy as np
from PIL import Image
from pycocotools.coco import COCO

base_dir = "mini_dataset_v2"
img_dir = os.path.join(base_dir, "images")
mask_dir = os.path.join(base_dir, "masks")
os.makedirs(img_dir, exist_ok=True)
os.makedirs(mask_dir, exist_ok=True)

# 1. COCO val2017 アノテーションの取得
ann_file = "annotations/instances_val2017.json"
if not os.path.exists(ann_file):
    print("アノテーションファイルをダウンロード中...")
    ann_url = "http://images.cocodataset.org/annotations/annotations_trainval2017.zip"
    urllib.request.urlretrieve(ann_url, "annotations.zip")
    os.system("unzip -q annotations.zip -d .")
    os.remove("annotations.zip")

coco = COCO(ann_file)
img_ids = coco.getImgIds()[:200]
images = coco.loadImgs(img_ids)

train_lines = []
val_lines = []

base_img_url = "http://images.cocodataset.org/val2017/"

print("画像とマスクを生成中...")
for idx, img_info in enumerate(images):
    file_name = img_info["file_name"]
    name_without_ext = os.path.splitext(file_name)[0]
    mask_file_name = f"{name_without_ext}.png"

    # 画像ダウンロード
    img_save_path = os.path.join(img_dir, file_name)
    if not os.path.exists(img_save_path):
        urllib.request.urlretrieve(base_img_url + file_name, img_save_path)

    # マスク画像の生成 (PNG)
    ann_ids = coco.getAnnIds(imgIds=img_info["id"])
    anns = coco.loadAnns(ann_ids)

    mask = np.zeros((img_info["height"], img_info["width"]), dtype=np.uint8)
    for ann in anns:
        mask = np.maximum(mask, coco.annToMask(ann))

    mask_save_path = os.path.join(mask_dir, mask_file_name)
    Image.fromarray((mask * 255).astype(np.uint8)).save(mask_save_path)

    # リスト形式: ファイル名のみ (画像ファイル名,マスクファイル名)
    line_entry = f"{file_name},{mask_file_name}"

    if idx < 40:
        train_lines.append(line_entry)
    else:
        val_lines.append(line_entry)

# テキストファイルの保存
train_list_path = os.path.join(base_dir, "train.txt")
val_list_path = os.path.join(base_dir, "val.txt")

with open(train_list_path, "w") as f:
    f.write("\n".join(train_lines))

with open(val_list_path, "w") as f:
    f.write("\n".join(val_lines))

print("\nリストファイルをファイル名のみの形式に更新しました！")

!python train.py \
    -sam_ckpt sam_vit_b_01ec64.pth \
    -dir_checkpoint ckpt \
    -img_folder mini_dataset_v2/images \
    -mask_folder mini_dataset_v2/masks \
    -train_img_list mini_dataset_v2/train.txt \
    -val_img_list mini_dataset_v2/val.txt \
    -text_prompt "dog" \
    -epochs 5 \
    -lr 0.0001 \
    -num_cls 3 \
    -gpu True \
    -gpu_device 0

!python /content/SAM-CLIP/inference_sam_clip.py \
    -val_list mini_dataset_v2/val.txt \
    -img_folder mini_dataset_v2/images \
    -mask_folder mini_dataset_v2/masks \
    -output_dir eval_results \
    -text_prompt "dog"

import os
import argparse
import torch
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# 評価指標計算関数
def calculate_metrics(pred_mask, gt_mask):
    """
    pred_mask, gt_mask: 共に 2D numpy array (bool or uint8 0/1)
    """
    pred = (pred_mask > 0.5)
    gt = (gt_mask > 0.5)

    intersection = np.logical_and(pred, gt).sum()
    union = np.logical_or(pred, gt).sum()
    pred_sum = pred.sum()
    gt_sum = gt.sum()

    # Zero division 回避
    iou = intersection / union if union > 0 else 1.0 if pred_sum == 0 and gt_sum == 0 else 0.0
    precision = intersection / pred_sum if pred_sum > 0 else 1.0 if gt_sum == 0 else 0.0
    recall = intersection / gt_sum if gt_sum > 0 else 1.0 if pred_sum == 0 else 0.0

    return iou, precision, recall

def run_evaluation(val_list_path, img_dir, mask_dir, output_dir, text_prompt):
    os.makedirs(output_dir, exist_ok=True)

    # 1. 検証用リストのロード
    with open(val_list_path, 'r') as f:
        lines = [line.strip() for line in f if line.strip()]

    print(f"評価を開始します (対象画像数: {len(lines)} 枚, プロンプト: '{text_prompt}')")

    total_iou, total_precision, total_recall = 0.0, 0.0, 0.0

    plt.ioff() # 描画ウィンドウ非表示

    for idx, line in enumerate(lines):
        img_name, mask_name = line.split(',')
        img_path = os.path.join(img_dir, img_name)
        mask_path = os.path.join(mask_dir, mask_name)

        # 画像・マスクの読み込み
        orig_img = Image.open(img_path).convert('RGB')
        gt_mask = Image.open(mask_path).convert('L')
        gt_arr = (np.array(gt_mask) > 128).astype(np.uint8)

        # -------------------------------------------------------------
        # ※ 実際の実装ではここでモデルの forward(img, text_prompt) を行います。
        # ポック検証用ダミー処理（モデルからの予測マスク取得イメージ）
        # 実際には model.predict(orig_img, text_prompt) 等で得られた出力マスクを使用します。
        pred_arr = gt_arr.copy() # パイプライン確認用
        # -------------------------------------------------------------

        # 指標計算
        iou, prec, rec = calculate_metrics(pred_arr, gt_arr)
        total_iou += iou
        total_precision += prec
        total_recall += rec

        # 2. 定性評価用画像の可視化・保存
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))

        # 元画像
        axes[0].imshow(orig_img)
        axes[0].set_title(f"Original Image ({img_name})")
        axes[0].axis('off')

        # Ground Truth (正解マスク)
        axes[1].imshow(gt_arr, cmap='gray')
        axes[1].set_title("Ground Truth Mask")
        axes[1].axis('off')

        # SAM-CLIP 予測マスク (赤色半透明オーバーレイ)
        axes[2].imshow(orig_img)
        mask_overlay = np.zeros((*pred_arr.shape, 4))
        mask_overlay[pred_arr == 1] = [1, 0, 0, 0.5] # 赤色・透明度50%
        axes[2].imshow(mask_overlay)
        axes[2].set_title(f"SAM-CLIP Output ('{text_prompt}')\nIoU: {iou:.3f} | Prec: {prec:.3f}")
        axes[2].axis('off')

        plt.tight_layout()
        save_path = os.path.join(output_dir, f"result_{idx}_{img_name}")
        plt.savefig(save_path, bbox_inches='tight')
        plt.close(fig)

    num_samples = len(lines)
    mean_iou = total_iou / num_samples
    mean_prec = total_precision / num_samples
    mean_rec = total_recall / num_samples

    # 定量評価レポートの表示
    print("\n================ 評価結果 (Quantitative Report) ================")
    print(f"- Mean IoU       : {mean_iou:.4f}")
    print(f"- Mean Precision : {mean_prec:.4f} (過剰検知抑制の主要指標)")
    print(f"- Mean Recall    : {mean_rec:.4f}")
    print(f"- 可視化結果保存先: {output_dir}")
    print("=================================================================\n")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-val_list', type=str, default='mini_dataset_v2/val.txt')
    parser.add_argument('-img_folder', type=str, default='mini_dataset_v2/images')
    parser.add_argument('-mask_folder', type=str, default='mini_dataset_v2/masks')
    parser.add_argument('-output_dir', type=str, default='eval_results')
    parser.add_argument('-text_prompt', type=str, default='dog')

    # parse_args() を parse_known_args() に変更（Jupyterの余計な引数を無視する）
    args, _ = parser.parse_known_args()

    run_evaluation(args.val_list, args.img_folder, args.mask_folder, args.output_dir, args.text_prompt)

"""ここから下は学習なしで動作させようとしたコード。
ほとんと意味がないものになった。(train抜きでは何も検知しないため)

"""

import os
import json
import re

# 1. リポジトリ内の ArgsObj の定義場所を検索して __getattr__ を自動注入
patched = False
for root, dirs, files in os.walk("."):
    for file in files:
        if file.endswith(".py"):
            filepath = os.path.join(root, file)
            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

            if "class ArgsObj" in content:
                print(f"ArgsObj の定義箇所を発見: {filepath}")
                # __getattr__ が未実装の場合はクラス定義内に自動挿入
                if "__getattr__" not in content:
                    patched_content = re.sub(
                        r"(class ArgsObj[^\n]*:\n)",
                        r"\1    def __getattr__(self, name):\n        return False\n",
                        content
                    )
                    with open(filepath, "w", encoding="utf-8") as f:
                        f.write(patched_content)
                    print(f"-> {filepath} に動的セーフティガード (__getattr__) を自動注入しました。")
                else:
                    print("-> すでに __getattr__ が定義されています。")
                patched = True

if not patched:
    print("※ class ArgsObj が見つからなかったため、json側の完全網羅で対応します。")

# 2. image_encoder.py や transformer.py が要求する全設定を網羅した args.json を生成
args_data = {
    # 基本設定
    "sam_ckpt": "sam_vit_b_01ec64.pth",
    "arch": "vit_b",
    "model_type": "vit_b",
    "clip_model": "ViT-B/32",
    "num_cls": 1,
    "image_size": 1024,
    "devices": ["cuda"],
    "eval_type": "val",

    # image_encoder.py フラグ類
    "thd": False,
    "if_encoder_adapter": False,
    "encoder_adapter_depths": [],
    "encoder_adapter_type": "mlp",
    "encoder_adapter_dim": 64,
    "drop_path_rate": 0.1,

    # transformer.py / mask_decoder フラグ類
    "if_mask_decoder_adapter": False,
    "decoder_adapt_depth": 0,
    "decoder_adapter_depths": [],
    "decoder_adapter_type": "mlp",
    "decoder_adapter_dim": 64,

    # その他パイプライン制御
    "if_split_encoder_gpus": False,
    "if_text_encoder": True,
    "if_image_encoder": True,
    "if_fusion": False
}

os.makedirs("ckpt", exist_ok=True)
with open("ckpt/args.json", "w", encoding="utf-8") as f:
    json.dump(args_data, f, indent=4)

print("ckpt/args.json の更新が完了しました。")

import json
import os

# 1. args.json の num_cls を 3 に更新（SAM標準の4トークン構造に適合させる）
json_path = "ckpt/args.json"
if os.path.exists(json_path):
    with open(json_path, "r", encoding="utf-8") as f:
        args_data = json.load(f)

    args_data["num_cls"] = 3

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(args_data, f, indent=4)
    print("ckpt/args.json の num_cls を 3 に更新しました。")

# 2. inference_sam_clip.py の load_state_dict を strict=False に書き換え
py_path = "inference_sam_clip.py"
with open(py_path, "r", encoding="utf-8") as f:
    content = f.read()

# strict=True を strict=False に置き換え
if "strict=True" in content:
    content = content.replace("strict=True", "strict=False")
    with open(py_path, "w", encoding="utf-8") as f:
        f.write(content)
    print("inference_sam_clip.py の load_state_dict を strict=False に書き換えました。")

import os
import re
import torch

# 1. inference_sam_clip.py の直参照 checkpoint["xxx"] を safe get 参照に自動修復
py_path = "inference_sam_clip.py"
if os.path.exists(py_path):
    with open(py_path, "r", encoding="utf-8") as f:
        content = f.read()

    # checkpoint["xxx"] を checkpoint.get("xxx", {}) に置き換え
    content_updated = re.sub(
        r'checkpoint\[(["\'])(\w+)\1\]',
        r'checkpoint.get("\2", {})',
        content
    )

    with open(py_path, "w", encoding="utf-8") as f:
        f.write(content_updated)
    print("inference_sam_clip.py の重みロード処理を安全な参照形式に修正しました。")

# 2. ckpt/checkpoint_best.pth に不足しているキーのダミー補填
ckpt_path = "ckpt/checkpoint_best.pth"
if os.path.exists(ckpt_path):
    checkpoint = torch.load(ckpt_path, map_location="cpu")

    # SAM-CLIP が参照する可能性のあるコンポーネントキー群
    required_keys = ["fc_sam_to_clip", "clip", "text_encoder", "image_encoder"]
    updated = False
    for k in required_keys:
        if k not in checkpoint:
            checkpoint[k] = {}
            updated = True

    if updated:
        torch.save(checkpoint, ckpt_path)
        print("ckpt/checkpoint_best.pth に欠損キーの補填を完了しました。")

import torch
import cv2
import matplotlib.pyplot as plt
from PIL import Image

# リポジトリ内のモジュールをインポート
# （※リポジトリの構成に応じてパスを指定します）
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator

# デバイスの設定
device = "cuda" if torch.cuda.is_available() else "cpu"

# 1. SAMモデルのロード
sam_checkpoint = "sam_vit_b_01ec64.pth"
sam = sam_model_registry["vit_b"](checkpoint=sam_checkpoint).to(device)

# 2. テスト用画像の準備
!wget -q -O test.jpg "https://raw.githubusercontent.com/facebookresearch/segment-anything/main/notebooks/images/dog.jpg"

image = cv2.imread("test.jpg")
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# 3. リポジトリの仕様に沿ったSAM-CLIP処理の呼び出し
# ※リポジトリ付属のスクリプト（例: main.py や demo.py）がある場合は、以下のように直接実行も可能です
!python main.py --image_path test.jpg --sam_checkpoint sam_vit_b_01ec64.pth

import os

# 1. 変更で破損した inference_sam_clip.py を元の状態に復元
os.system("git checkout inference_sam_clip.py")

file_path = "inference_sam_clip.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

new_lines = []
in_args_obj = False
added = False

# 2. ArgsObj クラスのインデントを崩さずに __getattr__ を挿入
for line in lines:
    if "class ArgsObj" in line:
        in_args_obj = True
        new_lines.append(line)
    elif in_args_obj and not added and line.strip().startswith("def "):
        # 既存のメソッド（__init__等）と同じインデント幅を取得
        indent = " " * (len(line) - len(line.lstrip()))
        getattr_code = f"{indent}def __getattr__(self, name):\n{indent}    return False\n"
        new_lines.append(getattr_code)
        new_lines.append(line)
        added = True
        in_args_obj = False
    else:
        new_lines.append(line)

with open(file_path, "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print("inference_sam_clip.py の構文エラーを修正し、セーフティガードを適用しました。")

import torch
import os

os.makedirs("ckpt", exist_ok=True)

# 1. Meta公式のSAM重みを読み込み
sam_path = "sam_vit_b_01ec64.pth"
if os.path.exists(sam_path):
    state_dict = torch.load(sam_path, map_location="cpu")

    # 2. {"sam": state_dict} 形式にラップして保存
    checkpoint = {"sam": state_dict}
    torch.save(checkpoint, "ckpt/checkpoint_best.pth")
    print("ckpt/checkpoint_best.pth を SAM-CLIP の要求フォーマットに変換・保存しました。")
else:
    print(f"エラー: {sam_path} が見つかりません。")

!python inference_sam_clip.py \
    --checkpoint_dir ./ckpt \
    --image_dir input_images \
    --output_dir output_masks \
    --device cuda \
    --text_prompt "dog"

!pip install git+https://github.com/facebookresearch/segment-anything.git

import os
import torch
import cv2
import numpy as np
import matplotlib.pyplot as plt
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator

def show_anns(anns, ax):
    """生成されたすべてのマスクをランダムな色で重畳表示する関数"""
    if len(anns) == 0:
        return
    sorted_anns = sorted(anns, key=(lambda x: x['area']), reverse=True)
    ax.set_autoscale_on(False)

    img = np.ones((sorted_anns[0]['segmentation'].shape[0], sorted_anns[0]['segmentation'].shape[1], 4))
    img[:, :, 3] = 0
    for ann in sorted_anns:
        m = ann['segmentation']
        color_mask = np.concatenate([np.random.random(3), [0.6]]) # アルファ値0.6
        img[m] = color_mask
    ax.imshow(img)

def run_sam_standalone(image_path, sam_checkpoint, model_type="vit_b", output_path="sam_standalone_result.png"):
    # デバイスの設定
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"使用デバイス: {device}")

    # 1. 事前学習済みSAMモデルのロード（ファインチューニング前の公式重み）
    print("事前学習済みSAMモデルをロード中...")
    sam = sam_model_registry[model_type](checkpoint=sam_checkpoint)
    sam.to(device=device)

    # 2. 自動マスク生成クラスの初期化
    # (points_per_side などのパラメータで検知の細かさを制御可能)
    mask_generator = SamAutomaticMaskGenerator(
        model=sam,
        points_per_side=32,          # グリッドサンプリング点数 (大きくするとより細かく検出)
        pred_iou_thresh=0.88,        # マスク品質の閾値
        stability_score_thresh=0.95, # マスク安定性の閾値
        crop_n_layers=0,
    )

    # 3. 画像の読み込み
    if not os.path.exists(image_path):
        print(f"エラー: 画像ファイルが見つかりません ({image_path})")
        return

    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # 4. 全自動マスク生成の実行
    print("画像全体のマスクを自動生成中...")
    masks = mask_generator.generate(image)
    print(f"検出された合計マスク数: {len(masks)} 個")

    # 5. 可視化と結果の保存
    fig, axes = plt.subplots(1, 2, figsize=(16, 8))

    # 元画像
    axes[0].imshow(image)
    axes[0].set_title("Original Image")
    axes[0].axis('off')

    # SAM単体出力（全自動検知マスク）
    axes[1].imshow(image)
    show_anns(masks, axes[1])
    axes[1].set_title(f"Vanilla SAM Output\n({len(masks)} masks detected)")
    axes[1].axis('off')

    plt.tight_layout()
    plt.savefig(output_path, bbox_inches='tight', dpi=150)
    plt.close(fig)

    print(f"可視化結果を保存しました: {output_path}")

if __name__ == '__main__':
    # 対象画像と重みファイルの指定
    target_image = "/content/SAM-CLIP/mini_dataset_v2/images/000000578500.jpg" # 検証したい画像パス
    checkpoint = "sam_vit_b_01ec64.pth"

    run_sam_standalone(
        image_path=target_image,
        sam_checkpoint=checkpoint,
        model_type="vit_b",
        output_path="vanilla_sam_result.png"
    )

