# -*- coding: utf-8 -*-
"""Created_LLM_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCO-Co9aRO5u8vQM10p5fNHI-H0yNt5J
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

!pip install datasets

# -----------------------------
# Utilities: unfold_kv (same as earlier)
# -----------------------------
def unfold_kv(x: torch.Tensor, kernel_size: int, padding: int = 0):
    """
    x: (B, H, T, D)
    returns: (B, H, T, kernel_size, D)
    """
    B, H, T, D = x.shape
    x_img = x.permute(0, 1, 3, 2).reshape(B * H, D, 1, T)
    x_unf = F.unfold(x_img, kernel_size=(1, kernel_size), padding=(0, padding), stride=(1, 1))
    x_unf = x_unf.view(B * H, D, kernel_size, T)
    x_unf = x_unf.permute(0, 3, 2, 1).reshape(B, H, T, kernel_size, D)
    return x_unf

# -----------------------------
# RoPE helpers
# -----------------------------
def build_rope_cache(seq_len: int, dim: int, device=None, dtype=torch.float32):
    """
    Build cos and sin caches for RoPE.
    Returns:
      cos: (seq_len, dim//2)
      sin: (seq_len, dim//2)
    Note: dim must be even (we treat pairs).
    """
    assert dim % 2 == 0, "RoPE head dim must be even"
    half = dim // 2
    inv_freq = 1.0 / (10000 ** (torch.arange(0, half, dtype=dtype, device=device) / half))
    positions = torch.arange(seq_len, dtype=dtype, device=device).unsqueeze(1)  # (seq_len,1)
    angles = positions * inv_freq.unsqueeze(0)  # (seq_len, half)
    cos = torch.cos(angles)  # (seq_len, half)
    sin = torch.sin(angles)
    return cos, sin

def apply_rope_to_qk(x: torch.Tensor, cos: torch.Tensor, sin: torch.Tensor):
    """
    x: (B, H, T, D) where D is even
    cos, sin: (T, D//2)
    returns rotated x of same shape
    """
    B, H, T, D = x.shape
    half = D // 2
    # Split interleaved: even/odd positions along last dim
    x1 = x[..., :D:2]  # (B,H,T,half)
    x2 = x[..., 1:D:2]  # (B,H,T,half)
    # cos/sin -> (1,1,T,half) for broadcasting
    cos_b = cos.unsqueeze(0).unsqueeze(0)  # (1,1,T,half)
    sin_b = sin.unsqueeze(0).unsqueeze(0)
    # rotate
    x1c = x1 * cos_b - x2 * sin_b
    x2c = x1 * sin_b + x2 * cos_b
    # interleave back: [x1c0, x2c0, x1c1, x2c1, ...]
    x_rot = torch.stack([x1c, x2c], dim=-1).reshape(B, H, T, D)
    return x_rot

# -----------------------------
# Hybrid Sparse Attention with RoPE
# -----------------------------
class RoPEHybridSparseAttention(nn.Module):
    def __init__(self, dim: int, num_heads: int = 8, window: int = 4, dropout: float = 0.0):
        super().__init__()
        assert dim % num_heads == 0, "dim must be divisible by num_heads"
        head_dim = dim // num_heads
        assert head_dim % 2 == 0, "head_dim must be even for RoPE"
        self.dim = dim
        self.num_heads = num_heads
        self.head_dim = head_dim
        self.window = window
        self.kernel_size = 2 * window + 1

        self.q_proj = nn.Linear(dim, dim, bias=False)
        self.k_proj = nn.Linear(dim, dim, bias=False)
        self.v_proj = nn.Linear(dim, dim, bias=False)
        self.out_proj = nn.Linear(dim, dim, bias=False)
        self.dropout = nn.Dropout(dropout)

        # caches for RoPE will be created on forward based on seq_len

    def forward(self, x: torch.Tensor, global_mask: torch.Tensor = None):
        """
        x: (B, T, D)
        global_mask: (B, T) bool
        returns: out (B, T, D), full_attn (B, H, T, T)  # full_attn is for visualization
        """
        B, T, D = x.shape
        device = x.device
        # 1) project
        q = self.q_proj(x).view(B, T, self.num_heads, self.head_dim).permute(0, 2, 1, 3)  # (B,H,T,dh)
        k = self.k_proj(x).view(B, T, self.num_heads, self.head_dim).permute(0, 2, 1, 3)
        v = self.v_proj(x).view(B, T, self.num_heads, self.head_dim).permute(0, 2, 1, 3)

        # 1.5) build RoPE cache and apply to q,k
        cos, sin = build_rope_cache(T, self.head_dim, device=device, dtype=q.dtype)  # (T, dh/2)
        q = apply_rope_to_qk(q, cos, sin)
        k = apply_rope_to_qk(k, cos, sin)

        # 2) extract local windows
        K_windows = unfold_kv(k, kernel_size=self.kernel_size, padding=self.window)  # (B,H,T,win,dh)
        V_windows = unfold_kv(v, kernel_size=self.kernel_size, padding=self.window)  # (B,H,T,win,dh)

        # 3) local scores
        scores_local = torch.einsum("bhtd,bhtwd->bhtw", q, K_windows) / (self.head_dim ** 0.5)  # (B,H,T,win)

        # 4) global part
        if global_mask is None:
            scores_global = None
            K_global = None
            V_global = None
            global_idx_list = [torch.empty(0, dtype=torch.long, device=device) for _ in range(B)]
            global_token_mask = None
        else:
            global_idx_list = []
            maxG = 0
            for b in range(B):
                idx = torch.nonzero(global_mask[b], as_tuple=False).squeeze(-1)
                if idx.numel() == 0:
                    idx = torch.empty(0, dtype=torch.long, device=device)
                global_idx_list.append(idx)
                if idx.numel() > maxG:
                    maxG = idx.numel()

            if maxG == 0:
                scores_global = None
                K_global = None
                V_global = None
                global_token_mask = None
            else:
                # pad to maxG
                K_global = torch.zeros(B, self.num_heads, maxG, self.head_dim, device=device, dtype=q.dtype)
                V_global = torch.zeros(B, self.num_heads, maxG, self.head_dim, device=device, dtype=q.dtype)
                global_token_mask = torch.zeros(B, maxG, dtype=torch.bool, device=device)
                for b in range(B):
                    idx = global_idx_list[b]
                    if idx.numel() == 0:
                        continue
                    kg = k[b, :, idx, :]  # (H, G_b, dh)
                    vg = v[b, :, idx, :]
                    G_b = kg.shape[1]
                    K_global[b, :, :G_b, :] = kg
                    V_global[b, :, :G_b, :] = vg
                    global_token_mask[b, :G_b] = True

                scores_global = torch.einsum("bhtd,bhgd->bhtg", q, K_global) / (self.head_dim ** 0.5)
                # mask padded later

        # 5) combine local and global
        if scores_global is None:
            attn_local = F.softmax(scores_local, dim=-1)
            ctx_local = torch.einsum("bhtw,bhtwd->bhtd", attn_local, V_windows)
            out_heads = ctx_local  # (B,H,T,dh)
            full_attn = torch.zeros(B, self.num_heads, T, T, device=device, dtype=q.dtype)
            # fill local-only full_attn
            for t in range(T):
                left = max(0, t - self.window)
                right = min(T, t + self.window + 1)
                win_len = right - left
                # attn_local[..., t, :win_len] -> place at positions left:right
                full_attn[..., t, left:right] = attn_local[..., t, :win_len]
        else:
            # mask padded global slots
            gmask = global_token_mask.unsqueeze(1).unsqueeze(2)  # (B,1,1,G)
            scores_global = scores_global.masked_fill(~gmask, float("-1e9"))

            scores_cat = torch.cat([scores_local, scores_global], dim=-1)  # (B,H,T, win+G)
            attn_cat = F.softmax(scores_cat, dim=-1)
            attn_cat = self.dropout(attn_cat)

            w_local = attn_cat[..., : self.kernel_size]
            w_global = attn_cat[..., self.kernel_size :]

            ctx_local = torch.einsum("bhtw,bhtwd->bhtd", w_local, V_windows)
            ctx_global = torch.einsum("bhtg,bhgd->bhtd", w_global, V_global)
            out_heads = ctx_local + ctx_global

            # build full_attn for visualization
            full_attn = torch.zeros(B, self.num_heads, T, T, device=device, dtype=q.dtype)
            for b in range(B):
                gidx = global_idx_list[b]
                for t in range(T):
                    left = max(0, t - self.window)
                    right = min(T, t + self.window + 1)
                    win_len = right - left
                    # local part
                    full_attn[b, :, t, left:right] = w_local[b, :, t, :win_len]
                    # global part -> assign per actual indices
                    if gidx.numel() > 0:
                        G_b = gidx.numel()
                        full_attn[b, :, t, gidx] += w_global[b, :, t, :G_b]

        # 6) merge heads & out proj
        out = out_heads.permute(0, 2, 1, 3).contiguous().view(B, T, D)
        out = self.out_proj(out)

        return out, full_attn


# -----------------------------
# 2) Small Transformer Encoder block using RoPEHybridSparseAttention
# -----------------------------
class EncoderBlock(nn.Module):
    def __init__(self, dim, num_heads, mlp_dim, window=4, dropout=0.1):
        super().__init__()
        self.attn = RoPEHybridSparseAttention(dim=dim, num_heads=num_heads, window=window, dropout=dropout)
        self.ln1 = nn.LayerNorm(dim, eps=1e-6)
        self.ln2 = nn.LayerNorm(dim, eps=1e-6)
        self.mlp = nn.Sequential(
            nn.Linear(dim, mlp_dim),
            nn.GELU(),
            nn.Linear(mlp_dim, dim),
            nn.Dropout(dropout),
        )
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, global_mask=None):
        # Attention (RoPE + Local+Global)
        residual = x
        x_ln = self.ln1(x)
        attn_out, _ = self.attn(x_ln, global_mask=global_mask)  # attn returns (out, full_attn)
        x = residual + self.dropout(attn_out)

        # MLP
        residual = x
        x_ln2 = self.ln2(x)
        x = residual + self.mlp(x_ln2)
        return x

# -----------------------------
# 3) Encoder-style LLM (small)
# -----------------------------
class SparseRoPEEncoderLM(nn.Module):
    def __init__(self, vocab_size, dim=256, num_heads=8, num_layers=4, mlp_dim=512, window=4, dropout=0.1, tie_word_embeddings=True):
        super().__init__()
        assert dim % num_heads == 0
        self.vocab_size = vocab_size
        self.dim = dim
        self.token_emb = nn.Embedding(vocab_size, dim)
        self.layers = nn.ModuleList([
            EncoderBlock(dim=dim, num_heads=num_heads, mlp_dim=mlp_dim, window=window, dropout=dropout)
            for _ in range(num_layers)
        ])
        self.ln_final = nn.LayerNorm(dim, eps=1e-6)
        self.lm_head = nn.Linear(dim, vocab_size, bias=False)
        if tie_word_embeddings:
            # weight tying
            self.lm_head.weight = self.token_emb.weight

    def forward(self, input_ids, global_mask=None, return_attn=False):
        """
        input_ids: (B, T) long
        global_mask: (B, T) bool
        returns: logits (B, T, V) ; optionally optionally return last layer full_attn (B, H, T, T)
        """
        x = self.token_emb(input_ids) * (self.dim ** 0.5)  # scale
        full_attn_last = None
        for layer in self.layers:
            x = layer(x, global_mask=global_mask)
        x = self.ln_final(x)
        logits = self.lm_head(x)  # (B, T, V)
        if return_attn:
            # get full_attn from the last attention module by running one more call to get full_attn
            # (slightly wasteful but useful for visualization)
            # To avoid double-computation, we can call last layer's attn directly on ln input:
            with torch.no_grad():
                # reconstruct last layer's attn input: apply ln on pre-last activation
                pre_last = x  # note: in this simple code we don't have easy access to pre-ln input; skip
                full_attn_last = None
        return logits, full_attn_last


# -----------------------------
# 4) MLM Head Module (BERT style)
# -----------------------------
class RoPEMaskedLMHead(nn.Module):
    """
    BERTスタイルのMLMヘッド。
    Encoderの出力に対して、非線形変換と正規化を行ってから単語予測を行います。
    構成: Linear -> GELU -> LayerNorm -> Linear (Decoder)
    """
    def __init__(self, dim, vocab_size):
        super().__init__()
        self.dense = nn.Linear(dim, dim)
        self.activation = nn.GELU()
        self.layer_norm = nn.LayerNorm(dim, eps=1e-6)
        self.decoder = nn.Linear(dim, vocab_size, bias=False)

        # 出力層にはバイアス項をつけるのが一般的です
        self.bias = nn.Parameter(torch.zeros(vocab_size))
        self.decoder.bias = self.bias

    def forward(self, features):
        x = self.dense(features)
        x = self.activation(x)
        x = self.layer_norm(x)
        # 射影してLogitsを得る
        x = self.decoder(x)
        return x


# -----------------------------
# 5) Sparse RoPE BERT for Masked LM
# -----------------------------
class SparseRoPEBertForMaskedLM(nn.Module):
    def __init__(self, vocab_size, dim=256, num_heads=8, num_layers=4, mlp_dim=512, window=4, dropout=0.1, tie_word_embeddings=True):
        super().__init__()
        assert dim % num_heads == 0
        self.vocab_size = vocab_size
        self.dim = dim

        # 埋め込み層
        self.token_emb = nn.Embedding(vocab_size, dim)

        # エンコーダー層 (既存のEncoderBlockを使用)
        self.layers = nn.ModuleList([
            EncoderBlock(dim=dim, num_heads=num_heads, mlp_dim=mlp_dim, window=window, dropout=dropout)
            for _ in range(num_layers)
        ])

        # 元のコードにあったEncoder最終段のLNは、MLMヘッド内にLNがあるため
        # ここでは必須ではありませんが、BERTのアーキテクチャに従い
        # エンコーダー出力そのものを安定させるために入れても構いません。
        # 今回はBERT本来の構成に近づけるため、Head側にLNを任せ、ここは削除またはそのままパスします。
        # (ただし、Pre-LN構成の場合は最後にLNを入れるのが通例なので、念のため残しておきます)
        self.ln_final = nn.LayerNorm(dim, eps=1e-6)

        # MLM用ヘッド (Linear -> GELU -> LN -> Linear)
        self.mlm_head = RoPEMaskedLMHead(dim, vocab_size)

        # Weight Tying (埋め込み層と出力層の重み共有)
        if tie_word_embeddings:
            self.mlm_head.decoder.weight = self.token_emb.weight

        # 損失関数
        self.loss_fct = nn.CrossEntropyLoss()

    def forward(self, input_ids, global_mask=None, labels=None):
        """
        input_ids: (B, T) - 一部が[MASK]トークンに置き換わっている入力
        global_mask: (B, T) - Global Attentionを使う位置
        labels: (B, T) - MLMの正解ラベル（計算対象外のトークンは -100 にする）
        """
        # 1. Embedding
        x = self.token_emb(input_ids) * (self.dim ** 0.5)

        # 2. Encoder Stack
        for layer in self.layers:
            x = layer(x, global_mask=global_mask)

        # Final Norm (Encoderの出力安定化)
        sequence_output = self.ln_final(x)

        # 3. MLM Head
        prediction_scores = self.mlm_head(sequence_output)  # (B, T, V)

        # 4. Loss Calculation (Optional)
        loss = None
        if labels is not None:
            # CrossEntropyLossは (N, C) と (N) の入力を期待するため、次元を変更
            # -100 のラベルは自動的に無視されます
            loss = self.loss_fct(prediction_scores.view(-1, self.vocab_size), labels.view(-1))

        return prediction_scores, loss

from transformers import AutoTokenizer

# モデルのロード
model_id = "Qwen/Qwen2.5-7B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

sentence = "強化学習は非常に奥深く、解決に多くの時間がかかる"

# 1. まずIDに変換する (encode)
token_ids = tokenizer.encode(sentence)

# 2. IDを1つずつ日本語に戻してリストにする (decode)
# これで正しい分割単位が見えます
tokens_readable = [tokenizer.decode([tid]) for tid in token_ids]

print("【正しい分割結果】")
print(tokens_readable)

# 【重要】Causal LM用のトークナイザには [MASK] トークンがない場合があるため追加する
if tokenizer.mask_token is None:
    tokenizer.add_special_tokens({'mask_token': '[MASK]'})
    print(f"Mask token added: {tokenizer.mask_token} (ID: {tokenizer.mask_token_id})")
# 参考: 元の文字化け状態を確認したい場合（tokenizer.tokenizeを直接呼ぶとこうなる）
# print(tokenizer.tokenize(sentence))

print(tokenizer.vocab_size)

import matplotlib.pyplot as plt

B, T, D = 1, 48, 128
H = 8
window = 4
device = "cuda" if torch.cuda.is_available() else "cpu"

model = RoPEHybridSparseAttention(dim=D, num_heads=H, window=window).to(device)
x = torch.randn(B, T, D, device=device)

# set a couple of global tokens
global_mask = torch.zeros(B, T, dtype=torch.bool, device=device)
global_mask[0, 0] = True
global_mask[0, 12] = True

out, full_attn = model(x, global_mask)
print("out.shape=", out.shape)            # (B,T,D)
print("full_attn.shape=", full_attn.shape)  # (B,H,T,T)

# visualize head 0
att = full_attn[0, 0].detach().cpu().numpy()  # (T,T)
plt.figure(figsize=(6,6))
plt.imshow(att, aspect="auto")
plt.colorbar()
plt.title("RoPE + Hybrid Sparse Attention (head 0)")
plt.show()

# モデル設定
vocab_size = tokenizer.vocab_size + 5000
dim = 768
window = 4

model = SparseRoPEBertForMaskedLM(
    vocab_size=vocab_size,
    dim=dim,
    num_heads=8,
    num_layers=8,
    window=window
)

# ダミーデータ (Batch=2, Seq=10)
input_ids = torch.randint(0, vocab_size, (2, 10))

# MLM用のラベルを作成（通常は入力の一部を[MASK]にし、その正解をlabelsに入れる）
# 計算しない場所は -100
labels = input_ids.clone()
labels[:, :5] = -100  # 前半はLoss計算しない

# Forward pass
logits, loss = model(input_ids, labels=labels)

print("Logits shape:", logits.shape)  # (2, 10, 1000)
print("Loss:", loss.item())           # スカラー値

from huggingface_hub import login
from datasets import load_dataset

# 認証後にロードを実行
# trust_remote_code=True を追加します
dataset = load_dataset(
    "izumi-lab/wikipedia-ja-20230720",
    split="train",
    trust_remote_code=True  # <--- これが必要です
)

print(next(iter(dataset)))

# コンテキスト長（モデルに入力する長さ）
block_size = 512

def tokenize_function(examples):
    # テキストカラム名はデータセットによりますが、izumi-labの場合は "text" です
    return tokenizer(examples["text"])

def group_texts(examples):
    # 1. バッチ内のすべてのテキストを結合する
    concatenated_examples = {k: sum(examples[k], []) for k in examples.keys()}
    total_length = len(concatenated_examples[list(examples.keys())[0]])

    # 2. block_size の倍数になるように切り詰める
    # (余った半端な部分は捨てる)
    if total_length >= block_size:
        total_length = (total_length // block_size) * block_size

    # 3. block_size ごとに分割する
    result = {
        k: [t[i : i + block_size] for i in range(0, total_length, block_size)]
        for k, t in concatenated_examples.items()
    }
    # MLMでは "labels" カラムはDataCollatorが自動で作るため、ここではまだ不要
    # ただし、元の input_ids を labels としてコピーしておくとわかりやすい場合もあります
    result["labels"] = result["input_ids"].copy()
    return result

# --- 処理の実行 ---

# 1. まず通常のトークン化
tokenized_datasets = dataset.map(
    tokenize_function,
    batched=True,
    num_proc=4, # 並列処理数
    remove_columns=dataset.column_names # 元のテキストカラムは不要になるので削除
)

# 2. 結合して分割 (Chunking)
lm_datasets = tokenized_datasets.map(
    group_texts,
    batched=True,
    num_proc=4
)

print(f"加工後のデータ数: {len(lm_datasets)}")
print(f"各データの長さ: {len(lm_datasets[0]['input_ids'])}") # 512になっているはず

from google.colab import drive
import os
import shutil

# Google Driveを /content/drive にマウント
drive.mount('/content/drive')
print("Google Driveがマウントされました。")

# 1. Google Driveに保存したモデルファイル名
MODEL_FILE_NAME = "sparse_rope_mlm_model.pth"

# 2. Google Drive上のモデルファイルのフルパス（最後のファイル名を除くディレクトリ）
# 例: /content/drive/MyDrive/sparse_mlm_models/
DRIVE_SOURCE_DIR = "/content/drive/MyDrive/sparse_mlm_models/"

# 3. Colab内のコピー先ディレクトリ (通常は現在の作業ディレクトリ)
LOCAL_DESTINATION_DIR = os.getcwd() # './' を意味する

# 2. 転送元と転送先のフルパスを定義
source_path = os.path.join(DRIVE_SOURCE_DIR, MODEL_FILE_NAME)
destination_path = os.path.join(LOCAL_DESTINATION_DIR, MODEL_FILE_NAME)

print(f"Source path on Drive: {source_path}")
print(f"Destination path in Colab: {destination_path}")

# 3. ファイルの存在確認とコピーの実行
try:
    if not os.path.exists(source_path):
        raise FileNotFoundError(f"File not found on Drive at: {source_path}")

    # コピーを実行
    shutil.copy(source_path, destination_path)

    print(f"\n✅ Successfully copied model from Google Drive!")
    print(f"Model '{MODEL_FILE_NAME}' is now available in the local directory.")

    # コピーされたローカルのパラメータファイルを読み込む
    state_dict = torch.load(MODEL_FILE_NAME)

    # モデルにパラメータをロード
    model.load_state_dict(state_dict)

except FileNotFoundError as e:
    print(f"\n❌ Error: {e}")
    print("Please check if the 'DRIVE_SOURCE_DIR' and 'MODEL_FILE_NAME' variables are correct.")
except Exception as e:
    print(f"\n❌ An unexpected error occurred during file transfer: {e}")

# データセットの保存先ディレクトリ名
SAVE_DIR = "wikipedia_ja_mlm_processed"

# 1. 保存処理の実行
# lm_datasets は 'train' などの分割情報（split）を持つ DatasetDict オブジェクトを想定
if isinstance(lm_datasets, dict):
    # DatasetDict の場合
    lm_datasets.save_to_disk(SAVE_DIR)
else:
    # 単一の Dataset の場合
    lm_datasets.save_to_disk(SAVE_DIR)

print(f"データセットを '{SAVE_DIR}' に保存しました。")

# 前のステップで設定した保存ディレクトリ名
SAVE_DIR = "wikipedia_ja_mlm_processed"

# コピー先のGoogle Drive内のパスを設定
# Driveのマイドライブ直下に "MLM_Datasets" フォルダを作成し、その中に保存する場合
DESTINATION_PATH = "/content/drive/MyDrive/MLM_Datasets/"

# シェルコマンドでディレクトリを再帰的（-r）にコピー
# コピー先に同名のフォルダがない場合は自動で作成されます
!cp -r {SAVE_DIR} {DESTINATION_PATH}

print(f"データセット '{SAVE_DIR}' を Google Drive の '{DESTINATION_PATH}{SAVE_DIR}' にコピーしました。")

# 前のステップで設定した保存ディレクトリ名
SAVE_DIR = "wikipedia_ja_mlm_processed"

# コピー先のGoogle Drive内のパスを設定
# Driveのマイドライブ直下に "MLM_Datasets" フォルダを作成し、その中に保存する場合
DESTINATION_PATH = "/content/drive/MyDrive/MLM_Datasets/"

!cp -r {DESTINATION_PATH} {SAVE_DIR}

from datasets import load_from_disk

SAVE_DIR = "wikipedia_ja_mlm_processed"
# 1. ディスクからデータセットをロード
lm_datasets = load_from_disk(SAVE_DIR)

# 2. ロードされたデータセットの確認
print(f"ロード完了。データセットの型: {type(lm_datasets)}")

from transformers import DataCollatorForLanguageModeling

# MLM用のDataCollatorを作成
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=True,              # MLMを行うフラグ
    mlm_probability=0.15   # 15%をマスクする（BERTの論文通り）
)

# --- 動作確認 ---
# 実際にどうマスクされるか見てみましょう
from torch.utils.data import DataLoader

dataloader = DataLoader(
    lm_datasets,
    batch_size=8,
    collate_fn=data_collator,
    shuffle=True  # ここを追加
)
batch = next(iter(dataloader))

# input_ids: マスクされた入力
# labels: 正解（マスクされていない場所は -100）
input_ids = batch["input_ids"][0]
labels = batch["labels"][0]

print("\n--- Masking Check ---")
print("Input IDs (一部):", input_ids[:20])
print("Labels    (一部):", labels[:20])

# デコードして確認（[MASK]が含まれているか見る）
decoded_text = tokenizer.decode(input_ids)
print("\n--- Decoded Text (with Mask) ---")
print(decoded_text[:200]) # 最初の200文字を表示

from torch.optim import AdamW
from tqdm.auto import tqdm

# ハイパーパラメータ
BATCH_SIZE = 4        # GPUメモリに合わせて調整 (Colabなら8~16くらい)
LEARNING_RATE = 1e-4  # 学習率
EPOCHS = 1            # エポック数

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device) # モデルをGPUへ転送

# デバイス確認
print(f"計算リソース: {device}")

# データセットの前処理(前回のコード)で作成した lm_datasets["train"] を使用
# DataCollatorが動的にマスキングを行います
train_loader = DataLoader(
    lm_datasets, # 前回のコードで作成したデータセット
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=data_collator # ここで[MASK]への置換が行われます
)

# オプティマイザの設定
optimizer = AdamW(model.parameters(), lr=LEARNING_RATE)

# --- 4. 学習ループ (Training Loop) ---

print("Start Training...")
model.train() # 学習モードへ

from IPython import display  # Jupyter Notebook用
import matplotlib.pyplot as plt


# ライブプロット準備
plt.ion()
fig, ax = plt.subplots()
loss_values = []

for epoch in range(EPOCHS):
    total_loss = 0
    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS}")

    for step, batch in enumerate(progress_bar):
        # バッチをGPUへ転送
        input_ids = batch["input_ids"].to(device)
        labels = batch["labels"].to(device)

        global_mask = None  # 簡易実装

        # 勾配初期化
        optimizer.zero_grad()

        # 順伝播
        logits, loss = model(input_ids, global_mask=global_mask, labels=labels)

        # 逆伝播
        loss.backward()

        # パラメータ更新
        optimizer.step()

        # ロス更新
        total_loss += loss.item()
        progress_bar.set_postfix({"loss": loss.item()})

        # --- ライブプロット更新 ---
        loss_values.append(loss.item())
        ax.clear()
        ax.plot(loss_values, label="Batch Loss")
        ax.set_xlabel("Step")
        ax.set_ylabel("Loss")
        ax.set_title(f"Epoch {epoch+1}")
        ax.legend()
        display.clear_output(wait=True)
        display.display(fig)

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1} - Average Loss: {avg_loss:.4f}")

    if epoch >= 6000:
        break

# --- 学習終了後 ---
plt.ioff()
plt.show()

# --- 5. モデルの保存 ---
torch.save(model.state_dict(), "sparse_rope_mlm_model.pth")
print("Model saved!")

import os
from google.colab import drive

# --- 5. モデルの保存 ---
model.cpu()
torch.save(model.state_dict(), "sparse_rope_mlm_model.pth")
print("Model saved!")

# --- 2. ファイルの転送 ---
# 学習済みのモデルファイル名
MODEL_FILE_NAME = "sparse_rope_mlm_model.pth"

# 保存先のGoogle Driveパスを設定
# 例: MyDrive/Colab Notebooks/saved_models/ に保存する場合
# フォルダは自動で作成されません。事前にDrive上にフォルダを作成しておくことを推奨します。
DRIVE_SAVE_PATH = "/content/drive/MyDrive/sparse_mlm_models/"

# 転送元と転送先のフルパスを定義
source_path = os.path.join(os.getcwd(), MODEL_FILE_NAME)
destination_path = os.path.join(DRIVE_SAVE_PATH, MODEL_FILE_NAME)

# 転送先のフォルダが存在しない場合は作成 (必須ではないが安全のため)
if not os.path.exists(DRIVE_SAVE_PATH):
    print(f"Creating directory: {DRIVE_SAVE_PATH}")
    os.makedirs(DRIVE_SAVE_PATH, exist_ok=True)

# os.rename または shutil.copy を使用してファイルを移動/コピー
# shutil.copy を使用すると、元のファイルはColabに残ります。
# os.rename を使用すると、元のファイルはDriveに移動し、Colabから削除されます。

try:
    import shutil
    # コピーを実行 (Colab上にファイルも残る)
    shutil.copy(source_path, destination_path)

    print(f"\n✅ Successfully copied model to Google Drive!")
    print(f"Source: {source_path}")
    print(f"Destination: {destination_path}")

    # shutil.copy が成功したため、Colab上のファイルを削除してディスク容量を空ける場合は以下のコメントアウトを外す
    # os.remove(source_path)
    # print(f"Local file {source_path} deleted.")

except FileNotFoundError:
    print(f"\n❌ Error: The model file '{MODEL_FILE_NAME}' was not found at {source_path}.")
    print("Please check the file name and the path where 'torch.save' was executed.")
except Exception as e:
    print(f"\n❌ An unexpected error occurred during file transfer: {e}")

print("embedding vocab size:", model.token_emb.weight.shape[0])
print("lm_head vocab size:", model.lm_head.weight.shape[0])
print("max input id:", batch["input_ids"].max().item())
print("max label:", batch["labels"].max().item())

import torch
import random
from IPython.display import HTML, display

# -----------------------------------------------
# ★ tokenizer, model, device はすでにロード済み
# -----------------------------------------------

# ランダムに MASK を付与
def random_mask_text(text, mask_ratio=0.15):

    encoding = tokenizer(text, return_tensors="pt", add_special_tokens=False)
    input_ids = encoding["input_ids"][0]

    tokens = tokenizer.convert_ids_to_tokens(input_ids)
    num_mask = max(1, int(len(tokens) * mask_ratio))

    mask_indices = random.sample(range(len(tokens)), num_mask)

    masked_tokens = tokens.copy()
    for idx in mask_indices:
        masked_tokens[idx] = tokenizer.mask_token

    return tokens, masked_tokens, mask_indices


# MASK部分を予測
def predict_masked_text(masked_tokens):
    input_ids = tokenizer.convert_tokens_to_ids(masked_tokens)
    input_tensor = torch.tensor([input_ids]).to(device)

    with torch.no_grad():
        outputs = model(input_tensor)

    logits = outputs[0]  # tuple の 0 番目が logits

    predicted_tokens = []
    for i, token in enumerate(masked_tokens):
        if token == tokenizer.mask_token:
            pred_id = logits[0, i].argmax().item()
            predicted_tokens.append(tokenizer.convert_ids_to_tokens(pred_id))
        else:
            predicted_tokens.append(token)

    return predicted_tokens


# HTMLで可視化
def visualize(tokens, masked_tokens, predicted_tokens, mask_indices):

    html = ""

    for i, (orig, masked, pred) in enumerate(zip(tokens, masked_tokens, predicted_tokens)):

        if i in mask_indices:
            # 正解 → 緑 / 不一致 → 赤
            color = "lightgreen" if orig == pred else "salmon"
            html += f'<span style="background-color:{color}; padding:2px; margin:2px;">'
            html += f'原:{tokenizer.convert_tokens_to_string([orig])} → 予:{tokenizer.convert_tokens_to_string([pred])}'
            html += '</span> '
        else:
            html += tokenizer.convert_tokens_to_string([orig]) + " "

    display(HTML(html))


# メイン処理
def run_mask_prediction():
    text = "孫の誕生を待ちわびていた忠能は、慶子が懐妊した時からお産の準備に大わらわとなった。当時、産殿の建設には、総工費100両が必要とされたが"

    tokens, masked_tokens, mask_indices = random_mask_text(text)
    predicted_tokens = predict_masked_text(masked_tokens)

    print("\n【元の文章】")
    print(tokenizer.convert_tokens_to_string(tokens))

    print("\n【MASK を含む文章】")
    print(tokenizer.convert_tokens_to_string(masked_tokens))

    print("\n【予測後の文章】")
    print(tokenizer.convert_tokens_to_string(predicted_tokens))

    print("\n【色付き可視化】")
    visualize(tokens, masked_tokens, predicted_tokens, mask_indices)


run_mask_prediction()

visualize_mlm_predictions(model, train_loader, tokenizer, device)

import torch
from IPython.display import HTML, display

# === HTMLで色を付けるユーティリティ ===
def color_text(text, color):
    return f"<span style='color:{color}; font-weight:bold'>{text}</span>"


# === メイン可視化関数（文章ごとに改行対応） ===
def visualize_mlm_predictions(model, dataloader, tokenizer, device):
    model.eval()

    batch = next(iter(dataloader))
    input_ids = batch["input_ids"].to(device)
    labels = batch["labels"].to(device)

    ids = input_ids[0].unsqueeze(0)

    with torch.no_grad():
        logits, _ = model(ids, global_mask=None, labels=None)

    pred_ids = torch.argmax(logits, dim=-1)[0].cpu().tolist()
    orig_ids = ids[0].cpu().tolist()
    label_ids = labels[0].cpu().tolist()

    html_output = ""

    # === 文区切り候補 ===
    sentence_end_tokens = ["。", "!", "！", "？", "?"]
    sep_token_id = tokenizer.sep_token_id

    for orig, pred, lab in zip(orig_ids, pred_ids, label_ids):

        # 特殊トークン処理
        if orig in tokenizer.all_special_ids:
            tok = tokenizer.decode([orig])
            html_output += color_text(tok, "gray") + " "

            # [SEP] などでは改行
            if orig == sep_token_id:
                html_output += "<br><br>"
            continue

        orig_token = tokenizer.decode([orig])
        pred_token = tokenizer.decode([pred])

        # === MASK 部分を色付け ===
        if lab != -100:
            html_output += (
                color_text(f"[MASK→{pred_token}]", "red")
                + color_text(f"({orig_token})", "blue")
                + " "
            )
        else:
            html_output += orig_token + " "

        # === 文の最後なら改行する ===
        if orig_token in sentence_end_tokens:
            html_output += "<br><br>"

    display(HTML("<div style='font-size:18px; line-height:1.8'>" + html_output + "</div>"))

visualize_mlm_predictions(model, train_loader, tokenizer, device)

import torch
import numpy as np
import random
import collections

# ====================================================================
# 【実行に必要なモックオブジェクトの定義】
# ====================================================================

# 1. デバイス定義
device = torch.device("cpu")

# 2. ダミーのトークナイザクラス定義 (変更なし)
class MockTokenizer:
    def __init__(self):
        self.vocab = {
            1: "[CLS]", 2: "[MASK]", 3: "[SEP]", 4: "[PAD]",
            5: "学習", 8: "モデル", 12: "デコード", 20: "プロセス",
            24: "成功", 25: "完了", 40: "結果", 45: "確認", 46: "分析",
            100: "処理", 110: "コード"
        }
        self.special_tokens = {"[CLS]", "[MASK]", "[SEP]", "[PAD]"}
        self.pad_token_id = 4

    def decode(self, token_ids, skip_special_tokens=False):
        tokens = []
        for tid in token_ids:
            if tid == -100 or tid == self.pad_token_id:
                continue
            token = self.vocab.get(tid, f"[UNK_{tid}]")
            if skip_special_tokens and token in self.special_tokens:
                continue
            tokens.append(token)
        return " ".join(tokens)

# 3. ダミーのモデルクラス定義 (変更なし)
class MockModel(torch.nn.Module):
    def __init__(self, vocab_size, seq_len):
        super().__init__()
        self.vocab_size = vocab_size
        self.seq_len = seq_len
    def forward(self, input_ids, global_mask=None, labels=None):
        batch_size = input_ids.shape[0]
        logits = torch.randn(batch_size, self.seq_len, self.vocab_size)
        loss = torch.tensor(0.5, dtype=torch.float32)
        return logits, loss

# 4. ★ ダミーのデータセットクラス定義 (インデックスでアクセス可能) ★
class MockDataset(torch.utils.data.Dataset):
    def __init__(self):
        # 10個のダミーサンプルを作成
        self.samples = []
        for i in range(10):
            # iによって少し異なるデータを作成
            input_ids = torch.randint(low=5, high=50, size=(10,))
            # マスク位置はランダムに2箇所
            mask_indices = torch.tensor(random.sample(range(10), 2))
            labels = torch.full((10,), -100, dtype=torch.long)
            labels[mask_indices] = input_ids[mask_indices]
            input_ids[mask_indices] = 2 # [MASK] ID (2) を挿入

            self.samples.append({
                "input_ids": input_ids,
                "labels": labels
            })

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]

# 5. ダミーのデータローダークラス定義 (Datasetを持つ)
class MockDataLoader:
    def __init__(self, dataset, batch_size):
        self.dataset = dataset
        self.batch_size = batch_size

    def __iter__(self):
        # 実際はshuffle=Trueでイテレータを生成するが、ここではインデックス抽出に集中
        return self

    def __next__(self):
        raise StopIteration # 推論コードでは使用しない

# --- 初期化 ---
VOCAB_SIZE = 50
SEQ_LEN = 10
BATCH_SIZE = 4 # ★ バッチサイズを設定 ★

model = MockModel(VOCAB_SIZE, SEQ_LEN).to(device)
tokenizer = MockTokenizer()
train_dataset = MockDataset() # Datasetを初期化
train_loader = MockDataLoader(train_dataset, BATCH_SIZE) # DataLoaderを初期化
sample_index = 0

# ====================================================================

# --- 推論コードの実行 ---

# 1. モデルを評価モードに設定
model.eval()
print("Model set to evaluation mode (model.eval()).")

# 2. 勾配計算を無効化
with torch.no_grad():

    # 3. ★★★ データセットからランダムなインデックスを指定してバッチを構築 ★★★

    # データセットの全サイズを取得
    dataset_size = len(train_loader.dataset)

    if dataset_size == 0:
        print("Error: Dataset is empty.")
        raise IndexError

    # バッチの開始インデックスをランダムに決定
    # dataset_size - BATCH_SIZE が開始可能な最後のインデックス
    max_start_index = dataset_size - BATCH_SIZE
    if max_start_index < 0:
        max_start_index = 0 # データサイズがバッチサイズより小さい場合

    start_index = random.randint(0, max_start_index)

    # バッチサイズ分のインデックスを連続して抽出
    random_indices = list(range(start_index, start_index + BATCH_SIZE))

    # 選択されたインデックスのデータをデータセットから取得し、リストに格納
    batch_list = [train_loader.dataset[i] for i in random_indices]

    # 手動でバッチとして結合 (collate)
    # デフォルトの colate_fn を使用して、リスト形式のデータをテンソル形式のバッチに変換
    from torch.utils.data._utils.collate import default_collate
    sample_batch = default_collate(batch_list)

    print(f"\n--- インデックス指定によるランダム抽出 ---")
    print(f"抽出されたランダムな開始インデックス: {start_index}")
    print(f"抽出されたサンプルインデックス: {random_indices}")

    # 4. バッチをデバイスへ転送
    input_ids = sample_batch["input_ids"].to(device)
    labels = sample_batch["labels"].to(device)
    global_mask = None

    print(f"\n--- サンプルデータの情報 ---")
    print(f"バッチサイズ: {input_ids.shape[0]} (期待値: {BATCH_SIZE})")
    print(f"入力シーケンス形状: {input_ids.shape}")

    # 5. モデルによる推論実行
    try:
        logits, _ = model(input_ids, global_mask=global_mask, labels=labels)
    except Exception as e:
        print(f"Warning: Failed with labels. Trying inference without labels. Error: {e}")
        logits = model(input_ids, global_mask=global_mask)


    # 6. 推論結果の確認
    print(f"\n--- 推論結果 ---")
    print(f"Logits形状: {logits.shape}")

    predicted_ids = torch.argmax(logits, dim=-1)

    # 最初のサンプルだけ表示

    print(f"\n予測されたトークンID (最初のサンプル):")
    print(predicted_ids[sample_index].cpu().numpy())

    print(f"\n元の入力ID (最初のサンプル):")
    print(input_ids[sample_index].cpu().numpy())

    # ====================================================================
    # 【デコード処理】
    # ====================================================================

    # 1. 予測されたトークンIDをデコード
    predicted_tokens = predicted_ids[sample_index].tolist()
    decoded_prediction = tokenizer.decode(
        predicted_tokens,
        skip_special_tokens=True
    )

    print(f"\n--- デコードされた予測文章 ---")
    print(f"予測: {decoded_prediction}")

    # 2. 元の入力ID（マスクされた文章）をデコード
    input_tokens = input_ids[sample_index].tolist()
    decoded_input = tokenizer.decode(
        input_tokens,
        skip_special_tokens=False
    )

    # 3. 元のラベル（正解文章）をデコード (MLMの正解トークン)
    label_tokens = labels[sample_index].tolist()

    # -100 ではない有効なラベルのみを抽出
    decoded_labels = tokenizer.decode(
        [t for t in label_tokens if t != -100],
        skip_special_tokens=True
    )

    print(f"\n--- 元データとの比較 ---")
    print(f"元の入力 ([MASK]を含む): {decoded_input}")
    print(f"正解ラベル (マスクされた部分): {decoded_labels}")

def predict_mask(text, model, tokenizer, device, top_k=5): # (1) deviceを追加
    model.eval()
    model.to(device) # (2) モデルを指定デバイスに移動

    # テキストをトークン化
    inputs = tokenizer(text, return_tensors="pt")

    # (3) 入力テンソルを指定デバイスに移動
    input_ids = inputs["input_ids"].to(device)

    # マスクの位置を探す
    mask_token_id = tokenizer.mask_token_id
    # (4) torch.whereの出力（mask_indices）もinput_idsと同じデバイス上にあるはずです。
    mask_indices = torch.where(input_ids == mask_token_id)[1]

    if len(mask_indices) == 0:
        print("MASKトークンが見つかりませんでした。")
        return

    with torch.no_grad():
        # modelがGPU上にあり、input_idsもGPU上にあることを確認
        logits, _ = model(input_ids)
        # logitsもGPU上にあります

    # マスク位置の予測を取得
    for mask_idx in mask_indices:
        # mask_logitsはGPU上にあります
        mask_logits = logits[0, mask_idx, :]
        # top_k_idsもGPU上にあります
        top_k_ids = torch.topk(mask_logits, top_k).indices

        print(f"\nOriginal Text: {text}")
        # item() でCPUに取り出す
        print(f"Mask Position: {mask_idx.item()}")
        print("Predictions:")
        for rank, token_id in enumerate(top_k_ids):
            # token_idをCPUに移動してからdecodeに渡す（これは通常不要ですが、安全のため）
            token = tokenizer.decode([token_id.item()])
            print(f"  {rank+1}. {token}")


# --- デバイスの定義 ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")
# --------------------

# --- テスト実行 ---
# Qwenのトークナイザの場合、スペースの扱いに注意が必要ですが、
# シンプルな文で試します。
test_sentence = f"日本の首都は{tokenizer.mask_token}京です。"
# device引数を追加
predict_mask(test_sentence, model, tokenizer, device)

test_sentence_2 = f"フルーツのことを日本語でフルー{tokenizer.mask_token}と呼ぶ"
# device引数を追加
predict_mask(test_sentence_2, model, tokenizer, device)

