# -*- coding: utf-8 -*-
"""Alpha_Clip

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NyfF31QuV5S8jJvddZuSUPaH_kIUqYsM
"""

# Commented out IPython magic to ensure Python compatibility.
# Alpha-CLIPのリポジトリをクローン
!git clone https://github.com/SunzeY/AlphaCLIP.git
# %cd AlphaCLIP
!pip install -e . --no-build-isolation

!pip install loralib

import torch
import alpha_clip

device = "cuda" if torch.cuda.is_available() else "cpu"
checkpoint_path = "/content/clip_l14@336_grit1m_fultune_8xe.pth"

# 1. ベースモデル (ViT-L/14@336px) のロード
model, preprocess = alpha_clip.load("ViT-L/14@336px", device=device)

# 2. チェックポイントファイルの読み込み
checkpoint = torch.load(checkpoint_path, map_location="cpu")
state_dict = checkpoint["state_dict"] if isinstance(checkpoint, dict) and "state_dict" in checkpoint else checkpoint

# 3. model 全体ではなく「model.visual」に対して重みを適用
missing_keys, unexpected_keys = model.visual.load_state_dict(state_dict, strict=False)

model.eval()
model.to(device)

print("model.visual への Alpha-CLIP 重み適用に成功しました！")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!wget -o food.jpeg https://thumb.photo-ac.com/4c/4c1b3af925428f7d7dc877b2d709ef18_w.jpeg

import alpha_clip
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

from PIL import Image, ImageDraw
import torchvision.transforms as transforms
from torchvision.transforms import InterpolationMode

device = "cuda" if torch.cuda.is_available() else "cpu"
checkpoint_path = "/content/clip_l14@336_grit1m_fultune_8xe.pth"  # パスを確認してください

# ----------------------------------------------------------------------
# 1. モデルの構築 & Alpha-CLIP の重み（model.visual）適用
# ----------------------------------------------------------------------
model, preprocess = alpha_clip.load("ViT-L/14@336px", device=device)

checkpoint = torch.load(checkpoint_path, map_location="cpu")
state_dict = checkpoint["state_dict"] if isinstance(checkpoint, dict) and "state_dict" in checkpoint else checkpoint
model.visual.load_state_dict(state_dict, strict=False)

model.eval()
model.to(device)

# ----------------------------------------------------------------------
# 2. テスト用画像とアルファマスク（領域）の作成
# ----------------------------------------------------------------------
img_size = (500, 500)

# (A) テスト画像: グレー背景の中央に「赤い円」を描画
image = Image.new("RGB", img_size, color=(220, 220, 220))
draw = ImageDraw.Draw(image)
draw.ellipse([150, 150, 350, 350], fill=(230, 40, 40))  # 赤い円

# (B) アルファマスク: 赤い円がある場所だけを 255 (注目)、他を 0 (背景) に指定
alpha_mask = Image.new("L", img_size, 0)
mask_draw = ImageDraw.Draw(alpha_mask)
mask_draw.ellipse([150, 150, 350, 350], fill=255)

# ----------------------------------------------------------------------
# 3. 入力画像とアルファマスクの表示 (matplotlib)
# ----------------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(8, 4))

axes[0].imshow(image)
axes[0].set_title("Input Image")
axes[0].axis("off")

axes[1].imshow(alpha_mask, cmap="gray")
axes[1].set_title("Alpha Mask (ROI)")
axes[1].axis("off")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------------------
# 4. 前処理 (画像 & アルファマスク)
# ----------------------------------------------------------------------
image_tensor = preprocess(image).unsqueeze(0).to(device)

mask_transform = transforms.Compose([
    transforms.Resize((336, 336), interpolation=InterpolationMode.BICUBIC),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
alpha_tensor = mask_transform(alpha_mask).unsqueeze(0).to(device)

# ----------------------------------------------------------------------
# 5. テキストプロンプトの準備 & 特徴量抽出・類似度計算
# ----------------------------------------------------------------------
text_prompts = [
    "a photo of a red circle",
    "a photo of a blue square",
    "a photo of a green triangle",
    "a photo of a cat",
]
text_tokens = alpha_clip.tokenize(text_prompts).to(device)

with torch.no_grad():
    image_features = model.visual(image_tensor, alpha_tensor)
    text_features = model.encode_text(text_tokens)

    image_features = F.normalize(image_features, dim=-1)
    text_features = F.normalize(text_features, dim=-1)

    similarity = (image_features @ text_features.T).squeeze(0)

    logit_scale = model.logit_scale.exp()
    logits = logit_scale * similarity
    probs = logits.softmax(dim=-1)

# ----------------------------------------------------------------------
# 6. 結果の出力
# ----------------------------------------------------------------------
print("\n=== Alpha-CLIP 領域・テキスト類似度結果 ===")
for prompt, sim, prob in zip(text_prompts, similarity, probs):
    print(f"Prompt: '{prompt:30s}' | Cosine Sim: {sim.item():.4f} | Prob: {prob.item() * 100:.2f}%")

import alpha_clip
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

from PIL import Image, ImageDraw
import torchvision.transforms as transforms
from torchvision.transforms import InterpolationMode

device = "cuda" if torch.cuda.is_available() else "cpu"
checkpoint_path = "/content/clip_l14@336_grit1m_fultune_8xe.pth"  # パスを確認してください

# ----------------------------------------------------------------------
# 1. モデルの構築 & Alpha-CLIP の重み（model.visual）適用
# ----------------------------------------------------------------------
model, preprocess = alpha_clip.load("ViT-L/14@336px", device=device)

checkpoint = torch.load(checkpoint_path, map_location="cpu")
state_dict = checkpoint["state_dict"] if isinstance(checkpoint, dict) and "state_dict" in checkpoint else checkpoint
model.visual.load_state_dict(state_dict, strict=False)

model.eval()
model.to(device)

# ----------------------------------------------------------------------
# 2. テスト用画像とアルファマスク（領域）の作成
# ----------------------------------------------------------------------
img_size = (1000, 500)

# (A) テスト画像: グレー背景の中央に「赤い円」を描画
image = Image.open("/content/4c1b3af925428f7d7dc877b2d709ef18_w.jpeg")
# draw = ImageDraw.Draw(image)
# draw.ellipse([150, 150, 350, 350], fill=(230, 40, 40))  # 赤い円

# (B) アルファマスク: 赤い円がある場所だけを 255 (注目)、他を 0 (背景) に指定
alpha_mask = Image.new("L", img_size, 0)
mask_draw = ImageDraw.Draw(alpha_mask)
mask_draw.ellipse([150, 150, 350, 350], fill=255)

# ----------------------------------------------------------------------
# 3. 入力画像とアルファマスクの表示 (matplotlib)
# ----------------------------------------------------------------------
fig, axes = plt.subplots(1, 2, figsize=(8, 4))

axes[0].imshow(image)
axes[0].set_title("Input Image")
axes[0].axis("off")

axes[1].imshow(alpha_mask, cmap="gray")
axes[1].set_title("Alpha Mask (ROI)")
axes[1].axis("off")

plt.tight_layout()
plt.show()

# ----------------------------------------------------------------------
# 4. 前処理 (画像 & アルファマスク)
# ----------------------------------------------------------------------
image_tensor = preprocess(image).unsqueeze(0).to(device)

mask_transform = transforms.Compose([
    transforms.Resize((336, 336), interpolation=InterpolationMode.BICUBIC),
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))
])
alpha_tensor = mask_transform(alpha_mask).unsqueeze(0).to(device)

# ----------------------------------------------------------------------
# 5. テキストプロンプトの準備 & 特徴量抽出・類似度計算
# ----------------------------------------------------------------------
text_prompts = [
    "a photo of a red circle",
    "a photo of a food",
    "a photo of a green triangle",
    "a photo of a cat",
]
text_tokens = alpha_clip.tokenize(text_prompts).to(device)

with torch.no_grad():
    image_features = model.visual(image_tensor, alpha_tensor)
    text_features = model.encode_text(text_tokens)

    image_features = F.normalize(image_features, dim=-1)
    text_features = F.normalize(text_features, dim=-1)

    similarity = (image_features @ text_features.T).squeeze(0)

    logit_scale = model.logit_scale.exp()
    logits = logit_scale * similarity
    probs = logits.softmax(dim=-1)

# ----------------------------------------------------------------------
# 6. 結果の出力
# ----------------------------------------------------------------------
print("\n=== Alpha-CLIP 領域・テキスト類似度結果 ===")
for prompt, sim, prob in zip(text_prompts, similarity, probs):
    print(f"Prompt: '{prompt:30s}' | Cosine Sim: {sim.item():.4f} | Prob: {prob.item() * 100:.2f}%")

