# -*- coding: utf-8 -*-
"""graph_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SvHt6IJ7G9oxgJE5lkkLvqYqRl-laY_0
"""

!pip install japanize-matplotlib

import matplotlib.pyplot as plt
import networkx as nx

# グラフオブジェクトの作成（無向グラフ）
G = nx.Graph()

# ノードの追加（例：User, Station, Neuron）
G.add_node("User")
G.add_node("Station")
G.add_node("Neuron")

# 辺の追加（例：Route, Connection, Friend）
G.add_edge("User", "Station", label="Route")
G.add_edge("User", "Neuron", label="Connection")
G.add_edge("Station", "Neuron", label="Friend")

# 描画設定
pos = nx.spring_layout(G)  # ノードの配置を自動計算
plt.figure(figsize=(6, 6))

# ノードと辺を描画
nx.draw_networkx_nodes(G, pos, node_size=800, node_color="lightblue")
nx.draw_networkx_edges(G, pos, width=2, edge_color="gray")

# ノードラベル（ノード名）
nx.draw_networkx_labels(G, pos, font_size=12, font_weight="bold")

# 辺ラベル（辺の種類）
edge_labels = nx.get_edge_attributes(G, "label")
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=10)

# タイトルと軸の非表示
plt.title("Graph Visualization: Nodes and Edges", fontsize=14)
plt.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import random

# 無向グラフの作成
G = nx.Graph()

# ノード数を増やす（例：10ノード）
num_nodes = 10
for i in range(1, num_nodes + 1):
    G.add_node(f"User_{i}")

# 辺をランダムに追加（例：各ノードから2〜3本の辺）
for i in range(1, num_nodes + 1):
    # 各ノードから2〜3本の辺を追加
    num_edges_from_node = random.randint(2, 3)
    # 自分自身と重複を避けて接続先を選ぶ
    possible_targets = [j for j in range(1, num_nodes + 1) if j != i]
    targets = random.sample(possible_targets, min(num_edges_from_node, len(possible_targets)))
    for t in targets:
        # 既に辺がある場合は追加しない（無向なので片方だけ見ればよい）
        if not G.has_edge(f"User_{i}", f"User_{t}"):
            G.add_edge(f"User_{i}", f"User_{t}", label="Friend")

# 描画設定（サイズを大きくする）
pos = nx.spring_layout(G, seed=42)  # 再現性のためにseedを固定
plt.figure(figsize=(10, 8))

# ノードと辺を描画
nx.draw_networkx_nodes(G, pos, node_size=800, node_color="lightblue")
nx.draw_networkx_edges(G, pos, width=2, edge_color="gray")

# ノードラベル
nx.draw_networkx_labels(G, pos, font_size=10, font_weight="bold")

# 辺ラベル（多いと見づらいので、必要に応じてコメントアウト可）
edge_labels = nx.get_edge_attributes(G, "label")
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8)

# タイトルと軸の非表示
plt.title("Large Undirected Graph (Single Graph)", fontsize=16)
plt.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import random

# 有向グラフの作成
G = nx.DiGraph()

# ノード数を増やす（例：10ノード）
num_nodes = 10
for i in range(1, num_nodes + 1):
    G.add_node(f"User_{i}")

# 有向辺をランダムに追加（例：各ノードから1〜3本の有向辺）
for i in range(1, num_nodes + 1):
    # 各ノードから1〜3本の有向辺を追加
    num_edges_from_node = random.randint(1, 3)
    # 自分自身を除いた接続先候補
    possible_targets = [j for j in range(1, num_nodes + 1) if j != i]
    targets = random.sample(possible_targets, min(num_edges_from_node, len(possible_targets)))
    for t in targets:
        # 既に同じ向きの辺がある場合は追加しない
        if not G.has_edge(f"User_{i}", f"User_{t}"):
            G.add_edge(f"User_{i}", f"User_{t}", label="Follows")

# 描画設定（サイズを大きくする）
pos = nx.spring_layout(G, seed=42)  # 再現性のためにseedを固定
plt.figure(figsize=(10, 8))

# ノードと有向辺を描画（arrows=Trueで矢印を表示）
nx.draw_networkx_nodes(G, pos, node_size=800, node_color="lightblue")
nx.draw_networkx_edges(G, pos, width=2, edge_color="gray", arrows=True, arrowsize=20)

# ノードラベル
nx.draw_networkx_labels(G, pos, font_size=10, font_weight="bold")

# 辺ラベル（多いと見づらいので、必要に応じてコメントアウト可）
edge_labels = nx.get_edge_attributes(G, "label")
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=8)

# タイトルと軸の非表示
plt.title("Large Directed Graph (Single Graph)", fontsize=16)
plt.axis("off")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx

# 1. グラフの構築（ランダムグラフの生成、または手動での追加）
# ここでは10個のノードを持つランダムなグラフ（Erdős-Rényiモデル）を作成します
G = nx.erdos_renyi_graph(n=10, p=0.3, seed=42)

# ノード間の接続が担保されていない場合に備えて連結成分を確認
if not nx.is_connected(G):
    # 最大の連結成分を取得して再構築
    largest_cc = max(nx.connected_components(G), key=len)
    G = G.subgraph(largest_cc).copy()

# 2. パスを探すスタートとゴールのノードを指定
start_node = list(G.nodes())[0]
target_node = list(G.nodes())[-1]

# 最短パス（Shortest Path）の計算
path = nx.shortest_path(G, source=start_node, target=target_node)
print(f"探索されたパス: {path}")

# 3. パスに含まれるエッジ（辺）のリストを作成
path_edges = list(zip(path[:-1], path[1:]))

# 4. 可視化の設定
plt.figure(figsize=(8, 6))

# ノードの配置（レイアウト）を決める
pos = nx.spring_layout(G, seed=42)

# --- 基本のグラフを描画 ---
# 全体のノードを描画
nx.draw_networkx_nodes(G, pos, node_color="lightblue", node_size=700)
# 全体のエッジを描画
nx.draw_networkx_edges(G, pos, edge_color="gray", width=1.5, alpha=0.6)
# ノードのラベルを描画
nx.draw_networkx_labels(G, pos, font_size=12, font_family="sans-serif")

# --- パス（通過ルート）をハイライト描画 ---
# パス上のノードを強調
nx.draw_networkx_nodes(
    G, pos, nodelist=path, node_color="orange", node_size=800
)
# スタートとゴールをさらに強調
nx.draw_networkx_nodes(
    G, pos, nodelist=[start_node], node_color="green", node_size=900
)
nx.draw_networkx_nodes(
    G, pos, nodelist=[target_node], node_color="red", node_size=900
)

# パス上のエッジを強調
nx.draw_networkx_edges(
    G, pos, edgelist=path_edges, edge_color="red", width=3.5
)

# 凡例・タイトルの設定
plt.title(
    f"Graph Path Visualization ({start_node} -> {target_node})", fontsize=14
)
plt.axis("off")  # 軸を非表示にする
plt.tight_layout()

# 表示
plt.show()

import matplotlib.pyplot as plt
import networkx as nx

# 1. 配送ネットワーク（グラフ）の構築
G = nx.Graph()

# 拠店（ノード）とルート（エッジ）の定義
edges = [
    ("Tokyo", "Saitama"),
    ("Saitama", "Gunma"),
    ("Gunma", "Tochigi"),
    ("Tochigi", "Ibaraki"),
    ("Ibaraki", "Saitama"),  # ここでサイクルが形成される (Saitama-Gunma-Tochigi-Ibaraki-Saitama)
    ("Tokyo", "Chiba"),
    ("Chiba", "Ibaraki"),  # ここでも別のサイクルが形成される
    ("Tokyo", "Kanagawa"),  # サイクルに含まれない枝ルート
]

G.add_edges_from(edges)

# 2. サイクル（閉路）の検出
# nx.cycle_basis は無向グラフの基底サイクル（最小単位のサイクルの組）を返します
cycles = nx.cycle_basis(G)

print(f"検出されたサイクルの数: {len(cycles)}")
for i, c in enumerate(cycles):
    # 見やすさのために先頭のノードを末尾にも追加して表示 (例: A -> B -> C -> A)
    cycle_path = c + [c[0]]
    print(f"  サイクル {i + 1}: {' -> '.join(cycle_path)}")

# 可視化対象とするサイクルを1つ選択（ここでは最初のサイクル）
target_cycle = cycles[0] if cycles else []

# サイクルに含まれるエッジ（辺）のペアリストを作成
cycle_edges = []
if target_cycle:
    cycle_nodes_seq = target_cycle + [target_cycle[0]]
    cycle_edges = list(zip(cycle_nodes_seq[:-1], cycle_nodes_seq[1:]))

# 3. 可視化の設定
plt.figure(figsize=(9, 7))

# レイアウトの固定（表示の再現性を保つためにseedを設定）
pos = nx.spring_layout(G, seed=15)

# --- A. 背景となる全体のグラフを描画 ---
# 通常のノード
nx.draw_networkx_nodes(
    G, pos, node_color="#E0E0E0", node_size=1200, edgecolors="gray"
)
# 通常のエッジ
nx.draw_networkx_edges(
    G, pos, edge_color="#B0B0B0", width=1.5, style="dashed"
)
# ノードラベル（拠点名）
nx.draw_networkx_labels(
    G, pos, font_size=10, font_family="sans-serif", font_weight="bold"
)

# --- B. 検出されたサイクルを強烈にハイライト ---
if target_cycle:
    # サイクルを構成するノードを強調（鮮やかなオレンジ）
    nx.draw_networkx_nodes(
        G,
        pos,
        nodelist=target_cycle,
        node_color="#FF9800",
        node_size=1400,
        edgecolors="#E65100",
        linewidths=2,
    )

    # サイクルを構成するエッジを強調（太い赤線）
    nx.draw_networkx_edges(
        G, pos, edgelist=cycle_edges, edge_color="#D32F2F", width=4.0
    )

# グラフタイトル・描画設定
plt.title(
    "Delivery Network: Cycle Detection Visualization",
    fontsize=14,
    pad=15,
)
plt.axis("off")
plt.tight_layout()

plt.show()

import networkx as nx
import matplotlib.pyplot as plt
from networkx.drawing.nx_pydot import graphviz_layout

def visualize_tree_structure():
    # 1. 木（Tree）グラフの構築
    # ここでは手動でエッジを追加して、シンプルな木を作成します。
    # 木の定義：連結でサイクルがないグラフ。
    G = nx.Graph()

    # エッジのリスト (親, 子)
    # 根（Root）を 'Root' とします。
    tree_edges = [
        ('Root', 'Child A'),
        ('Root', 'Child B'),
        ('Root', 'Child C'),
        ('Child A', 'Leaf A1'),
        ('Child A', 'Leaf A2'),
        ('Child B', 'Leaf B1'),
        ('Child C', 'Leaf C1'),
        ('Child C', 'Leaf C2'),
        ('Child C', 'Leaf C3'),
        ('Leaf A2', 'Sub-Leaf A2-1') # さらに深く
    ]
    G.add_edges_from(tree_edges)

    # 木であることを確認（デバッグ用）
    if not nx.is_tree(G):
        print("警告: 作成されたグラフは木ではありません。")
        return

    # 2. 階層型レイアウトの計算
    # Graphvizの 'dot' レイアウトエンジンを使用して、親から子へのきれいな階層を計算します。
    # ※この機能を使用するには、システムにGraphviz本体のインストールが必要です。
    try:
        # root引数で根ノードを指定すると、そこを起点に階層化されます。
        pos = graphviz_layout(G, prog='dot', root='Root')
    except ImportError:
        print("エラー: pydot または Graphviz が見つかりません。")
        print("通常のspringレイアウトで代用しますが、階層にはなりません。")
        pos = nx.spring_layout(G) # 代替案

    # 3. 可視化の設定
    plt.figure(figsize=(12, 8))

    # ノードの種類ごとに色を変えるためのリスト作成
    node_colors = []
    for node in G.nodes():
        if node == 'Root':
            node_colors.append('#FF5722') # 根：鮮やかなオレンジ
        elif G.degree(node) == 1 and node != 'Root':
            node_colors.append('#8BC34A') # 葉（末端）：黄緑
        else:
            node_colors.append('#03A9F4') # 中間ノード：水色

    # --- 描画 ---
    # エッジ（辺）の描画
    nx.draw_networkx_edges(G, pos, edge_color='#BDBDBD', width=2)

    # ノード（頂点）の描画
    nx.draw_networkx_nodes(
        G, pos,
        node_color=node_colors,
        node_size=2000,
        edgecolors='white', # ノードの枠線
        linewidths=2,
        alpha=0.9
    )

    # ラベル（ノード名）の描画
    nx.draw_networkx_labels(
        G, pos,
        font_size=10,
        font_family='sans-serif',
        font_weight='bold'
    )

    # 全体の設定
    plt.title("Tree Structure Visualization (Graphviz DOT Layout)", fontsize=16)
    plt.axis('off') # 軸を非表示
    plt.tight_layout()

    # 表示
    plt.show()

# 関数を実行
if __name__ == "__main__":
    visualize_tree_structure()

import matplotlib.pyplot as plt
import networkx as nx

# 1. グラフの構築（講義間の重複関係）
G = nx.Graph()

# 講義ノードの追加
courses = ["Course A", "Course B", "Course C", "Course D", "Course E"]
G.add_nodes_from(courses)

# 受講生が重複している講義間にエッジを張る
conflicts = [
    ("Course A", "Course B"),
    ("Course A", "Course C"),
    ("Course A", "Course D"),
    ("Course B", "Course C"),
    ("Course C", "Course D"),
    ("Course D", "Course E"),
]
G.add_edges_from(conflicts)

# 2. 貪欲法（Greedy Algorithm）による彩色と彩色数の算出
# DSATUR戦略などを使用することで、適切な彩色を試みます
coloring = nx.greedy_color(G, strategy="largest_first")

# 使用された色の種類数（＝彩色数 \chi(G)）
chromatic_number = max(coloring.values()) + 1

print(f"算出された彩色数 (Chromatic Number): {chromatic_number}")
print("各ノードの割り当て（色ID）:")
for node, color_id in sorted(coloring.items()):
    print(f"  - {node}: タイムスロット {color_id + 1}")

# 3. 可視化の準備
# カラーマップを設定（色IDを実際のHTMLカラーコードにマッピング）
palette = ["#FF5722", "#4CAF50", "#2196F3", "#FFEB3B", "#9C27B0"]
node_colors = [palette[coloring[node] % len(palette)] for node in G.nodes()]

# 4. グラフの描画
plt.figure(figsize=(9, 7))

# レイアウトの計算
pos = nx.spring_layout(G, seed=42)

# エッジ（競合関係）の描画
nx.draw_networkx_edges(G, pos, edge_color="gray", width=2, alpha=0.7)

# ノード（講義）の描画（彩色結果に基づいた色をセット）
nx.draw_networkx_nodes(
    G,
    pos,
    node_color=node_colors,
    node_size=2000,
    edgecolors="black",
    linewidths=1.5,
)

# ノードラベルの描画
nx.draw_networkx_labels(
    G, pos, font_size=11, font_family="sans-serif", font_weight="bold"
)

# タイトルと説明の描画
plt.title(
    f"Graph Coloring Example (Chromatic Number $\\chi(G)$ = {chromatic_number})",
    fontsize=14,
    pad=15,
)
plt.axis("off")
plt.tight_layout()

# 表示
plt.show()

import matplotlib.pyplot as plt
import networkx as nx

# 1. 二部グラフの構築
G = nx.Graph()

# ノードの定義 (エンジニアグループ と タスクグループ)
engineers = ["Alice", "Bob", "Charlie", "David"]
tasks = ["Task 1", "Task 2", "Task 3", "Task 4"]

# ノードを追加（bipartite属性を設定して左右のグループを区別）
G.add_nodes_from(engineers, bipartite=0)
G.add_nodes_from(tasks, bipartite=1)

# 適性・割り当て可能な候補ペア（エッジ）を追加
possible_edges = [
    ("Alice", "Task 1"),
    ("Alice", "Task 2"),
    ("Bob", "Task 2"),
    ("Bob", "Task 3"),
    ("Charlie", "Task 1"),
    ("Charlie", "Task 3"),
    ("David", "Task 3"),
]
G.add_edges_from(possible_edges)

# 2. 最大マッチング（Maximum Matching）の計算
# Hopcroft-Karp アルゴリズムなどで最大数を求めます
matching = nx.bipartite.maximum_matching(G, top_nodes=engineers)

# マッチング結果から重複を除いたエッジペアを抽出
matched_edges = [
    (u, v) for u, v in matching.items() if u in engineers
]  # 片方向のみ抽出
num_matches = len(matched_edges)

print(f"最大マッチング数 (Maximum Matching Size): {num_matches}")
print("確定した割り当てペア:")
for eng, task in matched_edges:
    print(f"  - {eng}  <--->  {task}")

# 3. 可視化の設定
plt.figure(figsize=(10, 7))

# 二部グラフ用の左右配置レイアウト（bipartite_layout）
pos = nx.bipartite_layout(G, engineers)

# --- A. 全体の描画（背景） ---
# ノード描画（エンジニア: 水色, タスク: オレンジ）
nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=engineers,
    node_color="#4FC3F7",
    node_size=2000,
    edgecolors="black",
)
nx.draw_networkx_nodes(
    G,
    pos,
    nodelist=tasks,
    node_color="#FFB74D",
    node_size=2000,
    edgecolors="black",
)

# 候補エッジの描画（グレーの点線）
nx.draw_networkx_edges(
    G, pos, edgelist=possible_edges, edge_color="gray", style="dashed", width=1.5
)

# ラベル描画
nx.draw_networkx_labels(
    G, pos, font_size=11, font_family="sans-serif", font_weight="bold"
)

# --- B. マッチング成功ペア（エッジ）のハイライト ---
nx.draw_networkx_edges(
    G, pos, edgelist=matched_edges, edge_color="#E53935", width=4.0
)

# 4. タイトルと表示設定
plt.title(
    f"Bipartite Matching Example: Job Assignment (Max Matches = {num_matches})",
    fontsize=14,
    pad=15,
)
plt.axis("off")
plt.tight_layout()

# 表示
plt.show()

import matplotlib.pyplot as plt
import networkx as nx

# 1. 有向グラフ（DiGraph）の構築
G = nx.DiGraph()

# ノード定義
# Source (S): 西日本データセンター
# Sink (T)  : 東日本データセンター
# A, B, C, D: 中継サーバ
nodes = ["Source", "Node_A", "Node_B", "Node_C", "Node_D", "Sink"]
G.add_nodes_from(nodes)

# エッジ（通信回線）と容量（Capacity: Gbps）の追加
# (送信元, 送信先, 容量)
capacities = [
    ("Source", "Node_A", 10),
    ("Source", "Node_B", 8),
    ("Node_A", "Node_B", 5),
    ("Node_A", "Node_C", 7),
    ("Node_B", "Node_D", 10),
    ("Node_C", "Node_B", 4),
    ("Node_C", "Sink", 8),
    ("Node_D", "Node_C", 3),
    ("Node_D", "Sink", 9),
]

for u, v, cap in capacities:
    G.add_edge(u, v, capacity=cap)

# 2. 最大フロー（Maximum Flow）の計算
# Edmonds-Karp アルゴリズム等を用いて計算されます
flow_value, flow_dict = nx.maximum_flow(G, "Source", "Sink")

print(f"==========================================")
print(f"最大フロー量 (Max Flow Value): {flow_value} Gbps")
print(f"==========================================")
print("各回線ごとの転送データ量 (フロー量 / 容量):")
for u in flow_dict:
    for v, flow in flow_dict[u].items():
        if flow > 0:
            cap = G[u][v]["capacity"]
            print(f"  - {u} -> {v}: {flow} / {cap} Gbps")

# 3. 可視化の準備
plt.figure(figsize=(11, 7))

# 階層的な配置にするためレイアウトを固定（左から右へ流れるイメージ）
pos = {
    "Source": (0, 1),
    "Node_A": (1, 2),
    "Node_B": (1, 0),
    "Node_C": (2, 2),
    "Node_D": (2, 0),
    "Sink": (3, 1),
}

# エッジごとの描画属性を作成
active_edges = []
inactive_edges = []
edge_labels = {}
edge_widths = []

for u, v, data in G.edges(data=True):
    cap = data["capacity"]
    flow = flow_dict[u][v]
    edge_labels[(u, v)] = f"{flow}/{cap}"  # ラベル表示（フロー量/容量）

    if flow > 0:
        active_edges.append((u, v))
    else:
        inactive_edges.append((u, v))

# 4. 描画処理
# --- A. ノードの描画 ---
# Source/Sink と 中継ノードで色を分ける
node_colors = []
for node in G.nodes():
    if node == "Source":
        node_colors.append("#4CAF50")  # スタート: 緑
    elif node == "Sink":
        node_colors.append("#E53935")  # ゴール: 赤
    else:
        node_colors.append("#2196F3")  # 中継: 青

nx.draw_networkx_nodes(
    G,
    pos,
    node_color=node_colors,
    node_size=2500,
    edgecolors="black",
    linewidths=1.5,
)
nx.draw_networkx_labels(
    G, pos, font_size=10, font_family="sans-serif", font_weight="bold"
)

# --- B. エッジ（回線）の描画 ---
# フローが流れていない回線（グレーの破線）
nx.draw_networkx_edges(
    G,
    pos,
    edgelist=inactive_edges,
    edge_color="#BDBDBD",
    style="dashed",
    width=1.5,
    arrowsize=15,
)

# フローが流れている回線（太い青実線）
# 実際に流れているフロー量に応じて線を少し太くします
for u, v in active_edges:
    flow = flow_dict[u][v]
    nx.draw_networkx_edges(
        G,
        pos,
        edgelist=[(u, v)],
        edge_color="#1E88E5",
        width=2.0 + (flow * 0.4),  # フロー量に応じた太さ
        arrowsize=20,
    )

# --- C. エッジラベル（フロー量/容量）の描画 ---
nx.draw_networkx_edge_labels(
    G,
    pos,
    edge_labels=edge_labels,
    font_color="#1A237E",
    font_size=11,
    font_weight="bold",
    bbox=dict(boxstyle="round,pad=0.2", fc="white", ec="none", alpha=0.8),
)

# 5. タイトルと表示
plt.title(
    f"Network Max Flow Visualization (Total Max Flow = {flow_value} Gbps)\n"
    f"Label format on edges: [ Actual Flow / Capacity ]",
    fontsize=13,
    pad=15,
)
plt.axis("off")
plt.tight_layout()

# 表示
plt.show()

import matplotlib.pyplot as plt
import networkx as nx


def analyze_and_draw_circuit(G, title):
    # 1. 平面グラフ判定（Planarity Check）
    is_planar, P = nx.check_planarity(G)

    print(f"--- {title} ---")
    print(f"平面グラフですか？ : {'はい (1層配線可能)' if is_planar else 'いいえ (多層化が必要)'}")

    # 2. 描画の設定
    plt.figure(figsize=(7, 6))

    if is_planar:
        # 平面グラフの場合：エッジが絶対に交差しないレイアウトを自動計算
        pos = nx.planar_layout(G)
        edge_color = "#2E7D32"  # 成功：緑色
        status_text = "Planar Graph (No Edge Crossings)"
    else:
        # 非平面グラフの場合：通常のレイアウト（交差が発生する）
        pos = nx.spring_layout(G, seed=42)
        edge_color = "#C62828"  # 失敗：赤色
        status_text = "Non-Planar Graph (Edge Crossings Exist)"

    # 3. 可視化
    # ノード（部品）の描画
    nx.draw_networkx_nodes(
        G,
        pos,
        node_color="#2196F3",
        node_size=1800,
        edgecolors="black",
        linewidths=1.5,
    )

    # エッジ（配線）の描画
    nx.draw_networkx_edges(G, pos, edge_color=edge_color, width=2.5, alpha=0.8)

    # ラベルの描画
    nx.draw_networkx_labels(
        G, pos, font_size=12, font_color="white", font_weight="bold"
    )

    # タイトル
    plt.title(f"{title}\nStatus: {status_text}", fontsize=12, pad=12)
    plt.axis("off")
    plt.tight_layout()
    plt.show()


# ==========================================
# 実行部分
# ==========================================

# ケースA: 平面グラフになる回路（5ノードの車輪グラフ Wheel Graph）
G_planar = nx.wheel_graph(5)
# ノード名をわかりやすく変更
G_planar = nx.relabel_nodes(
    G_planar, {0: "Center", 1: "P1", 2: "P2", 3: "P3", 4: "P4"}
)
analyze_and_draw_circuit(G_planar, "Case A: Standard Circuit")

# ケースB: 非平面グラフになる回路（5ノードの完全グラフ K5）
G_non_planar = nx.complete_graph(5)
analyze_and_draw_circuit(G_non_planar, "Case B: Fully Connected (K5) Circuit")

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 隣接行列の定義 (4x4)
# A:0, B:1, C:2, D:3
M = np.array(
    [
        [0, 1, 1, 0],  # A
        [0, 0, 1, 0],  # B
        [1, 0, 0, 1],  # C
        [0, 0, 0, 0],  # D
    ]
)

print("--- 隣接行列 M ---")
print(M)

# 2. 行列の2乗を計算 (長さ2のパスを検出)
M_squared = np.linalg.matrix_power(M, 2)
print("\n--- 隣接行列の2乗 M^2 ---")
print(M_squared)
print(
    f"\nAからDへの長さ2のパスの数 (M^2[0, 3]): {M_squared[0, 3]}"
)  # 1が表示される

# 3. NetworkXで有向グラフ化して可視化
labels = {0: "A", 1: "B", 2: "C", 3: "D"}
G = nx.from_numpy_array(M, create_using=nx.DiGraph)
G = nx.relabel_nodes(G, labels)

plt.figure(figsize=(7, 6))
pos = nx.spring_layout(G, seed=7)

# ノードとエッジの描画
nx.draw_networkx_nodes(
    G, pos, node_color="#4CAF50", node_size=1600, edgecolors="black"
)
nx.draw_networkx_edges(
    G, pos, edge_color="gray", width=2, arrowsize=20, connectionstyle="arc3,rad=0.1"
)
nx.draw_networkx_labels(
    G, pos, font_size=12, font_color="white", font_weight="bold"
)

plt.title("SNS Follow Network (Directed Graph)", fontsize=14, pad=12)
plt.axis("off")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. グラフの構築（無向グラフ）
G = nx.Graph()
edges = [("R1", "R2"), ("R1", "R3"), ("R2", "R3"), ("R2", "R4")]
G.add_edges_from(edges)

# ノード順序の固定
nodes = ["R1", "R2", "R3", "R4"]

# 2. 隣接行列 A と 次数行列 D の計算
A = nx.to_numpy_array(G, nodelist=nodes)

# 次数（各ノードの接続数）を計算し、対角行列化する
degrees = [G.degree(n) for n in nodes]
D = np.diag(degrees)

# グラフラプラシアン L = D - A
L = D - A

print("--- 次数配列 ---")
for n, deg in zip(nodes, degrees):
    print(f"  {n}: {deg}")

print("\n--- 次数行列 D ---")
print(D)

print("\n--- グラフラプラシアン L (D - A) ---")
print(L)

# 3. 可視化
plt.figure(figsize=(7, 6))
pos = nx.spring_layout(G, seed=42)

# ノードのサイズを次数に応じて大きくする（次数の可視化）
node_sizes = [deg * 1000 for deg in degrees]

nx.draw_networkx_nodes(
    G,
    pos,
    node_color="#FF9800",
    node_size=node_sizes,
    edgecolors="black",
    linewidths=1.5,
)
nx.draw_networkx_edges(G, pos, edge_color="gray", width=2)
nx.draw_networkx_labels(
    G, pos, font_size=12, font_color="white", font_weight="bold"
)

plt.title("Router Network (Node size proportional to Degree)", fontsize=13)
plt.axis("off")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from scipy.integrate import solve_ivp

# 1. 3ノードのライングラフの作成
G = nx.path_graph(3)

# 2. ラプラシアン行列 L の計算
# NetworkX の laplacian_matrix は sparse matrix を返すため numpy array に変換
L = nx.laplacian_matrix(G).toarray()
print("--- ラプラシアン行列 L ---")
print(L)

# 3. 熱拡散の微分方程式 ( df/dt = -L * f )
def heat_diffusion(t, f):
    return -L @ f

# 初期状態: f(0) = [100, 0, 0]
f0 = [100.0, 0.0, 0.0]
t_span = (0, 5)  # 時刻 t=0 から t=5 まで
t_eval = np.linspace(0, 5, 200)

# 微分方程式の数値解法
sol = solve_ivp(heat_diffusion, t_span, f0, t_eval=t_eval)

# 4. 可視化: 時間変化プロット
plt.figure(figsize=(10, 5))

plt.subplot(1, 2, 1)
pos = {0: (0, 0), 1: (1, 0), 2: (2, 0)}
nx.draw_networkx_nodes(G, pos, node_color="#4CAF50", node_size=1200)
nx.draw_networkx_edges(G, pos, width=2)
nx.draw_networkx_labels(
    G, pos, labels={0: "Node 0\n(100)", 1: "Node 1\n(0)", 2: "Node 2\n(0)"}, font_weight="bold"
)
plt.title("Initial Graph State (t = 0)")
plt.axis("off")

plt.subplot(1, 2, 2)
for i in range(3):
    plt.plot(sol.t, sol.y[i], label=f"Node {i}", linewidth=2.5)

plt.axhline(100 / 3, color="gray", linestyle="--", alpha=0.7, label="Equilibrium (33.3)")
plt.xlabel("Time $t$")
plt.ylabel("Temperature / State Value")
plt.title("Heat Diffusion over Graph (df/dt = -L * f)")
plt.grid(True, linestyle=":", alpha=0.6)
plt.legend()

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 無向グラフの構築
G = nx.Graph()

# ノードの追加
nodes = ["A", "B", "C", "D"]
G.add_nodes_from(nodes)

# エッジとラベル（e1〜e5）の定義
edges_with_labels = [
    ("A", "B", "e1"),
    ("B", "C", "e2"),
    ("C", "D", "e3"),
    ("D", "A", "e4"),
    ("A", "C", "e5"),  # バイパス
]

for u, v, label in edges_with_labels:
    G.add_edge(u, v, key=label)

# 2. 接続行列（Incidence Matrix）の取得
# (NetworkX の incidence_matrix は scipy sparse matrix を返すため toarray() で変換)
B = nx.incidence_matrix(G, nodelist=nodes, oriented=False).toarray().astype(int)

print("--- ノード一覧 ---")
print(nodes)

print("\n--- エッジ一覧 ---")
edge_list = [f"{u}-{v} ({data['key']})" for u, v, data in G.edges(data=True)]
print(edge_list)

print("\n--- 無向接続行列 B (Nodes x Edges) ---")
print(B)

print("\n--- B * B^T (D + A) ---")
print(B @ B.T)

# 3. 可視化処理
plt.figure(figsize=(8, 7))

# ノード配置の決定
pos = {
    "A": (0, 1),
    "B": (1, 1),
    "C": (1, 0),
    "D": (0, 0),
}

# ノードの描画
nx.draw_networkx_nodes(
    G, pos, node_color="#9C27B0", node_size=1800, edgecolors="black", linewidths=1.5
)
nx.draw_networkx_labels(
    G, pos, font_size=12, font_color="white", font_weight="bold"
)

# エッジの描画
nx.draw_networkx_edges(G, pos, edge_color="gray", width=2.5)

# エッジラベル（e1〜e5）の描画
edge_labels = {(u, v): data["key"] for u, v, data in G.edges(data=True)}
nx.draw_networkx_edge_labels(
    G,
    pos,
    edge_labels=edge_labels,
    font_color="#D81B60",
    font_size=12,
    font_weight="bold",
    bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="gray", alpha=0.9),
)

plt.title("Incidence Matrix Example (Nodes: A-D, Edges: e1-e5)", fontsize=13, pad=15)
plt.axis("off")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 2つのグループと1つの橋を持つグラフの構築
G = nx.Graph()

# グループA (0, 1, 2) の完全グラフ
edges_A = [(0, 1), (1, 2), (2, 0)]
# グループB (3, 4, 5) の完全グラフ
edges_B = [(3, 4), (4, 5), (5, 3)]
# 2つのグループを繋ぐ橋
bridge = [(2, 3)]

G.add_edges_from(edges_A + edges_B + bridge)

# 2. ラプラシアン行列 L の作成と固有値分解
L = nx.laplacian_matrix(G).toarray()

# 固有値・固有ベクトルの計算 (エルミート/実対称行列用)
eigenvalues, eigenvectors = np.linalg.eigh(L)

print("--- ラプラシアン行列 L ---")
print(L)

print("\n--- 固有値 (昇順) ---")
for i, val in enumerate(eigenvalues):
    print(f"  μ_{i+1}: {val:.4f}")

# 第2固有ベクトル (Fiedler Vector)
fiedler_vector = eigenvectors[:, 1]
print("\n--- 第2固有ベクトル v_2 (Fiedler Vector) ---")
for node_idx, val in enumerate(fiedler_vector):
    print(f"  Node {node_idx}: {val: .4f}")

# 3. 可視化：第2固有ベクトルの符号でグループ分け
# 負の値を青、正の値を赤に色分け
node_colors = ["#2196F3" if val < 0 else "#FF5722" for val in fiedler_vector]

plt.figure(figsize=(9, 5))

# 2グループが分かりやすい固定配置
pos = {
    0: (0, 1),
    1: (0.8, 0.5),
    2: (0, 0),  # Group A
    3: (2, 0),
    4: (1.2, 0.5),
    5: (2, 1),  # Group B
}

# ノードの描画 (サイズと色は Fiedler ベクトルに基づく)
nx.draw_networkx_nodes(
    G, pos, node_color=node_colors, node_size=1500, edgecolors="black"
)

# エッジの描画 (橋の部分を強調)
edge_colors = [
    "red" if (u == 2 and v == 3) or (u == 3 and v == 2) else "gray"
    for u, v in G.edges()
]
edge_widths = [
    3.0 if (u == 2 and v == 3) or (u == 3 and v == 2) else 1.5
    for u, v in G.edges()
]

nx.draw_networkx_edges(G, pos, edge_color=edge_colors, width=edge_widths)

# ラベル描画（ノード番号と Fiedler ベクトルの値）
labels = {i: f"N{i}\n({fiedler_vector[i]:.2f})" for i in G.nodes()}
nx.draw_networkx_labels(
    G, pos, labels=labels, font_size=9, font_color="white", font_weight="bold"
)

plt.title(
    f"Spectral Clustering using Fiedler Vector (μ_2 = {eigenvalues[1]:.3f})",
    fontsize=13,
    pad=15,
)
plt.axis("off")
plt.tight_layout()

plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. グラフの構築
G = nx.Graph()
edges = [("A", "B"), ("A", "C"), ("B", "C"), ("B", "D")]
G.add_edges_from(edges)

nodes = ["A", "B", "C", "D"]

# 2. 隣接行列 A の取得
A = nx.to_numpy_array(G, nodelist=nodes, dtype=int)

print("--- 隣接行列 A (長さ 1 のパス数) ---")
print(A)

# 3. 行列の累乗 A^2, A^3 の計算
A_2 = np.linalg.matrix_power(A, 2)
A_3 = np.linalg.matrix_power(A, 3)

print("\n--- A^2 (長さ 2 のパス数) ---")
print(A_2)

print("\n--- A^3 (長さ 3 のパス数) ---")
print(A_3)

print(f"\n[注目] A から D への長さ 3 のパス数: {A_3[0, 3]} 通り")
# (例: A->B->C->B->D, A->C->B->A.. などを含めたステップ数3の経路)

# 4. 可視化
plt.figure(figsize=(6, 5))
pos = {"A": (0, 1), "B": (1, 0), "C": (0, 0), "D": (2, 0)}

nx.draw_networkx_nodes(
    G, pos, node_color="#4CAF50", node_size=1200, edgecolors="black"
)
nx.draw_networkx_edges(G, pos, width=2, edge_color="gray")
nx.draw_networkx_labels(
    G, pos, font_size=12, font_color="white", font_weight="bold"
)

plt.title("Graph for Matrix Power & Path Counting", fontsize=12)
plt.axis("off")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 遷移確率行列 M の定義
M = np.array([[0.0, 0.0, 1.0], [0.5, 0.0, 0.0], [0.5, 1.0, 0.0]])

print("--- 遷移確率行列 M ---")
print(M)

# 2. 解法A: 固有値分解による解法 (M * r = 1 * r)
eigenvalues, eigenvectors = np.linalg.eig(M)

# 固有値 1 に対応するインデックスを取得 (実部がほぼ1のもの)
idx = np.argmin(np.abs(eigenvalues - 1.0))
r_eigen = np.real(eigenvectors[:, idx])

# 総和が 1 になるように正規化
r_eigen = r_eigen / np.sum(r_eigen)

print("\n--- 解法A: 固有値分解による PageRank r ---")
print(f"r_A: {r_eigen[0]:.4f}, r_B: {r_eigen[1]:.4f}, r_C: {r_eigen[2]:.4f}")


# 3. 解法B: べき乗法 (Power Iteration) によるシミュレーション
# 均等な初期確率分布 r0 = [1/3, 1/3, 1/3] からスタート
r_k = np.array([1 / 3, 1 / 3, 1 / 3])
history = [r_k.copy()]

# 行列の積を 20 回繰り返して収束を見る
for _ in range(20):
    r_k = M @ r_k
    history.append(r_k.copy())

history = np.array(history)

print("\n--- 解法B: べき乗法で20ステップ更新後の PageRank r ---")
print(f"r_A: {r_k[0]:.4f}, r_B: {r_k[1]:.4f}, r_C: {r_k[2]:.4f}")


# 4. 可視化
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# グラフ構造の可視化
G = nx.DiGraph()
G.add_edge("A", "B", weight=0.5)
G.add_edge("A", "C", weight=0.5)
G.add_edge("B", "C", weight=1.0)
G.add_edge("C", "A", weight=1.0)

pos = {"A": (0, 1), "B": (1, 1), "C": (0.5, 0)}

# ノードサイズを計算した PageRank (r) に比例させる
node_sizes = [r_eigen[0] * 5000, r_eigen[1] * 5000, r_eigen[2] * 5000]

nx.draw_networkx_nodes(
    G,
    pos,
    ax=ax1,
    node_color="#2196F3",
    node_size=node_sizes,
    edgecolors="black",
)
nx.draw_networkx_labels(
    G, pos, ax=ax1, font_color="white", font_weight="bold", font_size=14
)
nx.draw_networkx_edges(
    G,
    pos,
    ax=ax1,
    connectionstyle="arc3,rad=0.1",
    arrowsize=20,
    edge_color="gray",
    width=2,
)

ax1.set_title("Web Page Network (Node size = PageRank)", fontsize=12)
ax1.axis("off")

# 確率分布の収束プロット
steps = np.arange(len(history))
ax2.plot(steps, history[:, 0], "o-", label="Page A (0.4)", color="#E91E63")
ax2.plot(steps, history[:, 1], "s-", label="Page B (0.2)", color="#4CAF50")
ax2.plot(steps, history[:, 2], "^-", label="Page C (0.4)", color="#2196F3")

ax2.set_xlabel("Iteration Step $k$")
ax2.set_ylabel("Probability $r(k)$")
ax2.set_title("Power Iteration Convergence: $r^{(k+1)} = M r^{(k)}$")
ax2.grid(True, linestyle=":", alpha=0.6)
ax2.legend()

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx

# 1. グラフの構築
G = nx.Graph()
edges = [("A", "B"), ("A", "C"), ("B", "C"), ("B", "D"), ("D", "E")]
G.add_edges_from(edges)

# 2. 全ノード間の最短経路長行列の計算
all_shortest_paths = dict(nx.all_pairs_shortest_path_length(G))

print("--- 全ノード間の最短距離 (Shortest Path Lengths) ---")
for src in G.nodes():
    print(f"Node {src}: {all_shortest_paths[src]}")

# 3. グラフの直径 (Diameter) の取得
diameter = nx.diameter(G)
print(f"\n[結果] グラフの直径 (Diameter): {diameter}")

# 4. 直径を与える最遠ノード対とその最短経路を取得
# 例として (A, E) の最短経路を取得
longest_path = nx.shortest_path(G, source="A", target="E")
print(f"[最遠パス (A -> E)]: {' -> '.join(longest_path)} (長さ: {len(longest_path) - 1})")

# 5. 可視化
plt.figure(figsize=(8, 5))
pos = {"A": (0, 1), "C": (0, 0), "B": (1, 0.5), "D": (2, 0.5), "E": (3, 0.5)}

# ノードの色分け (最遠ノード A と E を赤色に)
node_colors = [
    "#FF5722" if node in ["A", "E"] else "#2196F3" for node in G.nodes()
]

# 最遠パスに含まれるエッジを太線・赤色で強調
path_edges = list(zip(longest_path[:-1], longest_path[1:]))
edge_colors = ["red" if edge in path_edges or edge[::-1] in path_edges else "gray" for edge in G.edges()]
edge_widths = [3.5 if edge in path_edges or edge[::-1] in path_edges else 1.5 for edge in G.edges()]

# ノード・エッジの描画
nx.draw_networkx_nodes(G, pos, node_color=node_colors, node_size=1200, edgecolors="black")
nx.draw_networkx_edges(G, pos, edge_color=edge_colors, width=edge_widths)
nx.draw_networkx_labels(G, pos, font_size=12, font_color="white", font_weight="bold")

plt.title(f"Graph Diameter Example (Diameter = {diameter})", fontsize=12, pad=15)
plt.axis("off")
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 隣接行列 A の定義
A = np.array([[0, 1, 1], [1, 0, 1], [1, 1, 0]])

# 隣接行列から無向グラフ
G = nx.from_numpy_array(A)

label_mapping = {0:"1", 1:"2", 2:"3"}
G = nx.relabel_nodes(G, label_mapping)

pos = nx.spring_layout(G)

plt.figure(figsize=(6, 5))

nx.draw_networkx_nodes(
    G,
    pos,
    node_color="#4CAF50",  # ノードの色 (緑)
    node_size=1500,  # ノードのサイズ
    edgecolors="black",  # 枠線の色
    linewidths=1.5,
)

nx.draw_networkx_edges(
    G, pos, width=2.0, edge_color="gray"  # エッジの太さと色
)

nx.draw_networkx_labels(
    G,
    pos,
    font_size=14,
    font_color="white",
    font_weight="bold",  # ノードのテキストラベル
)

plt.title("Graph Visualization of Adjacency Matrix A", fontsize=12, pad=15)
plt.axis("off")  # 軸を非表示
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 隣接行列 A の定義
A = np.array([[0, 1, 1], [0, 0, 1], [1, 0, 0]])

# 2. 隣接行列から有向グラフ (DiGraph) を作成
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# 0, 1, 2 を 1, 2, 3 のラベルに変更
label_mapping = {0: "1", 1: "2", 2: "3"}
G = nx.relabel_nodes(G, label_mapping)

# 3. ノードの配置 (三角形に綺麗に並べる)
pos = {"1": (0, 1), "2": (1, 0), "3": (-1, 0)}

# 4. 描画設定
plt.figure(figsize=(6, 5))

# ノードの描画
nx.draw_networkx_nodes(
    G,
    pos,
    node_color="#2196F3",  # ノードの色 (青)
    node_size=1500,  # ノードサイズ
    edgecolors="black",  # 枠線の色
    linewidths=1.5,
)

# 有向エッジ (矢印) の描画
nx.draw_networkx_edges(
    G,
    pos,
    width=2.0,  # 線の太さ
    edge_color="#333333",  # 線の色
    arrowsize=25,  # 矢印の大きさ
    arrowstyle="-|>",  # 矢印のスタイル
    connectionstyle="arc3,rad=0.1",  # 少しカーブさせて矢印を見やすくする
)

# ラベルの描画
nx.draw_networkx_labels(
    G,
    pos,
    font_size=14,
    font_color="white",
    font_weight="bold",
)

plt.title(
    "Directed Graph Visualization of Adjacency Matrix A", fontsize=12, pad=15
)
plt.axis("off")  # 軸を非表示
plt.tight_layout()
plt.show()

import networkx as nx
import numpy as np

# 1. 隣接行列 A の定義
A = np.array([[0, 1, 1], [0, 0, 1], [1, 0, 0]])

# 2. NetworkX で有向グラフを構築 (0-indexed: 0, 1, 2)
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

def count_paths_of_length_k(G, source, target, k):
    """NetworkXで頂点 source から target への長さ k の全パスの数をカウント"""

    def dfs(current_node, current_length):
        # 長さが k に達したら探索終了
        if current_length == k:
            return 1 if current_node == target else 0

        # 万が一 k を超えた場合は 0 を返して打ち切り
        if current_length > k:
            return 0

        path_count = 0
        for neighbor in G.successors(current_node):
            path_count += dfs(neighbor, current_length + 1)
        return path_count

    return dfs(source, 0)


# 3. k = 1, 2, 3, 4 で行列の累乗と全探索結果を比較検証
num_nodes = A.shape[0]

for k in range(1, 5):
    # (A) 行列演算: A^k を計算
    A_k = np.linalg.matrix_power(A, k)

    # (B) グラフ構造からの実測パス数を格納する行列を作成
    path_counts_dfs = np.zeros((num_nodes, num_nodes), dtype=int)
    for i in range(num_nodes):
        for j in range(num_nodes):
            path_counts_dfs[i, j] = count_paths_of_length_k(G, i, j, k)

    print(f"=== 長さ k = {k} のパス数比較 ===")
    print(f"行列の累乗 A^{k}:\n{A_k}")

    # (A) と (B) が完全一致するか検証
    is_equal = np.array_equal(A_k, path_counts_dfs)
    print(f"全探索で求めたパス数と一致するか?: {is_equal}\n")


# 4. 長さ k = 3 における具体的経路の列挙例 (1 -> 3)
# 1 (index 0) から 3 (index 2) への長さ 3 の経路
print("--- [具体例] 1(N0) から 3(N2) への長さ 3 のパス一覧 ---")


def find_all_paths_of_length_k(G, current, target, k, current_path):
    if len(current_path) - 1 == k:
        if current == target:
            print(" -> ".join([f"ノード{n+1}" for n in current_path]))
        return

    for neighbor in G.successors(current):
        find_all_paths_of_length_k(
            G, neighbor, target, k, current_path + [neighbor]
        )


find_all_paths_of_length_k(G, 0, 2, 3, [0])

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. 隣接行列の定義 (4x4)
# A:0, B:1, C:2, D:3
M = np.array(
    [
        [0, 1, 1, 0],  # A
        [0, 0, 1, 0],  # B
        [1, 0, 0, 1],  # C
        [0, 0, 0, 0],  # D
    ]
)

print("--- 隣接行列 M ---")
print(M)


# 2. 隣接行列から有向グラフ (DiGraph) を作成
G = nx.from_numpy_array(M, create_using=nx.DiGraph)

# 0, 1, 2 を 1, 2, 3 のラベルに変更
label_mapping = {0: "A", 1: "B", 2: "C", 3: "D"}
G = nx.relabel_nodes(G, label_mapping)

# 3. ノードの配置 (三角形に綺麗に並べる)
pos = {"A": (0, 0), "B": (0, 1), "C": (1, 0), "D":(1, 1)}

# 4. 描画設定
plt.figure(figsize=(6, 5))

# ノードの描画
nx.draw_networkx_nodes(
    G,
    pos,
    node_color="#2196F3",  # ノードの色 (青)
    node_size=1500,  # ノードサイズ
    edgecolors="black",  # 枠線の色
    linewidths=1.5,
)

# 有向エッジ (矢印) の描画
nx.draw_networkx_edges(
    G,
    pos,
    width=2.0,  # 線の太さ
    edge_color="#333333",  # 線の色
    arrowsize=25,  # 矢印の大きさ
    arrowstyle="-|>",  # 矢印のスタイル
    connectionstyle="arc3,rad=0.1",  # 少しカーブさせて矢印を見やすくする
)

# ラベルの描画
nx.draw_networkx_labels(
    G,
    pos,
    font_size=14,
    font_color="white",
    font_weight="bold",
)

plt.title(
    "Directed Graph Visualization of Adjacency Matrix A", fontsize=12, pad=15
)
plt.axis("off")  # 軸を非表示
plt.tight_layout()
plt.show()

M_squared = np.linalg.matrix_power(M, 2)

print("\n--- 隣接行列の2乗 M^2 ---")
print(M_squared)
print(
    f"\nAからDへの長さ2のパスの数 (M^2[0, 3]): {M_squared[0, 3]}"
)

import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

# 1. グラフの構築（無向グラフ）
G = nx.Graph()
edges = [("R1", "R2"), ("R1", "R3"), ("R2", "R3"), ("R2", "R4")]
G.add_edges_from(edges)

# ノード順序の固定
nodes = ["R1", "R2", "R3", "R4"]

# 2. 隣接行列 A と 次数行列 D の計算
A = nx.to_numpy_array(G, nodelist=nodes)

# 次数（各ノードの接続数）を計算し、対角行列化する
degrees = [G.degree(n) for n in nodes]
D = np.diag(degrees)

# グラフラプラシアン L = D - A
L = D - A


# 3. 可視化
plt.figure(figsize=(7, 6))
pos = nx.spring_layout(G, seed=42)

# ノードのサイズを次数に応じて大きくする（次数の可視化）
node_sizes = [deg * 1000 for deg in degrees]

nx.draw_networkx_nodes(
    G,
    pos,
    node_color="#FF9800",
    node_size=node_sizes,
    edgecolors="black",
    linewidths=1.5,
)
nx.draw_networkx_edges(G, pos, edge_color="gray", width=2)
nx.draw_networkx_labels(
    G, pos, font_size=12, font_color="white", font_weight="bold"
)

plt.title("Router Network (Node size proportional to Degree)", fontsize=13)
plt.axis("off")
plt.tight_layout()
plt.show()

import networkx as nx
import matplotlib.pyplot as plt

# 1. Create an undirected graph (assuming roads are bidirectional)
G = nx.Graph()

# 2. Add nodes (cities) and edges (roads) with travel times
edges_with_weight = [
    ("Tokyo", "Yokohama", 30),
    ("Tokyo", "Nagoya", 180),
    ("Yokohama", "Nagoya", 150),
    ("Nagoya", "Osaka", 120),
    ("Osaka", "Kyoto", 30),
    ("Osaka", "Kobe", 20),
    ("Kyoto", "Kobe", 25),
]

for u, v, w in edges_with_weight:
    G.add_edge(u, v, weight=w)

# 3. Set source and target cities
source = "Tokyo"
target = "Kobe"

# 4. Compute shortest path
path = nx.shortest_path(G, source=source, target=target, weight="weight")
total_time = nx.shortest_path_length(G, source=source, target=target, weight="weight")

print(f"Shortest path: {' → '.join(path)}")
print(f"Total travel time: {total_time} minutes")

# 5. Prepare layout for visualization
pos = nx.spring_layout(G, seed=42)  # Fixed layout for reproducibility

# 6. Extract edges belonging to the shortest path
path_edges = list(zip(path[:-1], path[1:]))

# 7. Draw the graph
plt.figure(figsize=(10, 8))

# 7-1. Draw all edges in light gray
nx.draw_networkx_edges(G, pos, alpha=0.3, width=1, edge_color="gray")

# 7-2. Highlight shortest path edges in red
nx.draw_networkx_edges(G, pos, edgelist=path_edges, width=3, edge_color="red")

# 7-3. Draw nodes
nx.draw_networkx_nodes(G, pos, node_size=800, node_color="lightblue")
nx.draw_networkx_labels(G, pos, font_size=12)

# 7-4. Add edge labels (travel times)
edge_labels = {(u, v): f"{d['weight']} min" for u, v, d in G.edges(data=True)}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=10)

plt.title("Road Network Between Cities and Shortest Path (Tokyo → Kobe)", fontsize=14)
plt.axis("off")
plt.tight_layout()
plt.show()

import networkx as nx

G = nx.DiGraph()

G.add_nodes_from(["Alice", "Bob", "Charlie", "Diana", "Eve"])
edges = [
    ("Alice", "Bob"),
    ("Alice", "Charlie"),
    ("Bob", "Charlie"),
    ("Bob", "Diana"),
    ("Charlie", "Diana"),
    ("Diana", "Eve"),
    ("Eve", "Alice"),
]
G.add_edges_from(edges)

for node in G.nodes():
  if node == "Alice":
    G.nodes[node]["role"] = "admin"
  else:
    G.nodes[node]["role"] = "user"

# ノード一覧（属性付き）
print("Nodes with attributes:")
for node in G.nodes():
    role = G.nodes[node].get("role", "N/A")
    print(f"  {node}: role={role}")

# ノード一覧
print("Nodes:", list(G.nodes()))

# エッジ一覧
print("Edges:", list(G.edges()))

# 隣接行列
A = nx.adjacency_matrix(G)
print(A.todense())


print("基本情報")

for node in G.nodes():
    in_deg = G.in_degree(node)
    out_deg = G.out_degree(node)
    print(f"  {node}: in_deg={in_deg}, out_deg={out_deg}")

in_degrees = dict(G.in_degree())
print(in_degrees)

import matplotlib.pyplot as plt

pos = nx.spring_layout(G)

nx.draw(G, pos, with_labels=True, node_color="lightblue", node_size=500, edge_color="gray")

edge_labels = {(u, v): d.get("weight", "") for u, v, d in G.edges(data=True)}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

plt.show()

