# -*- coding: utf-8 -*-
"""wavelet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KSc8VIOYQAYBZptaYjGg01538KRq-bms
"""

import numpy as np
import matplotlib.pyplot as plt
import pywt

# サンプリング設定
fs = 1000  # サンプリング周波数 [Hz]
T = 2.0    # 信号長 [秒]
t = np.linspace(0, T, int(fs * T), endpoint=False)

# チャープ信号: 5Hz -> 25Hz まで線形に増加
f0 = 5.0   # 初期周波数 [Hz]
k = 20.0   # 周波数変化率 [Hz/s]
f_inst = f0 + k * t  # 瞬間周波数
x = np.sin(2 * np.pi * (f0 * t + 0.5 * k * t**2))

# フーリエ変換
X = np.fft.fft(x)
freqs = np.fft.fftfreq(len(x), 1/fs)

# 正の周波数のみ
pos_freq = freqs > 0
freqs_pos = freqs[pos_freq]
X_pos = np.abs(X[pos_freq])

# 連続ウェーブレット変換 (CWT)
scales = np.arange(1, 128)  # スケール範囲
coef, freqs_cwt = pywt.cwt(x, scales, 'morl', sampling_period=1/fs)

# 可視化
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

# 元信号
axes[0,0].plot(t, x)
axes[0,0].set_xlabel('Time [s]')
axes[0,0].set_ylabel('Amplitude')
axes[0,0].set_title('Original signal (chirp)')

# 瞬間周波数
axes[0,1].plot(t, f_inst, 'r')
axes[0,1].set_xlabel('Time [s]')
axes[0,1].set_ylabel('Frequency [Hz]')
axes[0,1].set_title('Instantaneous frequency')

# フーリエスペクトル
axes[1,0].plot(freqs_pos, X_pos)
axes[1,0].set_xlabel('Frequency [Hz]')
axes[1,0].set_ylabel('Magnitude')
axes[1,0].set_title('Fourier spectrum')
axes[1,0].set_xlim(0, 50)

# CWT (時間-周波数平面)
im = axes[1,1].imshow(np.abs(coef), extent=[t[0], t[-1], freqs_cwt[-1], freqs_cwt[0]],
           aspect='auto', cmap='jet')
axes[1,1].set_xlabel('Time [s]')
axes[1,1].set_ylabel('Scale → Freq [Hz]')
axes[1,1].set_title('CWT (Magnitude)')
plt.colorbar(im, ax=axes[1,1])

plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
import pywt

# サンプリング設定
fs = 1000
T = 2.0
t = np.linspace(0, T, int(fs * T), endpoint=False)

# 低周波振動 + 短い高周波パルス
f_low = 2.0   # 低周波 [Hz]
f_high = 50.0 # 高周波パルス [Hz]
t0 = 1.0      # パルス中心時刻 [s]
dt = 0.1      # パルス幅 [s]

x_low = np.sin(2 * np.pi * f_low * t)

# 矩形窓で短いパルスを作る
pulse_window = np.where((t >= t0 - dt/2) & (t <= t0 + dt/2), 1.0, 0.0)
x_high = pulse_window * np.sin(2 * np.pi * f_high * t)

x = x_low + x_high

# フーリエ変換
X = np.fft.fft(x)
freqs = np.fft.fftfreq(len(x), 1/fs)
pos_freq = freqs > 0
freqs_pos = freqs[pos_freq]
X_pos = np.abs(X[pos_freq])

# CWT
scales = np.arange(1, 128)
coef, freqs_cwt = pywt.cwt(x, scales, 'morl', sampling_period=1/fs)

# 可視化
fig, axes = plt.subplots(2, 2, figsize=(12, 8))

# 元信号
axes[0,0].plot(t, x)
axes[0,0].plot(t, x_low, 'r--', alpha=0.7, label='low-freq component')
axes[0,0].legend()
axes[0,0].set_xlabel('Time [s]')
axes[0,0].set_ylabel('Amplitude')
axes[0,0].set_title('Signal: low-freq + short high-freq pulse')

# 高周波パルス部分の拡大
axes[0,1].plot(t, x_high)
axes[0,1].set_xlim(t0 - 0.2, t0 + 0.2)
axes[0,1].set_xlabel('Time [s]')
axes[0,1].set_ylabel('Amplitude')
axes[0,1].set_title('High-freq pulse (zoomed)')

# フーリエスペクトル
axes[1,0].plot(freqs_pos, X_pos)
axes[1,0].set_xlabel('Frequency [Hz]')
axes[1,0].set_ylabel('Magnitude')
axes[1,0].set_title('Fourier spectrum')
axes[1,0].set_xlim(0, 60)

# CWT
im = axes[1,1].imshow(np.abs(coef), extent=[t[0], t[-1], freqs_cwt[-1], freqs_cwt[0]],
           aspect='auto', cmap='jet')
axes[1,1].set_xlabel('Time [s]')
axes[1,1].set_ylabel('Scale → Freq [Hz]')
axes[1,1].set_title('CWT (Magnitude)')
plt.colorbar(im, ax=axes[1,1])

plt.tight_layout()
plt.show()

