# -*- coding: utf-8 -*-
"""petting_zoo_v5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDEpC5059LNxi9-GhVTYVWAHbIngWP_K
"""

# エミュレータとGymnasiumのインストール
!pip install gymnasium[atari]
!pip install gymnasium[accept-rom-license]
!pip install pyvirtualdisplay > /dev/null 2>&1
!pip install AutoROM[accept-rom-license]
!AutoROM --accept-license
# 描画用のシステムパッケージ
!apt-get install -y xvfb python-opengl ffmpeg > /dev/null 2>&1
!pip install pettingzoo[atari,accept-rom-license]
!pip install "pettingzoo[sisl]"
!pip install supersuit

!pip uninstall -y box2d-py

import numpy as np
from pettingzoo.sisl import pursuit_v4

class PursuitWrapper:
    def __init__(self, render_mode=None, max_cycles=500, obs_range=7):
        # チームとしての共通目的を維持するため shared_reward=True で環境を初期化
        self.env = pursuit_v4.env(
            render_mode=render_mode,
            max_cycles=max_cycles,
            shared_reward=True
        )
        self.obs_range = obs_range
        self.center_idx = obs_range // 2  # 7x7 の中心 (3, 3) が自分自身の位置

        self.possible_agents = self.env.possible_agents
        self.num_agents = len(self.possible_agents)

        # 🌟 変更点1: 観測次元数の再定義
        # - 空間観測: 7x7x4 = 196次元
        # - 味方の行動履歴: 5行動 (ワンホット) × 8人 = 40次元
        # 合計: 236次元
        self.spatial_dim = (obs_range * obs_range * 4)
        self.action_history_dim = 5 * self.num_agents  # 5行動ワンホット × 8人分
        self.obs_dim = self.spatial_dim + self.action_history_dim
        self.state_dim = self.obs_dim * self.num_agents

        self.action_space = self.env.action_space(self.possible_agents[0])
        self.action_dim = self.action_space.n

        # ハイブリッド報酬の重みパラメータ
        self.distance_reward_scale = 0.12     # 獲物へ接近したときの報酬
        self.coop_reward_scale = 0.2          # 獲物の近くで味方と連携したときの報酬
        self.flanking_bonus_scale = 0.2       # 他に味方がいないルートから回り込んだときの報酬
        self.surround_reward = 40.0            # 3人以上で包囲網を形成したときの報酬

        # 包囲網シェイピング用のパラメータを追加
        self.soft_gather_reward_scale = 0.05    # 2マス先までに味方が集まっているとき（緩い報酬）
        self.cross_position_reward_scale = 0.25 # 上下左右のジャスト位置に配置されたとき（強めの報酬）

        # 衝突ペナルティ（進路妨害や壁への衝突による無駄な動きを抑制）
        self.collision_penalty = -0.24

        # エージェントごとの前ステップの「最も近い獲物への距離」を記録する辞書
        self.prev_min_distances = {}
        self.capture_count = 0
        self.captured_prey_ids = set()  # 捕獲済みターゲットのID（座標など）を保持

        # 🌟 変更点2: 全エージェントの直前行動を保持するグローバルバッファ (初期値は「滞在: 4」のワンホット)
        self.last_actions = np.zeros((self.num_agents, 5), dtype=np.float32)
        self.last_actions[:, 4] = 1.0  # 4: 滞在 (NONE)

    def reset(self):
        self.env.reset()
        self.prev_min_distances = {agent: None for agent in self.possible_agents}
        # 🌟 行動履歴を初期化（滞在状態）
        self.last_actions = np.zeros((self.num_agents, 5), dtype=np.float32)
        self.last_actions[:, 4] = 1.0
        self.capture_count = 0
        self.captured_prey_ids = set()  # 捕獲済みターゲットのID（座標など）を保持

    def get_obs(self, agent):
        if agent not in self.env.agents:
            return None
        obs, _, _, _, _ = self.env.last(agent)
        if obs is None:
            return None

        # 元の環境のレイヤー (7, 7, 3) をパース
        wall_layer = obs[:, :, 0]
        ally_layer = obs[:, :, 1]
        prey_layer = obs[:, :, 2]

        # 🌟 変更点3: 味方レイヤー(Ch2)を個別ID（1.0〜8.0）で埋め直す
        # 元の ally_layer は単に 1 が立っているだけなので、内部情報からIDを特定して配置する
        id_ally_layer = np.zeros((self.obs_range, self.obs_range), dtype=np.float32)

        raw_env = self.env.unwrapped
        try:
            # 自分の絶対座標を取得
            my_agent_obj = next(a for a in raw_env.agents if a.name == agent)
            my_y, my_x = my_agent_obj.state[1], my_agent_obj.state[0]

            # 他の全エージェントを走査して自分のローカル視野に投影
            for other_agent in raw_env.agents:
                if other_agent.name == agent:
                    continue

                oy, ox = other_agent.state[1], other_agent.state[0]
                local_y = oy - my_y + self.center_idx
                local_x = ox - my_x + self.center_idx

                if 0 <= local_y < self.obs_range and 0 <= local_x < self.obs_range:
                    # 'pursuer_0' -> 1.0, 'pursuer_7' -> 8.0 のように浮動小数点ID化して格納
                    agent_id = int(other_agent.name.split('_')[-1]) + 1
                    id_ally_layer[local_y, local_x] = float(agent_id)
        except Exception:
            # 万が一のフォールバック (元のレイヤー構造をそのまま使用)
            id_ally_layer = ally_layer.astype(np.float32)

        # 1. 完全に空いている（通行可能）セルの判定 (味方ID化レイヤーを考慮)
        empty_layer = ((wall_layer == 0) & (id_ally_layer == 0) & (prey_layer == 0)).astype(np.float32)

        # 2. 4つのレイヤーを結合して (7, 7, 4) のセマンティック・テンソルを作成
        semantic_obs = np.stack([
            empty_layer,                   # Ch 0: 通行可能
            wall_layer.astype(np.float32), # Ch 1: 壁
            id_ally_layer,                 # Ch 2: 🌟 味方（個別ID仕様）
            prey_layer.astype(np.float32)  # Ch 3: 敵
        ], axis=-1)

        spatial_flat = semantic_obs.reshape(-1)  # 196次元

        # 🌟 変更点4: 全員の直前行動履歴（40次元）をフラット化して空間特徴量と結合
        action_history_flat = self.last_actions.reshape(-1)  # (8 * 5,) = 40次元

        # 最終的な観測（196 + 40 = 236次元）を生成
        full_obs = np.concatenate([spatial_flat, action_history_flat])
        return full_obs

    def get_global_state(self):
        """
        全員の観測（各236次元）を純粋にリスト化して結合し、
        (num_agents * 236,) の1次元の元データを作成する
        """
        obs_list = []
        for agent in self.possible_agents:
            obs_flat = self.get_obs(agent)
            if obs_flat is not None:
                obs_list.append(obs_flat)
            else:
                obs_list.append(np.zeros(self.obs_dim, dtype=np.float32))

        return np.concatenate(obs_list)

    def count_captures(self, prey_positions, ally_layer):
        count_capture = 0
        for py, px in prey_positions:
            # このターゲットの周囲（マンハッタン距離1以内）にいる味方の数を数える
            allies_around_prey = 0
            for dy in [-1, 0, 1]:
                for dx in [-1, 0, 1]:
                    if dy == 0 and dx == 0:
                        continue
                    ny, nx = py + dy, px + dx
                    if 0 <= ny < self.obs_range and 0 <= nx < self.obs_range:
                        allies_around_prey += ally_layer[ny, nx]

            # 3人以上で囲まれていて、まだ捕獲済みでないターゲットを「捕獲」とみなす
            if allies_around_prey >= 3:
                prey_id = (py, px)  # ターゲットのID（座標で代用）
                if prey_id not in self.captured_prey_ids:
                    # グローバルに「捕獲済み」として登録
                    self.captured_prey_ids.add(prey_id)
                    self.capture_count += 1
                    # print(f"--- 🎉 CAPTURE #{self.capture_count} (prey at {py},{px}) ---")
                    count_capture += 1
            return count_capture

    def _analyze_observation(self, obs_flat):
        """
        1つのエージェントの平坦化された観測(236,)から報酬計算用の情報を抽出する
        """
        if obs_flat is None:
            return None, 0, 0, 0.0

        # 🌟 変更点5: 入力次元が増えたため、先頭の196次元（空間データ）のみを切り出してデコード
        spatial_part = obs_flat[:self.spatial_dim]
        obs = spatial_part.reshape(self.obs_range, self.obs_range, 4)

        # 4チャンネル仕様のインデックス (Ch2が味方、Ch3が敵)
        ally_layer = obs[:, :, 2]
        prey_layer = obs[:, :, 3]

        prey_positions = np.argwhere(prey_layer > 0)
        # 捕獲カウント
        count_capture = self.count_captures(prey_positions, ally_layer)

        min_dist = float('inf')
        closest_prey_pos = None
        cy, cx = self.center_idx, self.center_idx

        # 1. 最も近い獲物を特定
        for py, px in prey_positions:
            dist = abs(py - cy) + abs(px - cx)
            if dist < min_dist:
                min_dist = dist
                closest_prey_pos = (py, px)

        if min_dist == float('inf'):
            return None, 0, 0, 0.0, count_capture  # 視界内に獲物がいない場合

        # 2. 協調判定：自分の隣接4マスにいる味方の総数 (ID化されているため、0より大きいマスをカウント)
        allies_count = 0
        neighbors = [(cy-1, cx), (cy+1, cx), (cy, cx-1), (cy, cx+1)]
        for ny, nx in neighbors:
            if 0 <= ny < self.obs_range and 0 <= nx < self.obs_range:
                if ally_layer[ny, nx] > 0:
                    allies_count += 1

        # 3. 獲物がいる「方向（セクター）」に他の味方が何人いるかをカウント
        py, px = closest_prey_pos
        flank_allies = 0

        if py < cy:
            flank_allies += np.sum(ally_layer[0:cy, :] > 0)
        elif py > cy:
            flank_allies += np.sum(ally_layer[cy+1:, :] > 0)

        if px < cx:
            flank_allies += np.sum(ally_layer[:, 0:cx] > 0)
        elif px > cx:
            flank_allies += np.sum(ally_layer[:, cx+1:] > 0)

        # 4. 特定のマス（最も近い敵）を基準とした包囲報酬の計算
        shaping_reward = 0.0

        # 敵の周囲（マンハッタン距離で2マス以内の全範囲を走査）
        for dy in range(-2, 3):
            for dx in range(-2, 3):
                target_y = py + dy
                target_x = px + dx

                # 視界(7x7)の範囲内、かつ「敵のマスそのもの」は除外
                if (0 <= target_y < self.obs_range) and (0 <= target_x < self.obs_range) and (dy != 0 or dx != 0):

                    # その位置に味方が綺麗に配置されているか？ (0より大きければ味方が存在)
                    if ally_layer[target_y, target_x] > 0:
                        m_dist = abs(dy) + abs(dx)

                        # 条件A: 上下左右のジャスト位置（距離1の十字位置）の場合（強めの報酬）
                        if m_dist == 1:
                            # ※重ね合わせによる重複はID化で検知可能（必要なら厳密化できますが、ここでは存在判定）
                            shaping_reward += self.cross_position_reward_scale

                        # 条件B: 2マス先までにゆるく集まっている場合（緩い報酬）
                        elif m_dist <= 2:
                            shaping_reward += self.soft_gather_reward_scale

        return min_dist, allies_count, flank_allies, shaping_reward, count_capture

    def step(self, agent, action):
        if agent not in self.env.agents:
            return np.zeros(self.obs_dim, dtype=np.float32), 0.0, True, True, {}

        current_cycle = getattr(self.env.unwrapped, 'cycles', 0)

        _, _, terminated, truncated, _ = self.env.last(agent)
        step_action = None if (terminated or truncated) else action

        # 🌟 変更点6: エージェントが選択した行動履歴をグローバルバッファに即時ワンホット形式で書き込み
        agent_idx = int(agent.split('_')[-1])
        if step_action is not None:
            self.last_actions[agent_idx] = 0.0
            self.last_actions[agent_idx, step_action] = 1.0

        self.env.step(step_action)

        if agent not in self.env.agents:
            return np.zeros(self.obs_dim, dtype=np.float32), 0.0, True, True, {}

        obs_flat, team_reward, terminated, truncated, info = self.env.last(agent)

        # 🌟 236次元にアップデートされた新しい get_obs(agent) データを取得
        obs = self.get_obs(agent)

        # -----------------------------------------------------------------
        # 個別評価報酬（Individual Reward）の計算開始
        # -----------------------------------------------------------------
        individual_reward = 0.0

        # 観測データから距離、周囲の味方数、シェイピング報酬を抽出
        current_min_dist, allies_count, flank_allies, shaping_reward, count_capture = self._analyze_observation(obs)
        count_capture = count_capture if count_capture else 0
        team_reward += self.surround_reward * count_capture

        # 包囲網シェイピング報酬の適用
        individual_reward += shaping_reward

        # 1. 距離・回り込みベースの評価
        reward_distance = 0.0
        prev_dist = self.prev_min_distances.get(agent)

        if current_min_dist is not None and prev_dist is not None:
            change = prev_dist - current_min_dist
            reward_distance = change * self.distance_reward_scale
            if change > 0 and flank_allies == 0:
                reward_distance += self.flanking_bonus_scale

        self.prev_min_distances[agent] = current_min_dist
        individual_reward += reward_distance

        # 2. 協調行動（接近＋包囲網）の評価
        reward_coop = 0.0
        if current_min_dist is not None and current_min_dist <= 2:
            if allies_count >= 1:
                reward_coop += self.coop_reward_scale
            if allies_count >= 3:
                reward_coop += self.surround_reward
        individual_reward += reward_coop

        # 3. 衝突ペナルティの評価
        if info.get('wasted_move', False):
            individual_reward += self.collision_penalty

        # 4. チーム全員の完全捕獲成功時の個別時間ボーナス
        if terminated and not truncated:
            if team_reward > 0:
                time_bonus = max(0, 500 - current_cycle) * 1.0
                individual_reward += (500.0 + time_bonus)
                print(f"--- 🎉 TRUE CAPTURE SUCCESS! Agent: {agent} | Bonus: {500.0 + time_bonus} ---")

        # -----------------------------------------------------------------
        # ハイブリッド報酬の合算（チーム共通報酬 ＋ 各自の個別評価）
        # -----------------------------------------------------------------
        hybrid_reward = (team_reward + individual_reward) * 0.1

        # 🌟 236次元の obs（空間196 + 行動40）を返します
        return obs, hybrid_reward, terminated, truncated, info, count_capture

    def render(self):
        render_mode = getattr(self.env, "render_mode", None)
        if render_mode is None:
            return None

        frame = self.env.render()

        if frame is None and render_mode == "human":
            try:
                import pygame
                screen = pygame.display.get_surface()
                if screen is not None:
                    img_str = pygame.image.tostring(screen, "RGB")
                    frame = np.frombuffer(img_str, dtype=np.uint8).reshape(screen.get_size()[1], screen.get_size()[0], 3)
            except Exception:
                pass

        return frame

import numpy as np
import torch
import torch.nn as nn
from torch.distributions import Categorical
import torch.optim as optim

# =====================================================================
# 1. Transformer アーキテクチャ
# =====================================================================

class MAPPO_TransformerActor(nn.Module):
    def __init__(self, obs_range=7, in_channels=4, d_model=64, nhead=4, num_layers=2, act_dim=5, num_agents=8, id_dim=8, hidden_size=256):
        super().__init__()
        self.obs_range = obs_range
        self.num_tokens = obs_range * obs_range  # 7x7 = 49
        self.spatial_dim = obs_range * obs_range * in_channels  # 196
        self.num_agents = num_agents

        # 1. 各マスの4次元情報を d_model(64次元) に引き上げる線形埋め込み
        self.embedding = nn.Linear(in_channels, d_model)

        # 2. 2次元空間用の学習可能な位置エンコーディング
        self.pos_embedding = nn.Parameter(torch.randn(1, self.num_tokens, d_model))

        # 🌟 変更点1: 他エージェントの行動履歴（40次元）を処理する線形層
        # 8人分×5行動を埋め込み、Transformerの各トークンに付加的なコンテキストとして加算/結合できるようにする
        self.action_history_embed = nn.Sequential(
            nn.Linear(num_agents * 5, d_model),
            nn.GELU()
        )

        # 3. エージェント固有IDの埋め込み（譲り合いの個性を学習）
        self.id_embedding = nn.Embedding(num_embeddings=num_agents, embedding_dim=id_dim)

        # 4. Transformer Encoder（GELUを内部で採用）
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=d_model * 2,
            activation="gelu", batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # 5. 出力用MLP：中心セルの特徴量（64） + エージェントID（8）
        input_dim = d_model + id_dim
        self.mlp = nn.Sequential(
            nn.Linear(input_dim, hidden_size),
            nn.GELU(),
            nn.Linear(hidden_size, act_dim)
        )

    def forward(self, obs, agent_id):
        """
        Args:
            obs: (batch_size, 236) のフラットな観測 (196次元空間 + 40次元行動履歴)
            agent_id: (batch_size,) のエージェント固有ID
        """
        batch_size = obs.shape[0]

        # 🌟 変更点2: 空間特徴量(196) と 行動履歴履歴(40) を分離
        spatial_obs = obs[:, :self.spatial_dim]          # (batch_size, 196)
        action_history = obs[:, self.spatial_dim:]       # (batch_size, 40)

        # (batch_size, 196) -> (batch_size, 49, 4) へトークン変形
        x = spatial_obs.view(batch_size, self.num_tokens, -1)

        # トークン埋め込み + 位置エンコーディング
        x = self.embedding(x) + self.pos_embedding  # (batch_size, 49, 64)

        # 🌟 変更点3: 行動履歴の埋め込みをブロードキャストして、空間トークンにコンテキストとして加算
        # 全員が「直前誰がどう動いたか」を知った上で、各マスのAttentionを計算できるようにします
        act_emb = self.action_history_embed(action_history).unsqueeze(1)  # (batch_size, 1, 64)
        x = x + act_emb  # 空間特徴に協調コンテキストをブレンド

        # Transformer処理
        features = self.transformer(x)  # (batch_size, 49, 64)

        # 視界の中心(3,3) ＝ インデックス 24 の自身のトークン特徴量を抽出
        my_feature = features[:, 24, :]  # (batch_size, 64)

        # ID特徴量の統合
        if agent_id.dim() == 2:
            agent_id = agent_id.squeeze(-1)
        id_feats = self.id_embedding(agent_id)  # (batch_size, 8)

        # 結合して行動のカテゴリカル分布を返却
        combined = torch.cat([my_feature, id_feats], dim=-1)
        logits = self.mlp(combined)

        return Categorical(logits=logits)


class MAPPO_TransformerCritic(nn.Module):
    def __init__(self, num_agents=8, obs_range=7, in_channels=4, d_model=64, nhead=4, num_layers=2, agent_emb_dim=16):
        super().__init__()
        self.num_agents = num_agents
        self.num_tokens_per_agent = obs_range * obs_range  # 49
        self.spatial_dim_per_agent = obs_range * obs_range * in_channels  # 196
        self.obs_dim_per_agent = self.spatial_dim_per_agent + (num_agents * 5)  # 236
        self.total_tokens = self.num_tokens_per_agent * num_agents  # 49 * 8 = 392

        # 各エージェントマスの特徴抽出埋め込み
        self.embedding = nn.Linear(in_channels, d_model)

        # 全トークン（392個）の位置・所属エージェント認識用エンコーディング
        self.pos_embedding = nn.Parameter(torch.randn(1, self.total_tokens, d_model))

        # 🌟 変更点4: Critic側でも全員の行動履歴（40次元）を集約するレイヤー
        self.global_action_embed = nn.Sequential(
            nn.Linear(num_agents * 5, d_model),
            nn.GELU()
        )

        # 評価対象ターゲットエージェントのID埋め込み
        self.agent_embedding = nn.Embedding(num_agents, agent_emb_dim)

        # Transformer Encoder
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=d_model, nhead=nhead, dim_feedforward=d_model * 2,
            activation="gelu", batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # 統合価値出力ヘッド（グローバル行動特徴も考慮するため、入力を拡張）
        self.v_head = nn.Sequential(
            nn.Linear(d_model * 2 + agent_emb_dim, 128),
            nn.GELU(),
            nn.Linear(128, 1)
        )

    def forward(self, global_states, target_agent_id):
        """
        Args:
            global_states: (batch_size, num_agents, 236) のテンソル
            target_agent_id: (batch_size,) の対象エージェントID
        """
        device = next(self.parameters()).device
        global_states = global_states.to(device)
        target_agent_id = target_agent_id.to(device)

        batch_size = global_states.size(0)

        # 🌟 変更点5: 1エージェントあたり236次元に拡張された global_states を空間と行動履歴に分離
        # global_statesの形状: (batch_size, 8, 236)
        spatial_states = global_states[:, :, :self.spatial_dim_per_agent]  # (batch_size, 8, 196)

        # 行動履歴は共通バッファなため、インデックス0番のエージェントの観測末尾から代表して抽出
        action_history = global_states[:, 0, self.spatial_dim_per_agent:]  # (batch_size, 40)

        # 全員分を1つの巨大なトークンシーケンスに変形 (batch_size, 392, 4)
        x = spatial_states.reshape(batch_size, self.total_tokens, -1)

        # 埋め込みと自己アテンション処理
        x = self.embedding(x) + self.pos_embedding
        features = self.transformer(x)  # (batch_size, 392, 64)

        # 平均プーリングによるグローバル盤面表現の圧縮
        global_spatial_feature = torch.mean(features, dim=1)  # (batch_size, 64)

        # 🌟 変更点6: グローバル行動履歴の埋め込み
        global_action_feature = self.global_action_embed(action_history)  # (batch_size, 64)

        # 評価ターゲットIDの結合
        if target_agent_id.dim() == 2:
            target_agent_id = target_agent_id.squeeze(-1)
        elif target_agent_id.dim() == 0:
            target_agent_id = target_agent_id.unsqueeze(0).repeat(batch_size)

        agent_emb = self.agent_embedding(target_agent_id)

        # 空間特徴 + 行動特徴 + ターゲットID特徴をすべて結合
        combined = torch.cat([global_spatial_feature, global_action_feature, agent_emb], dim=-1)
        return self.v_head(combined)


# =====================================================================
# 2. MAPPO トレーナークラス
# =====================================================================
class MAPPO:
    def __init__(self, num_agents, obs_dim=236, state_dim=1888, action_dim=5,
                 lr_actor=1e-4, lr_critic=1e-4, gamma=0.99, gae_lambda=0.95,
                 clip_epsilon=0.2, value_coef=0.5, entropy_coef=0.01,
                 device=torch.device("cpu")):
        self.num_agents = num_agents
        self.obs_dim = obs_dim  # 🌟 236 に拡張 (196 + 40)
        self.state_dim = state_dim  # 🌟 1888 に拡張 (236x8)
        self.action_dim = action_dim
        self.gamma = gamma
        self.gae_lambda = gae_lambda
        self.clip_epsilon = clip_epsilon
        self.value_coef = value_coef
        self.entropy_coef = entropy_coef
        self.device = device

        # Transformerベースのモデルを初期化
        self.actor = MAPPO_TransformerActor(num_agents=num_agents, act_dim=action_dim).to(device)
        self.critic = MAPPO_TransformerCritic(num_agents=num_agents).to(device)

        # 最適化器
        self.optimizer_actor = optim.Adam(self.actor.parameters(), lr=lr_actor)
        self.optimizer_critic = optim.Adam(self.critic.parameters(), lr=lr_critic)

    def get_action(self, obs, greedy=False):
        """
        Args:
            obs: (num_agents, 236) のテンソル
        """
        obs = obs.to(self.device)
        agent_ids = torch.arange(self.num_agents, dtype=torch.long, device=self.device)

        with torch.no_grad():
            dist = self.actor(obs, agent_ids)

            if greedy:
                actions = torch.argmax(dist.logits, dim=-1)
            else:
                actions = dist.sample()

            log_probs = dist.log_prob(actions)

            return actions.cpu().numpy(), log_probs.cpu().numpy()

    def get_value_for_agent(self, state, agent_id):
        """
        特定のエージェント視点での中央集中型Transformer Criticの価値を算出
        """
        # 🌟 変更点7: 形状の安全な復元次元を obs_dim=236 ベースに修正
        if state.dim() == 1:
            state = state.view(self.num_agents, self.obs_dim)
        if state.dim() == 2:
            state = state.unsqueeze(0)

        state = state.to(self.device)
        agent_id = agent_id.to(self.device)

        with torch.no_grad():
            value = self.critic(state, agent_id)
            return value.item()

    def get_value(self, state):
        dummy_agent_id = torch.tensor([0], dtype=torch.long, device=self.device)
        return self.get_value_for_agent(state, dummy_agent_id)

    def update(self, batch, epochs=3):
        if batch is None:
            return 0.0, 0.0, 0.0

        batch_size = batch['obs'].shape[0]

        obs = torch.FloatTensor(batch['obs']).to(self.device)                  # (batch, num_agents, 236)
        actions = torch.LongTensor(batch['actions']).to(self.device)           # (batch, num_agents)
        old_log_probs = torch.FloatTensor(batch['log_probs']).to(self.device)   # (batch, num_agents)
        advantages = torch.FloatTensor(batch['advantages']).to(self.device)     # (batch, num_agents)
        returns = torch.FloatTensor(batch['rewards']).to(self.device)           # (batch, num_agents)

        global_states = torch.FloatTensor(batch['global_states']).to(self.device)

        if global_states.dim() == 2:
            global_states = global_states.view(batch_size, self.num_agents, self.obs_dim)

        # Advantageの正規化
        advantages = (advantages - advantages.mean(dim=0, keepdim=True)) / (advantages.std(dim=0, keepdim=True) + 1e-8)

        actor_losses = []
        critic_losses = []
        entropies = []

        batch_agent_ids = torch.arange(self.num_agents, dtype=torch.long, device=self.device).repeat(batch_size, 1)

        for epoch in range(epochs):
            # --- 1. Actorの更新 ---
            flat_obs = obs.view(-1, self.obs_dim)
            flat_ids = batch_agent_ids.view(-1)

            dist = self.actor(flat_obs, flat_ids)

            new_log_probs = dist.log_prob(actions.view(-1)).view(batch_size, self.num_agents)
            entropy = dist.entropy().view(batch_size, self.num_agents).mean()

            ratio = torch.exp(new_log_probs - old_log_probs)

            surr1 = ratio * advantages
            surr2 = torch.clamp(ratio, 1.0 - self.clip_epsilon, 1.0 + self.clip_epsilon) * advantages

            actor_loss = -torch.min(surr1, surr2).mean() - self.entropy_coef * entropy

            self.optimizer_actor.zero_grad()
            actor_loss.backward()
            torch.nn.utils.clip_grad_norm_(self.actor.parameters(), 0.5)
            self.optimizer_actor.step()

            # --- 2. Criticの更新 ---
            critic_epoch_losses = []

            for i in range(self.num_agents):
                target_agent_id = torch.full((batch_size,), i, dtype=torch.long, device=self.device)

                # Transformer Criticへ整形した状態データをフォワード
                values = self.critic(global_states, target_agent_id).squeeze(-1)  # (batch,)
                target_returns = returns[:, i]

                critic_loss = nn.SmoothL1Loss()(values, target_returns)
                critic_epoch_losses.append(critic_loss)

            total_critic_loss = torch.stack(critic_epoch_losses).mean() * self.value_coef

            self.optimizer_critic.zero_grad()
            total_critic_loss.backward()
            torch.nn.utils.clip_grad_norm_(self.critic.parameters(), 0.5)
            self.optimizer_critic.step()

            actor_losses.append(actor_loss.item())
            critic_losses.append(total_critic_loss.item())
            entropies.append(entropy.item())

        return np.mean(actor_losses), np.mean(critic_losses), np.mean(entropies)

    def load_checkpoint(self, checkpoint_path):
        checkpoint = torch.load(checkpoint_path, map_location=self.device)
        self.actor.load_state_dict(checkpoint['actor_state_dict'])
        self.critic.load_state_dict(checkpoint['critic_state_dict'])

        self.optimizer_actor.load_state_dict(checkpoint['optimizer_actor_state_dict'])
        self.optimizer_critic.load_state_dict(checkpoint['optimizer_critic_state_dict'])

        episode = checkpoint['episode']
        print(f"チェックポイントを読み込み: {checkpoint_path} (episode: {episode})")
        return episode

import numpy as np
from collections import defaultdict

class MultiAgentBuffer:
    def __init__(self, num_agents, obs_dim, state_dim, action_dim):
        self.num_agents = num_agents
        self.obs_dim = obs_dim          # 🌟 236 (196空間 + 40行動履歴)
        self.state_dim = state_dim      # 🌟 1888 (236 x 8)
        self.action_dim = action_dim

        self.buffer = {
            'obs': [],
            'actions': [],
            'rewards': [],
            'global_states': [],
            'log_probs': [],
            'values': [],       # 各エージェントの辞書形式 {'pursuer_0': v, ...}
            'terminated': [],
            'truncated': [],
            'advantages': [],   # compute_advantages内で辞書のリストとして生成
            'returns': [],      # compute_advantages内で辞書のリストとして生成
        }

        self.episode_lengths = []
        self.current_episode_steps = 0

    def store(self, obs_dict, action_dict, reward_dict, global_state,
              log_prob_dict, value_dict, terminated, truncated):
        """
        環境の1ステップのデータを保存
        """
        self.buffer['obs'].append(obs_dict)
        self.buffer['actions'].append(action_dict)
        self.buffer['rewards'].append(reward_dict)
        self.buffer['global_states'].append(global_state)
        self.buffer['log_probs'].append(log_prob_dict)
        self.buffer['values'].append(value_dict)
        self.buffer['terminated'].append(terminated)
        self.buffer['truncated'].append(truncated)

        self.current_episode_steps += 1

        # エピソードが終了（または時間切れ）したら長さを記録
        if terminated or truncated:
            self.episode_lengths.append(self.current_episode_steps)
            self.current_episode_steps = 0

    def sample(self, batch_size):
        if len(self.buffer['obs']) == 0:
            return None

        total_stored = len(self.buffer['obs'])
        indices = np.random.choice(total_stored, size=batch_size, replace=False)

        obs_batch, actions_batch, rewards_batch = [], [], []
        log_probs_batch, advantages_batch, returns_batch = [], [], []
        values_batch, global_states_batch = [], []

        for idx in indices:
            obs_step, actions_step, log_probs_step = [], [], []
            values_step, advantages_step, returns_step = [], [], []

            for i in range(self.num_agents):
                agent_name = f'pursuer_{i}'
                obs_step.append(self.buffer['obs'][idx][agent_name])
                actions_step.append(self.buffer['actions'][idx][agent_name])
                log_probs_step.append(self.buffer['log_probs'][idx][agent_name])
                values_step.append(self.buffer['values'][idx][agent_name])

                # 🌟 変更点1: 報酬（Returns）バッチのサンプリングキーを正しく設定
                # 元のコードの rewards_step.append(self.buffer['returns']...) に合わせつつ安全に取得
                if idx < len(self.buffer['returns']) and self.buffer['returns'][idx] is not None and agent_name in self.buffer['returns'][idx]:
                    returns_step.append(self.buffer['returns'][idx][agent_name])
                else:
                    returns_step.append(0.0)

                # 🌟 変更点2: Advantageバッチのサンプリング
                if idx < len(self.buffer['advantages']) and self.buffer['advantages'][idx] is not None and agent_name in self.buffer['advantages'][idx]:
                    advantages_step.append(self.buffer['advantages'][idx][agent_name])
                else:
                    advantages_step.append(0.0)

            obs_batch.append(obs_step)
            actions_batch.append(actions_step)
            log_probs_batch.append(log_probs_step)
            values_batch.append(values_step)

            # 🌟 変更点3: リスト名とバッチキーの不整合を防ぐため、変数名をわかりやすく整理
            returns_batch.append(returns_step)
            advantages_batch.append(advantages_step)

            global_states_batch.append(self.buffer['global_states'][idx])

        # MAPPO.update() が期待するNumPy配列の形状に成形
        batch = {
            'obs': np.array(obs_batch, dtype=np.float32),                 # (batch, num_agents, 236)
            'actions': np.array(actions_batch, dtype=np.int64),           # (batch, num_agents)
            'rewards': np.array(returns_batch, dtype=np.float32),         # (batch, num_agents) ※MAPPO側で returns として受け取るもの
            'global_states': np.array(global_states_batch, dtype=np.float32), # (batch, num_agents, 236) またはフラット
            'log_probs': np.array(log_probs_batch, dtype=np.float32),     # (batch, num_agents)
            'values': np.array(values_batch, dtype=np.float32),           # (batch, num_agents)
            'advantages': np.array(advantages_batch, dtype=np.float32),   # (batch, num_agents)
        }
        return batch

    def compute_advantages(self, gamma=0.99, gae_lambda=0.95):
        total_steps = len(self.buffer['obs'])
        advantages = [None] * total_steps
        returns = [None] * total_steps

        # ロールアウト終了時に、まだ途中で終わっていない未完のエピソードの長さを一時的に追加
        working_lengths = list(self.episode_lengths)
        if self.current_episode_steps > 0:
            working_lengths.append(self.current_episode_steps)

        start_idx = 0
        for ep_len in working_lengths:
            end_idx = start_idx + ep_len

            rewards_ep = self.buffer['rewards'][start_idx:end_idx]
            values_ep = self.buffer['values'][start_idx:end_idx]
            terminated_ep = self.buffer['terminated'][start_idx:end_idx]
            truncated_ep = self.buffer['truncated'][start_idx:end_idx]

            for agent_idx in range(self.num_agents):
                agent_name = f'pursuer_{agent_idx}'
                agent_rewards = [r[agent_name] for r in rewards_ep]
                agent_values = [v[agent_name] for v in values_ep]

                advantage_ep = np.zeros(ep_len)
                return_ep = np.zeros(ep_len)

                gae = 0.0

                # 時間切れ（truncated）またはロールアウトの強制的な終端である場合、最後の状態の価値でブートストラップ
                if truncated_ep[-1] or (not terminated_ep[-1] and start_idx + ep_len == total_steps):
                    next_value = agent_values[-1]
                    future_return = agent_values[-1]
                else:
                    next_value = 0.0
                    future_return = 0.0

                # 未来から過去へ向かって逆順ループ
                for t in reversed(range(ep_len)):
                    is_not_terminal = 0.0 if terminated_ep[t] else 1.0

                    delta = agent_rewards[t] + gamma * next_value * is_not_terminal - agent_values[t]
                    gae = delta + gamma * gae_lambda * is_not_terminal * gae
                    advantage_ep[t] = gae

                    future_return = agent_rewards[t] + gamma * is_not_terminal * future_return
                    return_ep[t] = future_return

                    next_value = agent_values[t]

                for t_idx in range(ep_len):
                    global_idx = start_idx + t_idx
                    if advantages[global_idx] is None:
                        advantages[global_idx] = {}
                        returns[global_idx] = {}
                    advantages[global_idx][agent_name] = advantage_ep[t_idx]
                    returns[global_idx][agent_name] = return_ep[t_idx]

            start_idx = end_idx

        self.buffer['advantages'] = advantages
        self.buffer['returns'] = returns

    def clear(self):
        for key in self.buffer:
            self.buffer[key] = []
        self.episode_lengths = []
        self.current_episode_steps = 0

    def __len__(self):
        return len(self.buffer['obs'])

from google.colab import drive
import os
drive.mount('/content/drive')

CHECKPOINT_DIR = "/content/drive/MyDrive/rl_pursuit"
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
def save_checkpoint(mappo, episode, checkpoint_dir="checkpoints"):
    """
    MAPPOのチェックポイントを保存

    Args:
        mappo: MAPPOインスタンス
        episode: 現在のエピソード番号
        checkpoint_dir: 保存ディレクトリ
    """
    os.makedirs(checkpoint_dir, exist_ok=True)
    checkpoint_path = os.path.join(checkpoint_dir, f"mappo_episode.pth")

    # 現在のデバイスを退避（CPU/GPUに柔軟に対応するため）
    actor_device = next(mappo.actor.parameters()).device
    critic_device = next(mappo.critic.parameters()).device

    # 安全な保存のために一度モデルをCPUへ退避
    mappo.actor.cpu()
    mappo.critic.cpu()

    # 状態辞書の作成
    save_dict = {
        'episode': episode,
        'actor_state_dict': mappo.actor.state_dict(),
        'critic_state_dict': mappo.critic.state_dict(),
        'cnn_encoder_state_dict': mappo.cnn_encoder.state_dict(),      # Actor側のCNN
        'critic_encoder_state_dict': mappo.critic_encoder.state_dict(),  # Critic側のCNN (追加)
        'optimizer_actor_state_dict': mappo.optimizer_actor.state_dict(),
        'optimizer_critic_state_dict': mappo.optimizer_critic.state_dict(),
    }

    torch.save(save_dict, checkpoint_path)

    # モデルを元のデバイスに復元
    mappo.actor.to(actor_device)
    mappo.critic.to(critic_device)

    print(f"Checkpoint saved: {checkpoint_path}")


def load_checkpoint(mappo, checkpoint_path, device='cpu'):
    """
    外部関数としてMAPPOのチェックポイントを読み込み

    Args:
        mappo: MAPPOインスタンス
        checkpoint_path: .pthファイルへのパス
        device: マップ先のデバイス設定
    """
    checkpoint = torch.load(checkpoint_path, map_location=device)

    # 各種ネットワークのウェイトをロード
    mappo.actor.load_state_dict(checkpoint['actor_state_dict'])
    mappo.critic.load_state_dict(checkpoint['critic_state_dict'])
    mappo.cnn_encoder.load_state_dict(checkpoint['cnn_encoder_state_dict'])
    mappo.critic_encoder.load_state_dict(checkpoint['critic_encoder_state_dict']) # 追加

    # オプティマイザの状態をロード
    mappo.optimizer_actor.load_state_dict(checkpoint['optimizer_actor_state_dict'])
    mappo.optimizer_critic.load_state_dict(checkpoint['optimizer_critic_state_dict'])

    episode = checkpoint['episode']
    print(f"チェックポイントを読み込み: {checkpoint_path} (episode: {episode})")
    return episode

import os
from collections import deque
import numpy as np
import torch

# =====================================================================
# ハイパーパラメータ & 設定
# =====================================================================
max_episodes = 1000
max_cycles = 500
batch_size = 64
update_epochs = 3
gamma = 0.99
gae_lambda = 0.95
checkpoint_interval = 10
CHECKPOINT_DIR = "/content/drive/MyDrive/rl_pursuit"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 🌟 行動履歴付き（obs_dim=236）に対応したラッパーで初期化
env = PursuitWrapper(render_mode=None, max_cycles=max_cycles)
num_agents = env.num_agents
obs_dim = env.obs_dim          # 🌟 自動的に 236 (196 + 40) になります
state_dim = env.state_dim      # 🌟 自動的に 1888 (236 x 8) になります
action_dim = env.action_dim

# MAPPOの初期化 (内部のActor/CriticがTransformerへと自動構築されます)
mappo = MAPPO(
    num_agents=num_agents,
    obs_dim=obs_dim,
    state_dim=state_dim,
    action_dim=action_dim,
    gamma=gamma,
    gae_lambda=gae_lambda,
    device=device
)

# 外部にMultiAgentBufferを明示的に紐付け
from __main__ import MultiAgentBuffer
mappo.buffer = MultiAgentBuffer(num_agents, obs_dim, state_dim, action_dim)

print("=== MAPPO（Transformer & IDベース）学習開始 ===")
print(f"エージェント数: {num_agents}")
print(f"観測次元 (空間196 + 行動履歴40): {obs_dim}")
print(f"グローバル状態次元: {state_dim}")
print(f"行動空間サイズ: {action_dim}")
print(f"使用デバイス: {device}")

# 🛠️ チェックポイント復元関数の安全ラップ
def load_checkpoint_safely(model_obj, path, device):
    try:
        checkpoint = torch.load(path, map_location=device)
        model_obj.actor.load_state_dict(checkpoint['actor_state_dict'])
        model_obj.critic.load_state_dict(checkpoint['critic_state_dict'])
        model_obj.optimizer_actor.load_state_dict(checkpoint['optimizer_actor_state_dict'])
        model_obj.optimizer_critic.load_state_dict(checkpoint['optimizer_critic_state_dict'])
        return checkpoint['episode']
    except Exception as e:
        print(f"警告: チェックポイントの読み込み中にエラーが発生しました（アーキテクチャ不一致の可能性）: {e}")
        return 0

# 🛠️ チェックポイント保存関数の安全ラップ
def save_checkpoint_safely(model_obj, ep, checkpoint_dir):
    os.makedirs(checkpoint_dir, exist_ok=True)
    save_path = os.path.join(checkpoint_dir, "mappo_episode.pth")
    torch.save({
        'episode': ep,
        'actor_state_dict': model_obj.actor.state_dict(),
        'critic_state_dict': model_obj.critic.state_dict(),
        'optimizer_actor_state_dict': model_obj.optimizer_actor.state_dict(),
        'optimizer_critic_state_dict': model_obj.optimizer_critic.state_dict(),
    }, save_path)
    print(f"💾 チェックポイントを保存しました: {save_path} (Episode {ep})")

path_checkpoint = os.path.join(CHECKPOINT_DIR, "mappo_episode.pth")
start_episode = 0
if os.path.exists(path_checkpoint):
    start_episode = load_checkpoint_safely(mappo, path_checkpoint, device=device)
    print(f"再開エピソード: {start_episode}")

# モニタリング用のバッファ
reward_buffer = deque(maxlen=100)
capture_buffer = deque(maxlen=100)

# =====================================================================
# メイン学習ループ
# =====================================================================
for episode in range(start_episode, max_episodes):
    env.reset()
    episode_reward = 0.0
    episode_captures = 0

    # AEC環境のループ
    for agent in env.env.agent_iter():
        _, _, terminated, truncated, _ = env.env.last(agent)

        if terminated or truncated:
            action = None
        else:
            # 1. 全エージェントの「現在のステップ」における最新236次元観測（行動履歴含む）を集約
            obs_list = []
            for i in range(num_agents):
                agent_name = f'pursuer_{i}'
                if agent_name in env.env.agents:
                    agent_obs = env.get_obs(agent_name)
                    obs_list.append(agent_obs if agent_obs is not None else np.zeros(obs_dim, dtype=np.float32))
                else:
                    obs_list.append(np.zeros(obs_dim, dtype=np.float32))

            # 2. テンソル化してポリシーに入力
            obs_tensor = torch.FloatTensor(np.array(obs_list)).to(device)  # (num_agents, 236)

            # MAPPOで全エージェント分の行動と確率を同時に推論
            actions_np, log_probs_np = mappo.get_action(obs_tensor)

            # 現在のループ対象エージェントの行動を抽出
            agent_idx = int(agent.split('_')[-1])
            action = actions_np[agent_idx]

        # 3. 環境を1ステップ進める
        obs, reward, terminated, truncated, info, count_capture = env.step(agent, action)
        episode_reward += reward

        # Pursuit環境特有の捕獲報酬(+5)をカウント
        episode_captures += count_capture if count_capture else 0

        # 4. バッファに保存するためのステップ全体の辞書データを構築
        obs_dict = {}
        action_dict = {}
        reward_dict = {}
        log_prob_dict = {}
        value_dict = {}

        # 🌟 変更点1: 環境ステップ通過後（＝行動履歴が更新された後）の最新状態を再取得して辞書化
        # これにより、バッファーに保存されるobsと、Criticに入力されるglobal_stateの次元数(236)が完全に一致します
        global_state_list = []
        for i in range(num_agents):
            agent_name = f'pursuer_{i}'
            if agent_name in env.env.agents:
                agent_obs = env.get_obs(agent_name)
                current_obs = agent_obs if agent_obs is not None else np.zeros(obs_dim, dtype=np.float32)
                obs_dict[agent_name] = current_obs
                global_state_list.append(current_obs)

                if agent_name == agent:
                    action_dict[agent_name] = action if action is not None else 0
                    reward_dict[agent_name] = reward
                else:
                    action_dict[agent_name] = 0
                    reward_dict[agent_name] = 0.0

                log_prob_dict[agent_name] = log_probs_np[i] if 'log_probs_np' in locals() else 0.0
            else:
                zero_obs = np.zeros(obs_dim, dtype=np.float32)
                obs_dict[agent_name] = zero_obs
                global_state_list.append(zero_obs)
                action_dict[agent_name] = 0
                reward_dict[agent_name] = 0.0
                log_prob_dict[agent_name] = 0.0

        # 5. Centralized Transformer Criticによる価値推定
        # 🌟 .contiguous() を追加してメモリ配置の不連続性を解消
        global_state_tensor = torch.FloatTensor(np.array(global_state_list)).unsqueeze(0).to(device).contiguous()

        for i in range(num_agents):
            agent_name = f'pursuer_{i}'
            if agent_name in env.env.agents:
                target_id_tensor = torch.tensor([i], dtype=torch.long, device=device)
                with torch.no_grad():
                    val = mappo.critic(global_state_tensor, target_id_tensor).item()
                value_dict[agent_name] = val
            else:
                value_dict[agent_name] = 0.0

        # 6. マルチエージェントバッファへ格納
        # 🌟 変更点3: 平坦化サイズは 236 * 8 = 1888 次元になります
        global_state_flat = np.array(global_state_list).flatten()  # (1888,)
        mappo.buffer.store(
            obs_dict, action_dict, reward_dict, global_state_flat,
            log_prob_dict, value_dict, terminated, truncated
        )

        if terminated or truncated:
            break

    # =====================================================================
    # エピソード終了後のネットワーク更新処理
    # =====================================================================
    reward_buffer.append(episode_reward)
    capture_buffer.append(episode_captures)

    avg_reward = np.mean(reward_buffer)
    avg_captures = np.mean(capture_buffer)

    print(f"Episode {episode}: Reward = {episode_reward:.2f}, "
          f"Captures = {episode_captures}, "
          f"Avg Reward = {avg_reward:.2f}, "
          f"Avg Captures = {avg_captures:.2f}")

    # アドバンテージ（GAE）とリターンの計算
    mappo.buffer.compute_advantages(gamma=gamma, gae_lambda=gae_lambda)

    # PPOの更新（ミニバッチサンプリング）
    actor_losses, critic_losses, entropies = [], [], []

    for _ in range(update_epochs):
        batch = mappo.buffer.sample(batch_size)
        if batch is not None:
            actor_loss, critic_loss, entropy = mappo.update(batch, epochs=1)

            actor_losses.append(actor_loss)
            critic_losses.append(critic_loss)
            entropies.append(entropy)

    if len(actor_losses) > 0:
        print(f"Actor Loss: {np.mean(actor_losses):.4f} | "
              f"Critic Loss: {np.mean(critic_losses):.4f} | "
              f"Avg Entropy: {np.mean(entropies):.4f}")

    # 次のエピソードに備えてバッファをリセット
    mappo.buffer.clear()

    # 一定間隔でチェックポイントをセーブ
    if episode % checkpoint_interval == 0 and episode > 0:
        save_checkpoint_safely(mappo, episode, checkpoint_dir=CHECKPOINT_DIR)

env.close()
print("=== MAPPO（Transformer & IDベース）学習完了 ===")

import os
import numpy as np
import torch
import imageio
from PIL import Image, ImageDraw, ImageFont

# =====================================================================
# 設定（学習コードと共通）
# =====================================================================
max_cycles = 500
CHECKPOINT_DIR = "/content/drive/MyDrive/rl_pursuit"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 🌟 行動履歴付き（obs_dim=236）に対応したラッパーで初期化（render_mode="human"）
env_wrapper = PursuitWrapper(render_mode="human", max_cycles=max_cycles)
num_agents = env_wrapper.num_agents
obs_dim = env_wrapper.obs_dim          # 🌟 自動的に 236 (196 + 40) になります
state_dim = env_wrapper.state_dim      # 🌟 自動的に 1888 (236 x 8) になります
action_dim = env_wrapper.action_dim

# フォントの設定（環境に応じてパスを調整）
try:
    font = ImageFont.truetype("arial.ttf", 20)
except:
    font = ImageFont.load_default()

# MAPPO の初期化 (内部アーキテクチャはTransformer)
mappo = MAPPO(
    num_agents=num_agents,
    obs_dim=obs_dim,
    state_dim=state_dim,
    action_dim=action_dim,
    gamma=0.99,
    gae_lambda=0.95,
    device=device
)

# 🛠️ チェックポイント復元関数の安全ラップ（学習コードと統一）
def load_checkpoint_safely(model_obj, path, device):
    try:
        checkpoint = torch.load(path, map_location=device)
        model_obj.actor.load_state_dict(checkpoint['actor_state_dict'])
        model_obj.critic.load_state_dict(checkpoint['critic_state_dict'])
        print(f"💾 チェックポイントを読み込みました (Episode {checkpoint['episode']})")
        return checkpoint['episode']
    except Exception as e:
        print(f"エラー: チェックポイントの読み込み中にエラーが発生しました: {e}")
        exit(1)

path_checkpoint = os.path.join(CHECKPOINT_DIR, "mappo_episode.pth")
if os.path.exists(path_checkpoint):
    load_checkpoint_safely(mappo, path_checkpoint, device=device)
else:
    print("エラー: チェックポイントが見つかりません。")
    exit(1)

# ネットワークを評価モードに
mappo.actor.eval()
mappo.critic.eval()

print("=== MAPPO 推論モード（Transformer & gif保存付き）開始 ===")
print(f"エージェント数: {num_agents}")
print(f"観測次元 (空間196 + 行動履歴40): {obs_dim}")
print(f"使用デバイス: {device}")

# =====================================================================
# フレーム保存用の設定
# =====================================================================
video_folder = "videos"
os.makedirs(video_folder, exist_ok=True)
frames = []  # 各ステップの画像を保存するリスト

# =====================================================================
# 推論ループ（1エピソード分）
# =====================================================================
env_wrapper.reset()
episode_reward = 0.0
episode_captures = 0

# AEC環境のループ
for agent in env_wrapper.env.agent_iter():
    # 現在アクティブなエージェントの終了フラグを取得
    _, _, terminated, truncated, _ = env_wrapper.env.last(agent)

    if terminated or truncated:
        action = None
    else:
        # 1. 全エージェントの最新236次元観測（行動履歴含む）を集約
        obs_list = []
        for i in range(num_agents):
            agent_name = f'pursuer_{i}'
            if agent_name in env_wrapper.env.agents:
                agent_obs = env_wrapper.get_obs(agent_name)
                obs_list.append(agent_obs if agent_obs is not None else np.zeros(obs_dim, dtype=np.float32))
            else:
                obs_list.append(np.zeros(obs_dim, dtype=np.float32))

        # 2. テンソル化して Transformer Actor に入力
        # 🌟 viewエラー対策として .contiguous() を追加
        obs_tensor = torch.FloatTensor(np.array(obs_list)).to(device).contiguous()

        with torch.no_grad():
            actions_np, _ = mappo.get_action(obs_tensor)

        # 現在のエージェントに対応する行動を取得
        agent_idx = int(agent.split('_')[-1])
        action = actions_np[agent_idx]

    # 3. 環境を1ステップ進める
    obs, reward, terminated, truncated, info, count_capture = env_wrapper.step(agent, action)
    episode_reward += reward

    # Pursuit環境特有の捕獲報酬(+5)をカウント
    episode_captures += count_capture if count_capture else 0

    # 🌟 4. 【最適化】1サイクル（全員分の行動が1周）終わったタイミングで画面をキャプチャ
    if agent == f'pursuer_{num_agents - 1}':
        frame = env_wrapper.render()
        if frame is not None:
            # NumPy配列をPIL Imageに変換
            pil_img = Image.fromarray(frame)

            # 描画オブジェクトを作成
            draw = ImageDraw.Draw(pil_img)

            # 右下の座標を計算（マージン10px）
            text = f"Captures: {episode_captures}"
            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]
            x = pil_img.width - text_width - 10
            y = pil_img.height - text_height - 10

            # テキストを描画（白文字＋黒縁など）
            draw.rectangle([x-2, y-2, x+text_width+2, y+text_height+2], fill="black")
            draw.text((x, y), text, fill="white", font=font)

            # PIL ImageをNumPy配列に戻して保存
            frame_with_text = np.array(pil_img)
            frames.append(frame_with_text)

    # 🌟 5. 捕獲成功判定
    if terminated and not truncated:
        # 終了ステップの最後のフレームも確実に記録
        frame = env_wrapper.render()
        if frame is not None:
            # 終了時も同様に Captures テキストを描画
            pil_img = Image.fromarray(frame)
            draw = ImageDraw.Draw(pil_img)
            text = f"Captures: {episode_captures}"
            bbox = draw.textbbox((0, 0), text, font=font)
            text_width = bbox[2] - bbox[0]
            text_height = bbox[3] - bbox[1]
            x = pil_img.width - text_width - 10
            y = pil_img.height - text_height - 10
            draw.rectangle([x-2, y-2, x+text_width+2, y+text_height+2], fill="black")
            draw.text((x, y), text, fill="white", font=font)
            frame_with_text = np.array(pil_img)
            frames.append(frame_with_text)
        break

    if truncated:
        break

print(f"推論結果: Total Hybrid Reward = {episode_reward:.2f}, Captures = {episode_captures}")

env_wrapper.env.close()
print("=== MAPPO 推論モード（フレーム収集）終了 ===")

# =====================================================================
# 収集したフレームを gif に保存
# =====================================================================
if len(frames) > 0:
    gif_path = os.path.join(video_folder, "pursuit_mappo.gif")
    print(f"gif 保存中: {gif_path} (総フレーム数: {len(frames)})")

    # フレームを gif に書き出し
    with imageio.get_writer(gif_path, fps=12) as writer:
        for frame in frames:
            writer.append_data(frame)

    print(f"gif 保存完了: {gif_path}")
else:
    print("⚠️ フレームが収集されていません。render() の戻り値を確認してください。")

print("=== gif 保存処理完了 ===")

