# -*- coding: utf-8 -*-
"""MHA_SHA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pV5Zi3JMZ2zeHohUgayDYDeWQHlk49n_
"""

# 1. 必要なライブラリのインストール
import math
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
import numpy as np

# デバイスの設定 (Colab GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ---------------------------------------------------------
# 2. カスタム Attention レイヤーの実装 (SHA vs MHA)
# ---------------------------------------------------------
class FlexibleAttention(nn.Module):
    """
    num_heads=1 の場合は SHA、num_heads > 1 の場合は MHA として振る舞うレイヤー。
    隠れ層次元 d_model とパラメータ数はどちらのヘッド数でも同等になるよう設計。
    """
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        assert self.head_dim * num_heads == d_model, "d_model must be divisible by num_heads"

        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(d_model, d_model)
        self.v_proj = nn.Linear(d_model, d_model)
        self.out_proj = nn.Linear(d_model, d_model)

    def forward(self, x, mask=None):
        batch_size, seq_len, _ = x.size()

        # (Batch, Seq_len, Num_heads, Head_dim) -> (Batch, Num_heads, Seq_len, Head_dim)
        Q = self.q_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        K = self.k_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        V = self.v_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)

        # Scaled Dot-Product Attention
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.head_dim)

        if mask is not None:
            # (Batch, 1, 1, Seq_len) の形状に拡張
            extended_mask = mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(extended_mask == 0, -1e9)

        attn_weights = torch.softmax(scores, dim=-1)
        context = torch.matmul(attn_weights, V)

        # テンソルの再結合: (Batch, Seq_len, d_model)
        context = context.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)
        return self.out_proj(context)


# ---------------------------------------------------------
# 3. WinoGrande 解答用モデル (Transformer + FlexibleAttention)
# ---------------------------------------------------------
class WinoGrandeClassifier(nn.Module):
    def __init__(self, base_model_name, num_heads):
        super().__init__()
        # BERT などの Embedding / Encoder 層を利用
        self.encoder = AutoModel.from_pretrained(base_model_name)
        d_model = self.encoder.config.hidden_size

        # 最上層の自己アテンションをカスタム Attention レイヤーに置換して検証する構成
        self.custom_attn = FlexibleAttention(d_model, num_heads=num_heads)
        self.classifier = nn.Linear(d_model, 1)

    def forward_single_option(self, input_ids, attention_mask):
        # Base encoder
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = outputs.last_hidden_state

        # カスタムアテンション層の適用
        attn_out = self.custom_attn(x, mask=attention_mask)

        # 文全体の表現として [CLS] トークン (index 0) のベクトルを抽出
        cls_rep = attn_out[:, 0, :]
        logits = self.classifier(cls_rep)
        return logits

    def forward(self, option1_ids, option1_mask, option2_ids, option2_mask):
        # option1 と option2 のスコアをそれぞれ計算
        logits1 = self.forward_single_option(option1_ids, option1_mask)
        logits2 = self.forward_single_option(option2_ids, option2_mask)
        # (Batch, 2) のロジットを結合
        return torch.cat([logits1, logits2], dim=1)


# ---------------------------------------------------------
# 4. データセットの前処理 (WinoGrande)
# ---------------------------------------------------------
MODEL_NAME = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Loading WinoGrande dataset...")
raw_dataset = load_dataset("allenai/winogrande", "winogrande_s") # 高速テスト用に xs サイズを選択 (S, M, L も指定可能)

def preprocess_function(examples):
    option1_texts = []
    option2_texts = []
    labels = []

    for sentence, opt1, opt2, answer in zip(examples["sentence"], examples["option1"], examples["option2"], examples["answer"]):
        # 虫食い部分 '_' を各選択肢で置換
        sentence_opt1 = sentence.replace("_", opt1)
        sentence_opt2 = sentence.replace("_", opt2)

        option1_texts.append(sentence_opt1)
        option2_texts.append(sentence_opt2)

        # 正解ラベル ('1' -> 0, '2' -> 1)
        labels.append(0 if answer == "1" else 1)

    enc1 = tokenizer(option1_texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    enc2 = tokenizer(option2_texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")

    return {
        "opt1_ids": enc1["input_ids"],
        "opt1_mask": enc1["attention_mask"],
        "opt2_ids": enc2["input_ids"],
        "opt2_mask": enc2["attention_mask"],
        "labels": torch.tensor(labels, dtype=torch.long)
    }

print("Preprocessing dataset...")
train_data = preprocess_function(raw_dataset["train"])
val_data = preprocess_function(raw_dataset["validation"])

# VRAMへ全テンソルを直接移動させてロード時間を大幅高速化
class VRAMDataset(torch.utils.data.Dataset):
    def __init__(self, data_dict):
        self.opt1_ids = data_dict["opt1_ids"].to(device)
        self.opt1_mask = data_dict["opt1_mask"].to(device)
        self.opt2_ids = data_dict["opt2_ids"].to(device)
        self.opt2_mask = data_dict["opt2_mask"].to(device)
        self.labels = data_dict["labels"].to(device)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return (
            self.opt1_ids[idx], self.opt1_mask[idx],
            self.opt2_ids[idx], self.opt2_mask[idx],
            self.labels[idx]
        )

train_loader = DataLoader(VRAMDataset(train_data), batch_size=16, shuffle=True)
val_loader = DataLoader(VRAMDataset(val_data), batch_size=16, shuffle=False)


# ---------------------------------------------------------
# 5. 学習・評価ループ関数
# ---------------------------------------------------------
def train_and_eval(num_heads, epochs=3, lr=2e-5):
    print(f"\n==========================================")
    print(f" Starting Experiment: num_heads = {num_heads} ({'Single-Head' if num_heads==1 else 'Multi-Head'})")
    print(f"==========================================")

    model = WinoGrandeClassifier(MODEL_NAME, num_heads=num_heads).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        total_loss = 0.0

        for batch in train_loader:
            opt1_ids, opt1_mask, opt2_ids, opt2_mask, labels = batch

            optimizer.zero_grad()
            logits = model(opt1_ids, opt1_mask, opt2_ids, opt2_mask)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        # Validation
        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for batch in val_loader:
                opt1_ids, opt1_mask, opt2_ids, opt2_mask, labels = batch
                logits = model(opt1_ids, opt1_mask, opt2_ids, opt2_mask)
                preds = torch.argmax(logits, dim=1)
                correct += (preds == labels).sum().item()
                total += labels.size(0)

        val_acc = correct / total
        avg_train_loss = total_loss / len(train_loader)
        print(f"Epoch {epoch+1}/{epochs} | Train Loss: {avg_train_loss:.4f} | Val Accuracy: {val_acc:.4f}")

    return val_acc


# ---------------------------------------------------------
# 6. SHA vs MHA の比較実行
# ---------------------------------------------------------
# 1. Single-Head Attention (h=1)
sha_accuracy = train_and_eval(num_heads=1, epochs=3)

# 2. Multi-Head Attention (h=12)
mha_accuracy = train_and_eval(num_heads=12, epochs=3)

print("\n================ FINAL RESULT ================")
print(f"Single-Head Attention (h=1)  Val Accuracy: {sha_accuracy:.4f}")
print(f"Multi-Head Attention  (h=12) Val Accuracy: {mha_accuracy:.4f}")
print("==============================================")

import matplotlib.pyplot as plt

# 実験結果を手動で入力（ログからコピー）
results = {
    "num_heads=1": {
        "epochs": [1, 2, 3],
        "train_loss": [0.6929, 0.6914, 0.6955],
        "val_accuracy": [0.5146, 0.5264, 0.4917],
    },
    "num_heads=12": {
        "epochs": [1, 2, 3],
        "train_loss": [0.6935, 0.6948, 0.6933],
        "val_accuracy": [0.5193, 0.5296, 0.5099],
    },
}

# グラフ描画
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

# Train Loss
for label, data in results.items():
    ax1.plot(data["epochs"], data["train_loss"], marker="o", label=label)
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Train Loss")
ax1.set_title("Train Loss vs Epoch")
ax1.legend()
ax1.grid(True, linestyle="--", alpha=0.7)

# Validation Accuracy
for label, data in results.items():
    ax2.plot(data["epochs"], data["val_accuracy"], marker="o", label=label)
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Val Accuracy")
ax2.set_title("Validation Accuracy vs Epoch")
ax2.legend()
ax2.grid(True, linestyle="--", alpha=0.7)

plt.tight_layout()
plt.show()

# 1. 必要なライブラリのインストール
import math
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModel
from datasets import load_dataset
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# デバイスの設定 (Colab GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# ---------------------------------------------------------
# 2. カスタム Attention レイヤーの実装 (SHA vs MHA)
# ---------------------------------------------------------
class FlexibleAttention(nn.Module):
    """
    num_heads=1 の場合は SHA、num_heads > 1 の場合は MHA として振る舞うレイヤー。
    隠れ層次元 d_model とパラメータ数はどちらのヘッド数でも同等になるよう設計。
    """
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.d_model = d_model
        self.num_heads = num_heads
        self.head_dim = d_model // num_heads
        assert self.head_dim * num_heads == d_model, "d_model must be divisible by num_heads"

        self.q_proj = nn.Linear(d_model, d_model)
        self.k_proj = nn.Linear(d_model, d_model)
        self.v_proj = nn.Linear(d_model, d_model)
        self.out_proj = nn.Linear(d_model, d_model)

    def forward(self, x, mask=None):
        batch_size, seq_len, _ = x.size()

        # (Batch, Seq_len, Num_heads, Head_dim) -> (Batch, Num_heads, Seq_len, Head_dim)
        Q = self.q_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        K = self.k_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        V = self.v_proj(x).view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)

        # Scaled Dot-Product Attention
        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(self.head_dim)

        if mask is not None:
            # (Batch, 1, 1, Seq_len) の形状に拡張
            extended_mask = mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(extended_mask == 0, -1e9)

        attn_weights = torch.softmax(scores, dim=-1)
        context = torch.matmul(attn_weights, V)

        # テンソルの再結合: (Batch, Seq_len, d_model)
        context = context.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)
        return self.out_proj(context)


# ---------------------------------------------------------
# 3. WinoGrande 解答用モデル (Transformer + FlexibleAttention)
# ---------------------------------------------------------
class WinoGrandeClassifier(nn.Module):
    def __init__(self, base_model_name, num_heads):
        super().__init__()
        # BERT などの Embedding / Encoder 層を利用
        self.encoder = AutoModel.from_pretrained(base_model_name)
        d_model = self.encoder.config.hidden_size

        # 最上層の自己アテンションをカスタム Attention レイヤーに置換して検証する構成
        self.custom_attn = FlexibleAttention(d_model, num_heads=num_heads)
        self.classifier = nn.Linear(d_model, 1)

    def forward_single_option(self, input_ids, attention_mask):
        # Base encoder
        outputs = self.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = outputs.last_hidden_state

        # カスタムアテンション層の適用
        attn_out = self.custom_attn(x, mask=attention_mask)

        # 文全体の表現として [CLS] トークン (index 0) のベクトルを抽出
        cls_rep = attn_out[:, 0, :]
        logits = self.classifier(cls_rep)
        return logits

    def forward(self, option1_ids, option1_mask, option2_ids, option2_mask):
        # option1 と option2 のスコアをそれぞれ計算
        logits1 = self.forward_single_option(option1_ids, option1_mask)
        logits2 = self.forward_single_option(option2_ids, option2_mask)
        # (Batch, 2) のロジットを結合
        return torch.cat([logits1, logits2], dim=1)


# ---------------------------------------------------------
# 4. データセットの前処理 (WinoGrande)
# ---------------------------------------------------------
MODEL_NAME = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("Loading WinoGrande dataset...")
raw_dataset = load_dataset("allenai/winogrande", "winogrande_s")

def preprocess_function(examples):
    option1_texts = []
    option2_texts = []
    labels = []

    for sentence, opt1, opt2, answer in zip(examples["sentence"], examples["option1"], examples["option2"], examples["answer"]):
        # 虫食い部分 '_' を各選択肢で置換
        sentence_opt1 = sentence.replace("_", opt1)
        sentence_opt2 = sentence.replace("_", opt2)

        option1_texts.append(sentence_opt1)
        option2_texts.append(sentence_opt2)

        # 正解ラベル ('1' -> 0, '2' -> 1)
        labels.append(0 if answer == "1" else 1)

    enc1 = tokenizer(option1_texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")
    enc2 = tokenizer(option2_texts, padding="max_length", truncation=True, max_length=128, return_tensors="pt")

    return {
        "opt1_ids": enc1["input_ids"],
        "opt1_mask": enc1["attention_mask"],
        "opt2_ids": enc2["input_ids"],
        "opt2_mask": enc2["attention_mask"],
        "labels": torch.tensor(labels, dtype=torch.long)
    }

print("Preprocessing dataset...")
train_data = preprocess_function(raw_dataset["train"])
val_data = preprocess_function(raw_dataset["validation"])

# VRAMへ全テンソルを直接移動させてロード時間を大幅高速化
class VRAMDataset(torch.utils.data.Dataset):
    def __init__(self, data_dict):
        self.opt1_ids = data_dict["opt1_ids"].to(device)
        self.opt1_mask = data_dict["opt1_mask"].to(device)
        self.opt2_ids = data_dict["opt2_ids"].to(device)
        self.opt2_mask = data_dict["opt2_mask"].to(device)
        self.labels = data_dict["labels"].to(device)

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return (
            self.opt1_ids[idx], self.opt1_mask[idx],
            self.opt2_ids[idx], self.opt2_mask[idx],
            self.labels[idx]
        )

train_loader = DataLoader(VRAMDataset(train_data), batch_size=16, shuffle=True)
val_loader = DataLoader(VRAMDataset(val_data), batch_size=16, shuffle=False)


# ---------------------------------------------------------
# 5. 学習・評価ループ関数（モデルオブジェクトを返却するよう修正）
# ---------------------------------------------------------
def train_and_eval(num_heads, epochs=3, lr=2e-5):
    print(f"\n==========================================")
    print(f" Starting Experiment: num_heads = {num_heads} ({'Single-Head' if num_heads==1 else 'Multi-Head'})")
    print(f"==========================================")

    model = WinoGrandeClassifier(MODEL_NAME, num_heads=num_heads).to(device)
    optimizer = torch.optim.AdamW(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(epochs):
        model.train()
        total_loss = 0.0

        for batch in train_loader:
            opt1_ids, opt1_mask, opt2_ids, opt2_mask, labels = batch

            optimizer.zero_grad()
            logits = model(opt1_ids, opt1_mask, opt2_ids, opt2_mask)
            loss = criterion(logits, labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        # Validation
        model.eval()
        correct = 0
        total = 0
        with torch.no_grad():
            for batch in val_loader:
                opt1_ids, opt1_mask, opt2_ids, opt2_mask, labels = batch
                logits = model(opt1_ids, opt1_mask, opt2_ids, opt2_mask)
                preds = torch.argmax(logits, dim=1)
                correct += (preds == labels).sum().item()
                total += labels.size(0)

        val_acc = correct / total
        avg_train_loss = total_loss / len(train_loader)
        print(f"Epoch {epoch+1}/{epochs} | Train Loss: {avg_train_loss:.4f} | Val Accuracy: {val_acc:.4f}")

    # 学習済みモデルと最終精度を返す
    return model, val_acc


# ---------------------------------------------------------
# 6. SHA vs MHA の比較実行とモデルの保持
# ---------------------------------------------------------
# 1. Single-Head Attention (h=1)
sha_model, sha_accuracy = train_and_eval(num_heads=1, epochs=3)

# 2. Multi-Head Attention (h=12)
mha_model, mha_accuracy = train_and_eval(num_heads=12, epochs=3)

print("\n================ FINAL RESULT ================")
print(f"Single-Head Attention (h=1)  Val Accuracy: {sha_accuracy:.4f}")
print(f"Multi-Head Attention  (h=12) Val Accuracy: {mha_accuracy:.4f}")
print("==============================================")

# ---------------------------------------------------------
# 7. 学習済みモデルを用いたアテンションマップの可視化
# ---------------------------------------------------------
def get_attention_matrix(model, text, tokenizer):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0])

    with torch.no_grad():
        encoder_outputs = model.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = encoder_outputs.last_hidden_state

        batch_size, seq_len, _ = x.size()
        head_dim = model.custom_attn.head_dim
        num_heads = model.custom_attn.num_heads

        Q = model.custom_attn.q_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)
        K = model.custom_attn.k_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(head_dim)
        if attention_mask is not None:
            extended_mask = attention_mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(extended_mask == 0, -1e9)

        attn_weights = torch.softmax(scores, dim=-1)

    return attn_weights[0].cpu().numpy(), tokens


def plot_attention_comparison(sha_model, mha_model, text, tokenizer):
    sha_attn, tokens = get_attention_matrix(sha_model, text, tokenizer)
    mha_attn, _ = get_attention_matrix(mha_model, text, tokenizer)

    # RoBERTaのトークンプレフィックス「Ġ」をクリーン化
    clean_tokens = [t.replace("Ġ", "").replace("##", "") for t in tokens]

    fig, axes = plt.subplots(1, 3, figsize=(22, 6))

    # SHA (Head 0)
    sns.heatmap(
        sha_attn[0],
        xticklabels=clean_tokens,
        yticklabels=clean_tokens,
        cmap="viridis",
        ax=axes[0],
        cbar=True
    )
    axes[0].set_title("Single-Head Attention (h=1, Head 0)", fontsize=14)
    axes[0].set_ylabel("Query (Focusing From)", fontsize=12)
    axes[0].set_xlabel("Key (Attending To)", fontsize=12)
    axes[0].tick_params(axis='x', rotation=90)

    # MHA (Head 0)
    sns.heatmap(
        mha_attn[0],
        xticklabels=clean_tokens,
        yticklabels=clean_tokens,
        cmap="viridis",
        ax=axes[1],
        cbar=True
    )
    axes[1].set_title("Multi-Head Attention (h=12, Head 0)", fontsize=14)
    axes[1].set_xlabel("Key (Attending To)", fontsize=12)
    axes[1].tick_params(axis='x', rotation=90)

    # MHA (Head 5)
    sns.heatmap(
        mha_attn[5],
        xticklabels=clean_tokens,
        yticklabels=clean_tokens,
        cmap="viridis",
        ax=axes[2],
        cbar=True
    )
    axes[2].set_title("Multi-Head Attention (h=12, Head 5)", fontsize=14)
    axes[2].set_xlabel("Key (Attending To)", fontsize=12)
    axes[2].tick_params(axis='x', rotation=90)

    plt.suptitle(f"Attention Map Analysis\nInput: \"{text}\"", fontsize=16, y=1.05)
    plt.tight_layout()
    plt.show()

# テスト文章でヒートマップを出力
sample_text = "The trophy does not fit in the brown suitcase because it is too large."
plot_attention_comparison(sha_model, mha_model, sample_text, tokenizer)

# ---------------------------------------------------------
# 7. 学習済みモデルを用いたアテンションマップの可視化 (拡張版)
# ---------------------------------------------------------
def get_attention_matrix(model, text, tokenizer):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0])

    with torch.no_grad():
        encoder_outputs = model.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = encoder_outputs.last_hidden_state

        batch_size, seq_len, _ = x.size()
        head_dim = model.custom_attn.head_dim
        num_heads = model.custom_attn.num_heads

        Q = model.custom_attn.q_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)
        K = model.custom_attn.k_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(head_dim)
        if attention_mask is not None:
            extended_mask = attention_mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(extended_mask == 0, -1e9)

        attn_weights = torch.softmax(scores, dim=-1)

    return attn_weights[0].cpu().numpy(), tokens


def plot_mha_all_heads(mha_model, text, tokenizer):
    """
    MHAの全12ヘッドのアテンションマップを3x4グリッドで一括表示し、
    ヘッドごとの役割分担（パターン差）を俯瞰確認する関数
    """
    mha_attn, tokens = get_attention_matrix(mha_model, text, tokenizer)
    clean_tokens = [t.replace("Ġ", "").replace("##", "") for t in tokens]
    num_heads = mha_attn.shape[0]

    rows, cols = 3, 4
    fig, axes = plt.subplots(rows, cols, figsize=(24, 16))
    axes = axes.flatten()

    for h in range(num_heads):
        sns.heatmap(
            mha_attn[h],
            xticklabels=clean_tokens,
            yticklabels=clean_tokens,
            cmap="viridis",
            ax=axes[h],
            cbar=False,
            square=True
        )
        axes[h].set_title(f"Head {h}", fontsize=12, fontweight="bold")
        axes[h].tick_params(axis='x', rotation=90, labelsize=8)
        axes[h].tick_params(axis='y', rotation=0, labelsize=8)

    plt.suptitle(f"MHA All 12 Heads Attention Overview\nInput: \"{text}\"", fontsize=16, y=1.01)
    plt.tight_layout()
    plt.show()


def plot_attention_detailed_comparison(sha_model, mha_model, text, tokenizer, selected_mha_heads=[0, 3, 7, 11]):
    """
    SHA (h=1) と、MHAの中から特徴的な複数のヘッドを抽出して横並び比較する関数
    """
    sha_attn, tokens = get_attention_matrix(sha_model, text, tokenizer)
    mha_attn, _ = get_attention_matrix(mha_model, text, tokenizer)
    clean_tokens = [t.replace("Ġ", "").replace("##", "") for t in tokens]

    num_plots = 1 + len(selected_mha_heads)
    fig, axes = plt.subplots(1, num_plots, figsize=(5 * num_plots, 5))

    # SHA (Head 0)
    sns.heatmap(
        sha_attn[0],
        xticklabels=clean_tokens,
        yticklabels=clean_tokens,
        cmap="viridis",
        ax=axes[0],
        cbar=True,
        square=True
    )
    axes[0].set_title("SHA (h=1)\nHead 0", fontsize=12, fontweight="bold")
    axes[0].set_ylabel("Query (From)", fontsize=10)
    axes[0].set_xlabel("Key (To)", fontsize=10)
    axes[0].tick_params(axis='x', rotation=90, labelsize=8)
    axes[0].tick_params(axis='y', rotation=0, labelsize=8)

    # 選択した MHA ヘッド群
    for idx, head_idx in enumerate(selected_mha_heads):
        ax = axes[idx + 1]
        sns.heatmap(
            mha_attn[head_idx],
            xticklabels=clean_tokens,
            yticklabels=clean_tokens,
            cmap="viridis",
            ax=ax,
            cbar=True,
            square=True
        )
        ax.set_title(f"MHA (h=12)\nHead {head_idx}", fontsize=12, fontweight="bold")
        ax.set_xlabel("Key (To)", fontsize=10)
        ax.tick_params(axis='x', rotation=90, labelsize=8)
        ax.tick_params(axis='y', rotation=0, labelsize=8)

    plt.suptitle(f"Attention Pattern Comparison: SHA vs Multiple MHA Heads\nInput: \"{text}\"", fontsize=14, y=1.05)
    plt.tight_layout()
    plt.show()


# ---------------------------------------------------------
# 可視化の実行
# ---------------------------------------------------------
sample_text = "The trophy does not fit in the brown suitcase because it is too large."

# 1. MHAの全12ヘッドを一括表示（パターン全体の差異を確認）
plot_mha_all_heads(mha_model, sample_text, tokenizer)

# 2. SHA と MHAから選択した代表的な4ヘッドを抽出して精細比較
plot_attention_detailed_comparison(sha_model, mha_model, sample_text, tokenizer, selected_mha_heads=[0, 3, 7, 11])

import matplotlib.pyplot as plt

# ログから抽出した結果を辞書に整理
results = {
    "Single-Head (h=1)": {
        "epochs": [1, 2, 3],
        "train_loss": [0.6934, 0.6935, 0.6930],
        "val_accuracy": [0.4893, 0.4878, 0.5099],
    },
    "Multi-Head (h=12)": {
        "epochs": [1, 2, 3],
        "train_loss": [0.6934, 0.6932, 0.6917],
        "val_accuracy": [0.5012, 0.5059, 0.5312],
    },
}

# グラフ描画
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))

# Train Loss の推移
for label, data in results.items():
    ax1.plot(data["epochs"], data["train_loss"], marker="o", label=label)
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Train Loss")
ax1.set_title("Train Loss vs Epoch")
ax1.legend()
ax1.grid(True, linestyle="--", alpha=0.7)

# Validation Accuracy の推移
for label, data in results.items():
    ax2.plot(data["epochs"], data["val_accuracy"], marker="o", label=label)
ax2.set_xlabel("Epoch")
ax2.set_ylabel("Val Accuracy")
ax2.set_title("Validation Accuracy vs Epoch")
ax2.legend()
ax2.grid(True, linestyle="--", alpha=0.7)

plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# 8. 指標（Metric）による SHA vs MHA の定量分析
# ---------------------------------------------------------
import torch.nn.functional as F

def calculate_attention_metrics(model, text, tokenizer):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    with torch.no_grad():
        encoder_outputs = model.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = encoder_outputs.last_hidden_state

        batch_size, seq_len, _ = x.size()
        head_dim = model.custom_attn.head_dim
        num_heads = model.custom_attn.num_heads

        Q = model.custom_attn.q_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)
        K = model.custom_attn.k_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(head_dim)
        if attention_mask is not None:
            extended_mask = attention_mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(extended_mask == 0, -1e9)

        attn = torch.softmax(scores, dim=-1)[0] # (num_heads, seq_len, seq_len)

    # 1. アテンションのエントロピー（集中度）
    # H = - sum(p * log2(p))  (アンダーフロー防止に 1e-9 を加算)
    entropy_per_token = -torch.sum(attn * torch.log2(attn + 1e-9), dim=-1) # (num_heads, seq_len)
    mean_entropy = entropy_per_token.mean(dim=-1) # (num_heads,)

    # 2. ヘッド間コサイン類似度（ヘッド間の多様性: MHAのみ計算可能）
    diversity_matrix = None
    if num_heads > 1:
        # (num_heads, seq_len * seq_len) にフラット化
        flat_attn = attn.view(num_heads, -1)
        # L2正規化
        flat_attn_norm = F.normalize(flat_attn, p=2, dim=1)
        # ヘッド同士のコサイン類似度行列
        diversity_matrix = torch.mm(flat_attn_norm, flat_attn_norm.t()).cpu().numpy()

    # 3. 対角成分（局所集中）率
    seq_range = torch.arange(seq_len, device=device)
    diag_mask = torch.abs(seq_range.unsqueeze(0) - seq_range.unsqueeze(1)) <= 1 # |i-j| <= 1
    diagonal_ratio = (attn * diag_mask.unsqueeze(0)).sum(dim=[-1, -2]) / seq_len # (num_heads,)

    return {
        "num_heads": num_heads,
        "mean_entropy": mean_entropy.cpu().numpy(),
        "diagonal_ratio": diagonal_ratio.cpu().numpy(),
        "diversity_matrix": diversity_matrix
    }

# 指標の計算
sample_text = "Although Dr. Smith spent weeks meticulously analyzing the extremely complicated financial report, he completely missed the critical calculation error until Sarah pointed out the wrong number on page forty two."
sha_metrics = calculate_attention_metrics(sha_model, sample_text, tokenizer)
mha_metrics = calculate_attention_metrics(mha_model, sample_text, tokenizer)

# ---------------------------------------------------------
# 結果の可視化と出力
# ---------------------------------------------------------
print("================ METRICS ANALYSIS ================")
print(f"SHA (h=1)  - Mean Entropy: {sha_metrics['mean_entropy'][0]:.4f} (Bits)")
print(f"MHA (h=12) - Mean Entropy (Across All Heads): {mha_metrics['mean_entropy'].mean():.4f} (Bits)")
print(f"MHA (h=12) - Min Entropy (Most Sharp Head):   {mha_metrics['mean_entropy'].min():.4f} (Bits)")
print(f"MHA (h=12) - Max Entropy (Most Diffuse Head): {mha_metrics['mean_entropy'].max():.4f} (Bits)")

# MHAのヘッド間類似度の平均値（自身を除くペア）
div_mat = mha_metrics["diversity_matrix"]
mask_off_diag = ~np.eye(div_mat.shape[0], dtype=bool)
avg_head_sim = div_mat[mask_off_diag].mean()
print(f"MHA (h=12) - Average Inter-Head Cosine Similarity: {avg_head_sim:.4f} (0=完全独立, 1=完全同一)")
print("==================================================")

# グラフによる比較表示
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 1. 各ヘッドのエントロピー（SHA vs MHA 各ヘッド）
axes[0].bar(range(12), mha_metrics["mean_entropy"], color="skyblue", label="MHA Heads")
axes[0].axhline(sha_metrics["mean_entropy"][0], color="red", linestyle="--", label="SHA (h=1)")
axes[0].set_xlabel("Head Index")
axes[0].set_ylabel("Entropy (Bits)")
axes[0].set_title("1. Attention Entropy (Lower = Sharper Focus)")
axes[0].legend()

# 2. 各ヘッドの局所集中率（Diagonal Ratio）
axes[1].bar(range(12), mha_metrics["diagonal_ratio"], color="lightgreen", label="MHA Heads")
axes[1].axhline(sha_metrics["diagonal_ratio"][0], color="red", linestyle="--", label="SHA (h=1)")
axes[1].set_xlabel("Head Index")
axes[1].set_ylabel("Local Focus Ratio")
axes[1].set_title("2. Local Focus Ratio (Diagonal Alignment)")
axes[1].legend()

# 3. MHA ヘッド間類似度行列（ヒートマップ）
sns.heatmap(mha_metrics["diversity_matrix"], cmap="magma", ax=axes[2], square=True, cbar=True)
axes[2].set_title("3. MHA Head-to-Head Cosine Similarity\n(Lower = Higher Role Separation)")
axes[2].set_xlabel("Head Index")
axes[2].set_ylabel("Head Index")

plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# 特殊トークン(<s>, </s>)を除外して純粋な単語間アテンションを抽出
# ---------------------------------------------------------
def get_clean_attention_matrix(model, text, tokenizer):
    model.eval()
    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0])

    with torch.no_grad():
        encoder_outputs = model.encoder(input_ids=input_ids, attention_mask=attention_mask)
        x = encoder_outputs.last_hidden_state

        batch_size, seq_len, _ = x.size()
        head_dim = model.custom_attn.head_dim
        num_heads = model.custom_attn.num_heads

        Q = model.custom_attn.q_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)
        K = model.custom_attn.k_proj(x).view(batch_size, seq_len, num_heads, head_dim).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / math.sqrt(head_dim)
        if attention_mask is not None:
            extended_mask = attention_mask.unsqueeze(1).unsqueeze(2)
            scores = scores.masked_fill(extended_mask == 0, -1e9)

        attn_weights = torch.softmax(scores, dim=-1)

    # --- ここがポイント: <s> (index 0) と </s> (最後のトークン) をスライスして除去 ---
    # 実際の単語部分のみ抽出 (1 :-1)
    clean_attn = attn_weights[0, :, 1:-1, 1:-1] # Shape: (num_heads, seq_len-2, seq_len-2)
    clean_tokens = [t.replace("Ġ", "").replace("##", "") for t in tokens[1:-1]]

    # 除去後の行（Row）ごとにアテンションを1.0に再正規化（Softmaxし直し）
    clean_attn = clean_attn / (clean_attn.sum(dim=-1, keepdim=True) + 1e-9)

    return clean_attn.cpu().numpy(), clean_tokens


def plot_mha_all_heads_clean(mha_model, text, tokenizer):
    mha_attn, clean_tokens = get_clean_attention_matrix(mha_model, text, tokenizer)
    num_heads = mha_attn.shape[0]

    rows, cols = 3, 4
    fig, axes = plt.subplots(rows, cols, figsize=(24, 18))
    axes = axes.flatten()

    for h in range(num_heads):
        sns.heatmap(
            mha_attn[h],
            xticklabels=clean_tokens,
            yticklabels=clean_tokens,
            cmap="viridis",
            ax=axes[h],
            cbar=False,
            square=True
        )
        axes[h].set_title(f"Head {h}", fontsize=12, fontweight="bold")
        axes[h].tick_params(axis='x', rotation=90, labelsize=7)
        axes[h].tick_params(axis='y', rotation=0, labelsize=7)

    plt.suptitle(f"MHA All 12 Heads (Excluding Special Tokens)\nInput: \"{text}\"", fontsize=16, y=1.01)
    plt.tight_layout()
    plt.show()

# ---------------------------------------------------------
# 実行テスト
# ---------------------------------------------------------
heavy_text = "Although Dr. Smith spent weeks meticulously analyzing the extremely complicated financial report, he completely missed the critical calculation error until Sarah pointed out the wrong number on page forty two."

# 特殊トークンを除外した全12ヘッドの可視化を実行
plot_mha_all_heads_clean(mha_model, heavy_text, tokenizer)

# ---------------------------------------------------------
# 特殊トークン除外版：指標計算関数
# ---------------------------------------------------------
def calculate_clean_attention_metrics(model, text, tokenizer):
    clean_attn, clean_tokens = get_clean_attention_matrix(model, text, tokenizer)
    # clean_attn shape: (num_heads, seq_len, seq_len)

    num_heads, seq_len, _ = clean_attn.shape
    attn_tensor = torch.tensor(clean_attn)

    # 1. アテンションのエントロピー（シャープさ/ボヤけ具合）
    # H = - sum(p * log2(p))
    entropy_per_token = -torch.sum(attn_tensor * torch.log2(attn_tensor + 1e-9), dim=-1) # (num_heads, seq_len)
    mean_entropy = entropy_per_token.mean(dim=-1).numpy() # (num_heads,)

    # 2. ヘッド間コサイン類似度（ヘッド間の多様性 / 役割分担の独立性）
    diversity_matrix = None
    if num_heads > 1:
        flat_attn = attn_tensor.view(num_heads, -1)
        flat_attn_norm = F.normalize(flat_attn, p=2, dim=1)
        diversity_matrix = torch.mm(flat_attn_norm, flat_attn_norm.t()).numpy()

    # 3. 対角成分（局所・隣接トークンへの注目）率: |i - j| <= 1
    seq_range = torch.arange(seq_len)
    diag_mask = torch.abs(seq_range.unsqueeze(0) - seq_range.unsqueeze(1)) <= 1 # |i-j| <= 1
    diagonal_ratio = (attn_tensor * diag_mask.unsqueeze(0)).sum(dim=[-1, -2]).numpy() / seq_len

    return {
        "num_heads": num_heads,
        "tokens": clean_tokens,
        "mean_entropy": mean_entropy,
        "diagonal_ratio": diagonal_ratio,
        "diversity_matrix": diversity_matrix
    }

# ---------------------------------------------------------
# 長文を用いた定量的評価の実行
# ---------------------------------------------------------
heavy_text = "Although Dr. Smith spent weeks meticulously analyzing the extremely complicated financial report, he completely missed the critical calculation error until Sarah pointed out the wrong number on page forty two."

sha_clean_metrics = calculate_clean_attention_metrics(sha_model, heavy_text, tokenizer)
mha_clean_metrics = calculate_clean_attention_metrics(mha_model, heavy_text, tokenizer)

# 数値結果のプリント
print("================ CLEAN METRICS ANALYSIS (Excluding Special Tokens) ================")
print(f"SHA (h=1)  - Mean Entropy: {sha_clean_metrics['mean_entropy'][0]:.4f} (Bits)")
print(f"MHA (h=12) - Mean Entropy (Across All Heads): {mha_clean_metrics['mean_entropy'].mean():.4f} (Bits)")
print(f"MHA (h=12) - Min Entropy (Most Focused Head): {mha_clean_metrics['mean_entropy'].min():.4f} (Bits)")
print(f"MHA (h=12) - Max Entropy (Most Diffuse Head): {mha_clean_metrics['mean_entropy'].max():.4f} (Bits)")

div_mat = mha_clean_metrics["diversity_matrix"]
mask_off_diag = ~np.eye(div_mat.shape[0], dtype=bool)
avg_head_sim = div_mat[mask_off_diag].mean()
print(f"MHA (h=12) - Average Inter-Head Cosine Similarity: {avg_head_sim:.4f} (0=完全独立, 1=完全同一)")
print("==================================================================================")

# ---------------------------------------------------------
# グラフ可視化
# ---------------------------------------------------------
fig, axes = plt.subplots(1, 3, figsize=(20, 5))

# 1. 各ヘッドのエントロピー（SHA vs MHA 各ヘッド）
axes[0].bar(range(12), mha_clean_metrics["mean_entropy"], color="#4C72B0", label="MHA Heads")
axes[0].axhline(sha_clean_metrics["mean_entropy"][0], color="#C44E52", linestyle="--", linewidth=2, label="SHA (h=1)")
axes[0].set_xlabel("Head Index", fontsize=11)
axes[0].set_ylabel("Entropy (Bits)", fontsize=11)
axes[0].set_title("1. Attention Entropy\n(Lower = Sharper & Focused)", fontsize=12, fontweight="bold")
axes[0].legend()

# 2. 局所集中率（対角成分比率）
axes[1].bar(range(12), mha_clean_metrics["diagonal_ratio"], color="#55A868", label="MHA Heads")
axes[1].axhline(sha_clean_metrics["diagonal_ratio"][0], color="#C44E52", linestyle="--", linewidth=2, label="SHA (h=1)")
axes[1].set_xlabel("Head Index", fontsize=11)
axes[1].set_ylabel("Local Focus Ratio (|i-j|<=1)", fontsize=11)
axes[1].set_title("2. Local Focus Ratio\n(High = Syntax / Local Alignment)", fontsize=12, fontweight="bold")
axes[1].legend()

# 3. MHA ヘッド間コサイン類似度行列
sns.heatmap(mha_clean_metrics["diversity_matrix"], cmap="viridis", ax=axes[2], square=True, cbar=True, vmin=0, vmax=1)
axes[2].set_title("3. MHA Head-to-Head Cosine Similarity\n(Low Off-Diagonal = High Diversity)", fontsize=12, fontweight="bold")
axes[2].set_xlabel("Head Index", fontsize=11)
axes[2].set_ylabel("Head Index", fontsize=11)

plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# RoBERTa 本体の事前学習済みアテンションをそのまま抽出して評価
# ---------------------------------------------------------
def get_pretrained_roberta_clean_metrics(text, tokenizer, model_name="roberta-base"):
    # 本体の RoBERTa をロード（output_attentions=True を指定）
    pretrained_model = AutoModel.from_pretrained(model_name, output_attentions=True).to(device)
    pretrained_model.eval()

    inputs = tokenizer(text, return_tensors="pt", truncation=True, max_length=128).to(device)
    input_ids = inputs["input_ids"]
    attention_mask = inputs["attention_mask"]

    tokens = tokenizer.convert_ids_to_tokens(input_ids[0])

    with torch.no_grad():
        outputs = pretrained_model(input_ids=input_ids, attention_mask=attention_mask)
        # 最終レイヤー (Layer 11) のアテンションマップを取得
        # outputs.attentions の形状: (num_layers, batch_size, num_heads, seq_len, seq_len)
        last_layer_attn = outputs.attentions[-1][0] # (12, seq_len, seq_len)

    # <s> と </s> を除去
    clean_attn = last_layer_attn[:, 1:-1, 1:-1]
    clean_tokens = [t.replace("Ġ", "").replace("##", "") for t in tokens[1:-1]]

    # 行ごとに再正規化
    clean_attn = clean_attn / (clean_attn.sum(dim=-1, keepdim=True) + 1e-9)

    num_heads, seq_len, _ = clean_attn.shape

    # 1. エントロピー
    entropy_per_token = -torch.sum(clean_attn * torch.log2(clean_attn + 1e-9), dim=-1)
    mean_entropy = entropy_per_token.mean(dim=-1).cpu().numpy()

    # 2. ヘッド間コサイン類似度
    flat_attn = clean_attn.view(num_heads, -1)
    flat_attn_norm = F.normalize(flat_attn, p=2, dim=1)
    diversity_matrix = torch.mm(flat_attn_norm, flat_attn_norm.t()).cpu().numpy()

    # 3. 局所集中率 (|i - j| <= 1)
    seq_range = torch.arange(seq_len, device=device)
    diag_mask = torch.abs(seq_range.unsqueeze(0) - seq_range.unsqueeze(1)) <= 1
    diagonal_ratio = (clean_attn * diag_mask.unsqueeze(0)).sum(dim=[-1, -2]).cpu().numpy() / seq_len

    return {
        "tokens": clean_tokens,
        "mean_entropy": mean_entropy,
        "diagonal_ratio": diagonal_ratio,
        "diversity_matrix": diversity_matrix
    }

# 実行
pretrained_metrics = get_pretrained_roberta_clean_metrics(heavy_text, tokenizer)

print("\n================ PRETRAINED RoBERTa (Layer 11) METRICS ================")
print(f"Mean Entropy Across Heads: {pretrained_metrics['mean_entropy'].mean():.4f} (Bits)")
print(f"Min Entropy (Most Focused): {pretrained_metrics['mean_entropy'].min():.4f} (Bits)")
print(f"Max Entropy (Most Diffuse): {pretrained_metrics['mean_entropy'].max():.4f} (Bits)")

div_mat = pretrained_metrics["diversity_matrix"]
mask_off_diag = ~np.eye(div_mat.shape[0], dtype=bool)
avg_head_sim = div_mat[mask_off_diag].mean()
print(f"Average Inter-Head Cosine Similarity: {avg_head_sim:.4f}")
print("=======================================================================")

