name: Generate and Deploy Sitemap

on:
  push:
    branches:
      - main

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # sitemap.xml を直接生成
      - name: Generate sitemap.xml manually
        run: |
          cat << 'EOF' > sitemap.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
            <url>
              <loc>https://shinichi0713.github.io/LLM-fundamental-study/</loc>
            </url>
            <url>
              <loc>https://shinichi0713.github.io/LLM-fundamental-study/attention/doc/1-query_mha.html</loc>
            </url>
          </urlset>
          EOF

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sitemap.xml
          git commit -m "docs: generate sitemap.xml" || echo "No changes"
          git push
