# -*- coding: utf-8 -*-
"""GRU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17b5V_7Mxuoznq9CzPlXG7tmdWzDGmue7
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("imdb")
train_data = dataset["train"]
test_data = dataset["test"]

import re
from collections import Counter

def basic_tokenizer(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return text.split()

counter = Counter()
for item in train_data:
    counter.update(basic_tokenizer(item["text"]))

vocab = {"<pad>": 0, "<unk>": 1}
for word, _ in counter.most_common(20000):
    vocab[word] = len(vocab)

def encode(text):
    return [vocab.get(tok, vocab["<unk>"]) for tok in basic_tokenizer(text)]

import torch
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import DataLoader

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def collate_fn(batch):
    xs, ys = [], []
    for item in batch:
        xs.append(torch.tensor(encode(item["text"]), dtype=torch.long))
        ys.append(1 if item["label"] == 1 else 0)
    xs = pad_sequence(xs, batch_first=True, padding_value=vocab["<pad>"])
    ys = torch.tensor(ys, dtype=torch.long)
    return xs.to(device), ys.to(device)

train_loader = DataLoader(train_data, batch_size=32, shuffle=True, collate_fn=collate_fn)
test_loader  = DataLoader(test_data,  batch_size=32, shuffle=False, collate_fn=collate_fn)

import torch.nn as nn

class GRUClassifier(nn.Module):
    def __init__(self, vocab_size, embed_dim=128, hidden_dim=128):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=vocab["<pad>"])
        self.gru = nn.GRU(embed_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, 2)

    def forward(self, x):
        emb = self.embedding(x)
        out, h = self.gru(emb)
        return self.fc(h[-1])

model = GRUClassifier(len(vocab)).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

from tqdm import tqdm

def train_epoch():
    model.train()
    total_loss = 0
    for x, y in tqdm(train_loader):
        optimizer.zero_grad()
        pred = model(x)
        loss = criterion(pred, y)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    return total_loss / len(train_loader)

def evaluate():
    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for x, y in test_loader:
            pred = model(x).argmax(1)
            correct += (pred == y).sum().item()
            total += y.size(0)
    return correct / total

for epoch in range(3):
    loss = train_epoch()
    acc = evaluate()
    print(f"Epoch {epoch+1}: Loss={loss:.4f}, Test Acc={acc:.4f}")

def predict(text):
    model.eval()
    x = torch.tensor(encode(text)).unsqueeze(0).to(device)
    pred = model(x).argmax(1).item()
    return "Positive" if pred == 1 else "Negative"

print(predict("This movie is really great, I loved it."))
print(predict("Terrible movie, boring and slow."))

