# -*- coding: utf-8 -*-
"""ideal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOEDO7TqyZgCX8MfbEmN5o75r8SddwkY
"""

import matplotlib.pyplot as plt
import numpy as np

def visualize_integer_ideal(n, xmin=-10, xmax=10):
    """
    整数環 ℤ のイデアル nℤ を可視化する。
    nℤ = { ..., -2n, -n, 0, n, 2n, ... }
    """
    # 整数点の生成
    integers = np.arange(xmin, xmax + 1)
    ideal_multiples = integers[integers % n == 0]
    non_ideal = integers[integers % n != 0]

    plt.figure(figsize=(10, 2))
    # イデアルに属する点（赤）
    plt.scatter(ideal_multiples, np.zeros_like(ideal_multiples),
               color='red', s=100, label=f'{n}ℤ (ideal)', zorder=3)
    # イデアルに属さない点（青）
    plt.scatter(non_ideal, np.zeros_like(non_ideal),
               color='blue', s=50, label=f'ℤ ∖ {n}ℤ', zorder=2)

    plt.axhline(0, color='black', linewidth=0.5)
    plt.yticks([])
    plt.xlabel('Integers ℤ')
    plt.title(f'Visualization of the ideal {n}ℤ in the integer ring ℤ')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# 例：偶数全体 2ℤ
visualize_integer_ideal(2)

def visualize_quotient_ring_mod_n(n):
    """
    剰余環 ℤ/nℤ を円周上の点として可視化する。
    イデアル nℤ で割ると、0,1,...,n-1 の n 個の元になる。
    """
    angles = np.linspace(0, 2*np.pi, n, endpoint=False)
    x = np.cos(angles)
    y = np.sin(angles)

    plt.figure(figsize=(6, 6))
    plt.scatter(x, y, s=100, color='red', zorder=3)
    for i in range(n):
        plt.text(x[i]*1.1, y[i]*1.1, str(i), fontsize=12,
                 ha='center', va='center')

    circle = plt.Circle((0,0), 1, fill=False, color='black', linestyle='--')
    plt.gca().add_artist(circle)
    plt.axis('equal')
    plt.title(f'Visualization of the quotient ring ℤ/{n}ℤ (mod {n} world)')
    plt.xlabel('Re')
    plt.ylabel('Im')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# 例：ℤ/5ℤ
visualize_quotient_ring_mod_n(5)

import matplotlib.pyplot as plt
import networkx as nx

def visualize_finite_poset_with_maximal():
    """
    有限半順序集合（ハッセ図）で、極大元のイメージを可視化する。
    ここでは Zorn の補題が自明に成り立つ有限の場合を例示。
    """
    # 半順序集合の例（ハッセ図）
    # 要素: a < b, a < c, b < d, c < d
    # d が極大元
    G = nx.DiGraph()
    G.add_edges_from([('a', 'b'), ('a', 'c'), ('b', 'd'), ('c', 'd')])

    pos = {
        'a': (0, 0),
        'b': (-1, 1),
        'c': (1, 1),
        'd': (0, 2)
    }

    plt.figure(figsize=(6, 6))
    nx.draw_networkx_nodes(G, pos, node_color='lightblue', node_size=800)
    nx.draw_networkx_labels(G, pos, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G, pos, edge_color='gray', arrows=True, arrowsize=20)

    # 極大元 d を強調
    nx.draw_networkx_nodes(G, pos, nodelist=['d'], node_color='red', node_size=800)

    plt.title("The concept of maximal elements in finite partially ordered sets (Zorn's lemma holds trivially)")
    plt.axis('off')
    plt.show()

visualize_finite_poset_with_maximal()

def visualize_chain_and_upper_bound():
    """
    半順序集合の鎖と、その上界のイメージを可視化する。
    """
    # 半順序集合の例
    # 要素: a < b < c < d, かつ e は a,b,c,d と比較不能だが、d の上にある
    G = nx.DiGraph()
    G.add_edges_from([('a', 'b'), ('b', 'c'), ('c', 'd')])
    # e は d の上にあるが、順序関係はない（図では上に配置）

    pos = {
        'a': (0, 0),
        'b': (0, 1),
        'c': (0, 2),
        'd': (0, 3),
        'e': (1, 4)
    }

    plt.figure(figsize=(6, 6))
    nx.draw_networkx_nodes(G, pos, node_color='lightblue', node_size=800)
    nx.draw_networkx_labels(G, pos, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G, pos, edge_color='gray', arrows=True, arrowsize=20)

    # 鎖 a < b < c < d を強調
    chain_nodes = ['a', 'b', 'c', 'd']
    nx.draw_networkx_nodes(G, pos, nodelist=chain_nodes, node_color='orange', node_size=800)
    # 上界 e を強調
    nx.draw_networkx_nodes(G, pos, nodelist=['e'], node_color='green', node_size=800)

    plt.title("鎖（オレンジ）とその上界（緑）のイメージ")
    plt.axis('off')
    plt.show()

visualize_chain_and_upper_bound()

import matplotlib.pyplot as plt
import networkx as nx

def visualize_chain_in_poset():
    """
    半順序集合（ハッセ図）の中で、鎖（全順序部分集合）のイメージを可視化する。
    """
    # 半順序集合の例（ハッセ図）
    # 要素: a < b < c < d（鎖）, かつ e, f は比較不能
    G = nx.DiGraph()
    G.add_edges_from([('a', 'b'), ('b', 'c'), ('c', 'd')])
    G.add_nodes_from(['e', 'f'])  # 比較不能な要素

    pos = {
        'a': (0, 0),
        'b': (0, 1),
        'c': (0, 2),
        'd': (0, 3),
        'e': (-1, 1.5),
        'f': (1, 1.5)
    }

    plt.figure(figsize=(6, 6))
    # すべてのノード（薄い色）
    nx.draw_networkx_nodes(G, pos, node_color='lightgray', node_size=800)
    nx.draw_networkx_labels(G, pos, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G, pos, edge_color='gray', arrows=True, arrowsize=20)

    # 鎖 a < b < c < d を強調（オレンジ）
    chain_nodes = ['a', 'b', 'c', 'd']
    nx.draw_networkx_nodes(G, pos, nodelist=chain_nodes,
                           node_color='orange', node_size=800)
    nx.draw_networkx_edges(G, pos, edgelist=[('a','b'),('b','c'),('c','d')],
                           edge_color='orange', arrows=True, arrowsize=20, width=2)

    plt.title("Image of a chain (orange) in a partially ordered set")
    plt.axis('off')
    plt.show()

visualize_chain_in_poset()

import matplotlib.pyplot as plt
import numpy as np

def visualize_cyclic_group(n=6):
    """
    巡回群 ℤ/nℤ（mod n の足し算）を円周上の点として可視化する。
    これは有限可換群の典型例。
    """
    # 0,1,...,n-1 を円周上に配置
    angles = np.linspace(0, 2*np.pi, n, endpoint=False)
    x = np.cos(angles)
    y = np.sin(angles)

    plt.figure(figsize=(6, 6))
    plt.scatter(x, y, s=100, color='red', zorder=3)
    for i in range(n):
        plt.text(x[i]*1.1, y[i]*1.1, str(i), fontsize=12,
                 ha='center', va='center')

    circle = plt.Circle((0,0), 1, fill=False, color='black', linestyle='--')
    plt.gca().add_artist(circle)
    plt.axis('equal')
    plt.title(f'有限可換群 ℤ/{n}ℤ のイメージ\n（mod {n} の足し算）')
    plt.xlabel('Re')
    plt.ylabel('Im')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# 例：ℤ/6ℤ
visualize_cyclic_group(6)

import matplotlib.pyplot as plt
import networkx as nx

def visualize_poset_with_maximal():
    """
    半順序集合（ハッセ図）で、極大元のイメージを可視化する。
    ここでは有限の場合を例示（Zornの補題は自明に成立）。
    """
    # 半順序集合の例（ハッセ図）
    # 要素: a < b, a < c, b < d, c < d
    # d が極大元
    G = nx.DiGraph()
    G.add_edges_from([('a', 'b'), ('a', 'c'), ('b', 'd'), ('c', 'd')])

    pos = {
        'a': (0, 0),
        'b': (-1, 1),
        'c': (1, 1),
        'd': (0, 2)
    }

    plt.figure(figsize=(6, 6))
    nx.draw_networkx_nodes(G, pos, node_color='lightblue', node_size=800)
    nx.draw_networkx_labels(G, pos, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G, pos, edge_color='gray', arrows=True, arrowsize=20)

    # 極大元 d を強調
    nx.draw_networkx_nodes(G, pos, nodelist=['d'], node_color='red', node_size=800)

    plt.title("半順序集合における極大元のイメージ\n（Zornの補題は有限では自明）")
    plt.axis('off')
    plt.show()

visualize_poset_with_maximal()

import matplotlib.pyplot as plt
import numpy as np

def visualize_finite_ordinals(n=8):
    """
    有限順序数 0,1,2,...,n-1 を数直線上に可視化する。
    順序数は「整列した番号」としてのイメージ。
    """
    ordinals = np.arange(n)
    y = np.zeros_like(ordinals)

    plt.figure(figsize=(10, 2))
    plt.scatter(ordinals, y, s=100, color='red', zorder=3)
    for i in ordinals:
        plt.text(i, 0.1, str(i), ha='center', va='bottom', fontsize=12)

    plt.axhline(0, color='black', linewidth=0.5)
    plt.yticks([])
    plt.xlabel('順序数')
    plt.title(f'有限順序数 0,1,...,{n-1} のイメージ\n（整列した番号の列）')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# 例：0〜7までの順序数
visualize_finite_ordinals(8)

def visualize_omega_ordinal(n_finite=6):
    """
    有限順序数 0,1,...,n-1 と、最初の無限順序数 ω の関係を可視化する。
    """
    finite_ordinals = np.arange(n_finite)
    y_finite = np.zeros_like(finite_ordinals)

    # ω の位置（有限の右側）
    omega_pos = n_finite + 1
    y_omega = 0

    plt.figure(figsize=(10, 2))
    # 有限順序数
    plt.scatter(finite_ordinals, y_finite, s=100, color='red', zorder=3, label='有限順序数')
    for i in finite_ordinals:
        plt.text(i, 0.1, str(i), ha='center', va='bottom', fontsize=12)

    # ω
    plt.scatter([omega_pos], [y_omega], s=100, color='blue', zorder=3, label='ω')
    plt.text(omega_pos, 0.1, 'ω', ha='center', va='bottom', fontsize=12)

    # 「...」で続きを表現
    plt.text(n_finite-0.5, -0.2, "...", fontsize=14, ha='center', va='top')

    plt.axhline(0, color='black', linewidth=0.5)
    plt.yticks([])
    plt.xlabel('順序数')
    plt.title('有限順序数と最初の無限順序数 ω のイメージ')
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

visualize_omega_ordinal()

import networkx as nx

def visualize_ordinal_as_order_type():
    """
    同じ順序数を持つ2つの整列集合が「同じ形」であることを可視化する。
    ここでは順序数 3 を持つ整列集合の例。
    """
    # 整列集合 A: {a < b < c}
    G1 = nx.DiGraph()
    G1.add_edges_from([('a', 'b'), ('b', 'c')])
    pos1 = {'a': (0,0), 'b': (0,1), 'c': (0,2)}

    # 整列集合 B: {x < y < z}（A と順序同型）
    G2 = nx.DiGraph()
    G2.add_edges_from([('x', 'y'), ('y', 'z')])
    pos2 = {'x': (2,0), 'y': (2,1), 'z': (2,2)}

    plt.figure(figsize=(8, 4))
    # 集合 A
    nx.draw_networkx_nodes(G1, pos1, node_color='lightblue', node_size=800)
    nx.draw_networkx_labels(G1, pos1, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G1, pos1, edge_color='blue', arrows=True, arrowsize=20)
    plt.text(0, 2.5, "整列集合 A", ha='center', va='bottom', fontsize=12)

    # 集合 B
    nx.draw_networkx_nodes(G2, pos2, node_color='lightgreen', node_size=800)
    nx.draw_networkx_labels(G2, pos2, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G2, pos2, edge_color='green', arrows=True, arrowsize=20)
    plt.text(2, 2.5, "整列集合 B", ha='center', va='bottom', fontsize=12)

    # 順序同型の対応を示す矢印
    plt.arrow(0.5, 1, 1, 0, head_width=0.1, head_length=0.1, fc='red', ec='red')
    plt.text(1, 1.2, "順序同型", ha='center', va='bottom', fontsize=10, color='red')

    plt.title("順序数は「整列順序の型」\n（同じ順序数を持つ集合は順序同型）")
    plt.axis('off')
    plt.show()

visualize_ordinal_as_order_type()

def visualize_ordinal_as_order_type():
    """
    Visualize that two well-ordered sets with the same ordinal number have "the same shape".
    Here we use an example of sets with ordinal number 3.
    """
    # Well-ordered set A: {a < b < c}
    G1 = nx.DiGraph()
    G1.add_edges_from([('a', 'b'), ('b', 'c')])
    pos1 = {'a': (0,0), 'b': (0,1), 'c': (0,2)}

    # Well-ordered set B: {x < y < z} (order-isomorphic to A)
    G2 = nx.DiGraph()
    G2.add_edges_from([('x', 'y'), ('y', 'z')])
    pos2 = {'x': (2,0), 'y': (2,1), 'z': (2,2)}

    plt.figure(figsize=(8, 4))
    # Set A
    nx.draw_networkx_nodes(G1, pos1, node_color='lightblue', node_size=800)
    nx.draw_networkx_labels(G1, pos1, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G1, pos1, edge_color='blue', arrows=True, arrowsize=20)
    plt.text(0, 2.5, "Well-ordered set A", ha='center', va='bottom', fontsize=12)

    # Set B
    nx.draw_networkx_nodes(G2, pos2, node_color='lightgreen', node_size=800)
    nx.draw_networkx_labels(G2, pos2, font_size=12, font_weight='bold')
    nx.draw_networkx_edges(G2, pos2, edge_color='green', arrows=True, arrowsize=20)
    plt.text(2, 2.5, "Well-ordered set B", ha='center', va='bottom', fontsize=12)

    # Arrow indicating order isomorphism
    plt.arrow(0.5, 1, 1, 0, head_width=0.1, head_length=0.1, fc='red', ec='red')
    plt.text(1, 1.2, "Order isomorphism", ha='center', va='bottom', fontsize=10, color='red')

    plt.title("Ordinal numbers are 'order types'\n(Sets with the same ordinal are order-isomorphic)")
    plt.axis('off')
    plt.show()

visualize_ordinal_as_order_type()


import matplotlib.pyplot as plt
import numpy as np

def visualize_finite_ordinals(n=8):
    """
    Visualize finite ordinals 0,1,2,...,n-1 on a number line.
    Ordinals are imagined as "well-ordered labels".
    """
    ordinals = np.arange(n)
    y = np.zeros_like(ordinals)

    plt.figure(figsize=(10, 2))
    plt.scatter(ordinals, y, s=100, color='red', zorder=3)
    for i in ordinals:
        plt.text(i, 0.1, str(i), ha='center', va='bottom', fontsize=12)

    plt.axhline(0, color='black', linewidth=0.5)
    plt.yticks([])
    plt.xlabel('Ordinal number')
    plt.title(f'Visualization of finite ordinals 0,1,...,{n-1}\n(A sequence of well-ordered labels)')
    plt.grid(True, linestyle='--', alpha=0.7)
    plt.show()

# Example: ordinals 0 to 7
visualize_finite_ordinals(8)

import numpy as np
import matplotlib.pyplot as plt

def plot_finite_field(p=5):
    """
    有限体 𝔽ₚ の加法・乗法表と逆元の分布を可視化
    """
    if not (isinstance(p, int) and p > 1):
        raise ValueError("p は 2 以上の整数で指定してください")

    values = list(range(p))
    size = p

    # 加法表 (mod p)
    add_table = np.zeros((size, size), dtype=int)
    for i, a in enumerate(values):
        for j, b in enumerate(values):
            add_table[i, j] = (a + b) % p

    # 乗法表 (mod p)
    mul_table = np.zeros((size, size), dtype=int)
    for i, a in enumerate(values):
        for j, b in enumerate(values):
            mul_table[i, j] = (a * b) % p

    # 逆元のチェック（0 以外）
    inverses = {}
    for a in range(1, p):
        for b in range(1, p):
            if (a * b) % p == 1:
                inverses[a] = b
                break

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # 加法表
    im0 = axes[0].imshow(add_table, cmap='viridis', interpolation='nearest')
    axes[0].set_title(f'Addition Table 𝔽_{p} (mod {p})', fontsize=14)
    axes[0].set_xticks(range(size))
    axes[0].set_yticks(range(size))
    axes[0].set_xticklabels(values)
    axes[0].set_yticklabels(values)
    axes[0].set_xlabel('b')
    axes[0].set_ylabel('a')
    plt.colorbar(im0, ax=axes[0])

    # 乗法表（逆元を強調）
    im1 = axes[1].imshow(mul_table, cmap='viridis', interpolation='nearest')
    axes[1].set_title(f'Multiplication Table 𝔽_{p} (Inverses Highlighted)', fontsize=14)
    axes[1].set_xticks(range(size))
    axes[1].set_yticks(range(size))
    axes[1].set_xticklabels(values)
    axes[1].set_yticklabels(values)
    axes[1].set_xlabel('b')
    axes[1].set_ylabel('a')

    # 逆元の位置をマーキング（a の逆元が b なら (a,b) に印）
    for a, inv in inverses.items():
        axes[1].plot(inv, a, 'ro', markersize=8, markeredgecolor='white')

    plt.colorbar(im1, ax=axes[1])
    plt.tight_layout()
    plt.show()

    # 逆元の情報をテキストで表示
    print(f"𝔽_{p} の乗法の逆元:")
    for a in range(1, p):
        print(f"  {a} の逆元: {inverses[a]} ({a} × {inverses[a]} ≡ 1 mod {p})")

# 実行例
plot_finite_field(p=5)  # 素数の例（体）
plot_finite_field(p=7)  # 別の素数の例

import matplotlib.pyplot as plt
import numpy as np

def plot_complex_field():
    """
    複素数体 ℂ の加法・乗法を幾何的に可視化
    """
    # 例として z = 1+2i, w = 2+1i を選ぶ
    z = complex(1, 2)
    w = complex(2, 1)

    # 加法: z + w
    add_result = z + w

    # 乗法: z * w
    mul_result = z * w

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # 加法の可視化（ベクトルの和）
    axes[0].quiver(0, 0, z.real, z.imag, angles='xy', scale_units='xy', scale=1, color='blue', label=f'z = {z}')
    axes[0].quiver(z.real, z.imag, w.real, w.imag, angles='xy', scale_units='xy', scale=1, color='green', label=f'w = {w}')
    axes[0].quiver(0, 0, add_result.real, add_result.imag, angles='xy', scale_units='xy', scale=1, color='red', label=f'z+w = {add_result}')
    axes[0].set_xlim(-1, 5)
    axes[0].set_ylim(-1, 5)
    axes[0].set_aspect('equal')
    axes[0].grid(True)
    axes[0].set_title('Complex Addition (Vector Addition)', fontsize=14)
    axes[0].legend()

    # 乗法の可視化（極形式：絶対値と偏角）
    r_z, theta_z = np.abs(z), np.angle(z)
    r_w, theta_w = np.abs(w), np.angle(w)
    r_mul, theta_mul = np.abs(mul_result), np.angle(mul_result)

    # 極座標プロット
    angles = [theta_z, theta_w, theta_mul]
    radii = [r_z, r_w, r_mul]
    labels = [f'z (r={r_z:.2f}, θ={theta_z:.2f})',
              f'w (r={r_w:.2f}, θ={theta_w:.2f})',
              f'z×w (r={r_mul:.2f}, θ={theta_mul:.2f})']
    colors = ['blue', 'green', 'red']

    for i, (theta, r, label, color) in enumerate(zip(angles, radii, labels, colors)):
        axes[1].plot([0, r*np.cos(theta)], [0, r*np.sin(theta)], color=color, linewidth=2, label=label)

    axes[1].set_xlim(-1, 6)
    axes[1].set_ylim(-1, 6)
    axes[1].set_aspect('equal')
    axes[1].grid(True)
    axes[1].set_title('Complex Multiplication (Magnitude and Argument)', fontsize=14)
    axes[1].legend()

    plt.tight_layout()
    plt.show()

    # テキストでの説明
    print("複素数体 ℂ の性質:")
    print(f"  加法: {z} + {w} = {add_result} (ベクトルの和)")
    print(f"  乗法: {z} × {w} = {mul_result}")
    print(f"    絶対値: |z|×|w| = {r_z:.2f}×{r_w:.2f} = {r_mul:.2f}")
    print(f"    偏角: arg(z)+arg(w) = {theta_z:.2f} + {theta_w:.2f} = {theta_mul:.2f} rad")
    print("  0 以外の複素数は逆元を持つ（例: 1/z など）")

# 実行例
plot_complex_field()

import torch
import matplotlib.pyplot as plt
import numpy as np

# ダミーの2次元ベクトル群（batch, seq_len, dim）のイメージ
batch_size, seq_len, dim = 1, 20, 2
vectors = torch.randn(batch_size, seq_len, dim)  # (1, 20, 2)

# 1バッチ目だけ取り出し
v = vectors[0]  # (20, 2)
x = v[:, 0].numpy()
y = v[:, 1].numpy()

plt.figure(figsize=(8, 6))

# ベクトルの大きさ（ノルム）を計算
norms = torch.norm(v, dim=1).numpy()  # 大きさ
angles = torch.atan2(v[:, 1], v[:, 0]).numpy()  # 向き（ラジアン）

# 散布図：位置(x,y)、色=向き、大きさ=ノルム
sc = plt.scatter(x, y, c=angles, s=norms*100, cmap='hsv', alpha=0.7)

# 各ベクトルに矢印（quiver）を重ねる
plt.quiver(x, y, x, y, angles, cmap='hsv', scale=20, width=0.005, alpha=0.6)

plt.colorbar(sc, label='Angle (rad)')
plt.xlabel('x')
plt.ylabel('y')
plt.title('2D Vectors: position + color(angle) + size(norm)')
plt.grid(True)
plt.show()

# 3次元ベクトル群（batch, seq_len, dim=3）
batch_size, seq_len, dim = 1, 30, 3
vectors_3d = torch.randn(batch_size, seq_len, dim)
v3 = vectors_3d[0]  # (30, 3)

x3 = v3[:, 0].numpy()
y3 = v3[:, 1].numpy()
z3 = v3[:, 2].numpy()
norms3 = torch.norm(v3, dim=1).numpy()

from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure(figsize=(10, 8))
ax = fig.add_subplot(111, projection='3d')

# 色はz成分（高さ）で変化させる例
sc = ax.scatter(x3, y3, z3, c=z3, s=norms3*100, cmap='viridis', alpha=0.7)

# 各点から原点への線を引く（ベクトルの向きと長さを表現）
for i in range(len(x3)):
    ax.plot([0, x3[i]], [0, y3[i]], [0, z3[i]], 'gray', alpha=0.4)

plt.colorbar(sc, label='z value')
ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
ax.set_title('3D Vectors: position + color(z) + size(norm)')
plt.show()


# 格子点を作成
X, Y = np.meshgrid(np.linspace(-2, 2, 10), np.linspace(-2, 2, 10))

# ダミーのベクトル場（例：回転場）
U = -Y  # x成分
V = X   # y成分

plt.figure(figsize=(8, 6))
plt.quiver(X, Y, U, V, scale=20, color='blue', alpha=0.7)
plt.xlabel('x')
plt.ylabel('y')
plt.title('2D Vector Field')
plt.grid(True)
plt.show()

!apt-get -y install fonts-ipafont-gothic

import matplotlib.pyplot as plt
from matplotlib import rcParams

# フォント設定
rcParams['font.family'] = 'IPAGothic'  # または 'IPAPGothic' など

import matplotlib.pyplot as plt
from matplotlib import font_manager
import shutil
import os

# キャッシュクリア（先ほどと同じ）
cache_dir = '/root/.cache/matplotlib'
if os.path.exists(cache_dir):
    shutil.rmtree(cache_dir)
    print("Cleared font cache")

# フォントマネージャのインスタンスを再生成
font_manager._fmcache = None  # キャッシュを無効化
font_manager.fontManager = font_manager.FontManager()  # 新しいインスタンス

# 利用可能なフォント一覧を確認
fonts = [f.name for f in font_manager.fontManager.ttflist]
jp_fonts = [f for f in fonts if 'Gothic' in f or 'Mincho' in f or 'IP' in f or 'Noto' in f]
print("Available Japanese fonts:", jp_fonts)

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import font_manager
import shutil
import os
from matplotlib import rcParams

# キャッシュクリア（念のため）
cache_dir = '/root/.cache/matplotlib'
if os.path.exists(cache_dir):
    shutil.rmtree(cache_dir)
    print("Cleared font cache")

# フォントマネージャのインスタンスを再生成
font_manager._fmcache = None
font_manager.fontManager = font_manager.FontManager()

# 利用可能なフォント一覧（名前とパス）
fonts_info = [(f.name, f.fname) for f in font_manager.fontManager.ttflist]
jp_fonts_info = [f for f in fonts_info if 'Gothic' in f[0] or 'Mincho' in f[0] or 'IP' in f[0] or 'Noto' in f[0]]
print("Available Japanese fonts (name, path):")
for name, path in jp_fonts_info:
    print(f"  {name}: {path}")

# IPAGothic のパスを取得（存在すれば）
ipagothic_path = None
for name, path in jp_fonts_info:
    if name == 'IPAGothic':
        ipagothic_path = path
        break

if ipagothic_path:
    # フォントファイルのパスを直接指定
    rcParams['font.family'] = [ipagothic_path]
    print(f"Set font to: {ipagothic_path}")
else:
    print("IPAGothic not found in font list. Falling back to English labels.")
    # ここで英字ラベルに切り替える準備

sigma = np.array([[1.0, 0.5], [0.5, 0.8]])
angles = np.linspace(0, 2*np.pi, 16, endpoint=False)
n_vectors = np.array([np.cos(angles), np.sin(angles)]).T
t_vectors = (sigma @ n_vectors.T).T

plt.figure(figsize=(10, 8))
plt.plot(0, 0, 'ko', markersize=8, label='点')

for i, n in enumerate(n_vectors):
    plt.quiver(0, 0, n[0], n[1], color='blue', scale=3, width=0.005, alpha=0.6,
               label='面の法線 n' if i == 0 else "")

for i, t in enumerate(t_vectors):
    plt.quiver(0, 0, t[0], t[1], color='red', scale=5, width=0.005, alpha=0.8,
               label='力ベクトル t' if i == 0 else "")

plt.xlim(-1.5, 1.5)
plt.ylim(-1.5, 1.5)
plt.xlabel('x')
plt.ylabel('y')
plt.title('応力テンソルの可視化\n青: 面の法線 n, 赤: 力ベクトル t = σ・n')
plt.grid(True)
plt.legend()
plt.gca().set_aspect('equal')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

sigma = np.array([[1.0, 0.5], [0.5, 0.8]])
angles = np.linspace(0, 2*np.pi, 16, endpoint=False)
n_vectors = np.array([np.cos(angles), np.sin(angles)]).T
t_vectors = (sigma @ n_vectors.T).T

plt.figure(figsize=(10, 8))
plt.plot(0, 0, 'ko', markersize=8, label='Point')

for i, n in enumerate(n_vectors):
    plt.quiver(0, 0, n[0], n[1], color='blue', scale=3, width=0.005, alpha=0.6,
               label='Normal n' if i == 0 else "")

for i, t in enumerate(t_vectors):
    plt.quiver(0, 0, t[0], t[1], color='red', scale=5, width=0.005, alpha=0.8,
               label='Force t' if i == 0 else "")

plt.xlim(-1.5, 1.5)
plt.ylim(-1.5, 1.5)
plt.xlabel('x')
plt.ylabel('y')
plt.title('Stress Tensor Visualization\nBlue: normal n, Red: force t = σ・n')
plt.grid(True)
plt.legend()
plt.gca().set_aspect('equal')
plt.show()

