# -*- coding: utf-8 -*-
"""shap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14EFqDe93BUVd8uYxLwIxsKBt6hwDSyrt
"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
import shap

# 乱数シードを固定
np.random.seed(42)

# サンプル数
n_samples = 1000

# 特徴量：部屋数、築年数、駅からの距離
rooms = np.random.randint(1, 6, n_samples)        # 1〜5部屋
age = np.random.randint(0, 50, n_samples)          # 築0〜49年
distance = np.random.uniform(0.1, 5.0, n_samples)  # 駅からの距離（km）

# 住宅価格（目的変数）を生成
# 部屋数が多いほど高く、築年数が古いほど安く、駅に近いほど高い、という単純な関係
price = (
    3000 * rooms
    - 50 * age
    - 200 * distance
    + np.random.normal(0, 100, n_samples)  # ノイズ
)

# DataFrameにまとめる
df = pd.DataFrame({
    "rooms": rooms,
    "age": age,
    "distance": distance,
    "price": price
})

X = df[["rooms", "age", "distance"]]
y = df["price"]

# 決定木モデルを学習
model = DecisionTreeRegressor(max_depth=4, random_state=42)
model.fit(X, y)

# 予測精度の確認（簡易）
print("R^2 score:", model.score(X, y))

# TreeExplainer の作成
explainer = shap.TreeExplainer(model)

# 全データの SHAP値を計算
shap_values = explainer.shap_values(X)

# 1件目のデータについて見てみる
sample_idx = 0
print("1件目のデータ:")
print(X.iloc[sample_idx])
print("実際の価格:", y.iloc[sample_idx])
print("モデルの予測:", model.predict(X.iloc[sample_idx:sample_idx+1])[0])
print("ベースライン（平均予測）:", explainer.expected_value)
print("SHAP値（rooms, age, distance の順）:", shap_values[sample_idx])
print("SHAP値の合計 + ベースライン = 予測値:",
      explainer.expected_value + shap_values[sample_idx].sum())

shap.force_plot(
    explainer.expected_value,
    shap_values[sample_idx],
    X.iloc[sample_idx],
    matplotlib=True
)

shap.summary_plot(shap_values, X)

!wget https://data.mendeley.com/public-api/zip/9z7yrcrpjk/download/1

!file /content/1

!unzip /content/1

!wget https://huggingface.co/datasets/aialliance/GEOBench-VLM/resolve/main/Single.parquet?download=true
!unzip /content/Temporal.zip?download=true
!wget https://huggingface.co/datasets/aialliance/GEOBench-VLM/resolve/main/Temporal.zip?download=true

!wget https://huggingface.co/datasets/aialliance/GEOBench-VLM/resolve/main/Temporal.zip?download=true

!unzip /content/Temporal.zip?download=true

import pandas as pd
import json
import os
import io
from PIL import Image

def convert_parquet_to_csv_and_images(parquet_path, csv_path, image_dir):
    if not os.path.exists(parquet_path):
        print(f"エラー: {parquet_path} が見つかりません。")
        return

    # 画像保存用フォルダの作成
    os.makedirs(image_dir, exist_ok=True)

    print(f"Parquetファイルを読み込んでいます: {parquet_path}")
    df = pd.read_parquet(parquet_path)

    print("検出されたカラム一覧:", df.columns.tolist())

    # 画像ファイル名を記録する新しい列
    saved_paths = []

    print("画像を抽出して保存しています...")
    for idx, row in df.iterrows():
        # 連番のファイル名を生成
        img_filename = f"image_{idx:05d}.png"
        img_path = os.path.join(image_dir, img_filename)

        # 'image' カラムからデータを取得
        img_data = row.get('image', None)

        success = False
        if img_data is not None:
            try:
                # パターン1: 辞書型で 'bytes' キーを持つ場合（Hugging Face形式）
                if isinstance(img_data, dict) and 'bytes' in img_data:
                    img = Image.open(io.BytesIO(img_data['bytes']))
                    img.save(img_path)
                    success = True
                # パターン2: バイナリ（bytes）データが直接入っている場合
                elif isinstance(img_data, bytes):
                    img = Image.open(io.BytesIO(img_data))
                    img.save(img_path)
                    success = True
                # パターン3: すでに PIL Image オブジェクトとして読み込まれている場合
                elif hasattr(img_data, 'save'):
                    img_data.save(img_path)
                    success = True
            except Exception as e:
                print(f"行 {idx} の画像保存中にエラーが発生しました: {e}")

        if success:
            saved_paths.append(img_path)
        else:
            saved_paths.append(None)  # 画像が取得できなかった場合

    # CSVに対応する画像パスを記録
    df['saved_image_path'] = saved_paths

    # 既存の 'image' カラム（巨大なバイナリデータ）はCSVを軽量化するため除外
    if 'image' in df.columns:
        df = df.drop(columns=['image'])

    # 辞書型やリスト型が含まれるカラムをCSV用にJSON文字列化
    for col in df.columns:
        if df[col].apply(lambda x: isinstance(x, (dict, list))).any():
            df[col] = df[col].apply(lambda x: json.dumps(x, ensure_ascii=False) if isinstance(x, (dict, list)) else x)

    # CSVとして出力
    df.to_csv(csv_path, index=False, encoding='utf-8-sig')
    print(f"\n処理が完了しました！")
    print(f"- メタデータ（CSV）: {csv_path}")
    print(f"- 画像フォルダ: {image_dir} (総枚数: {len([n for n in saved_paths if n is not None])}枚)")

if __name__ == '__main__':
    input_parquet = '/content/Single.parquet?download=true'
    output_csv = '/content/Single_metadata.csv'
    image_directory = '/content/image'

    convert_parquet_to_csv_and_images(input_parquet, output_csv, image_directory)

df = pd.read_csv("/content/Single_metadata.csv")
df['image_path'] = df['image_path'].apply(lambda x: os.path.basename(str(x)))
df.task.value_counts()

df_geo = df[df['task'] == 'Sptatial Relation Classification']

# 絞り込んだデータだけを別のCSVとして保存
df_geo.to_csv("/content/Single_geo_only.csv", index=False, encoding='utf-8-sig')
print("地理関係のみに絞り込んだCSVを保存しました。")

df_geo.head()

dir_base = "/content/images"
df_geo['image_path'] = df_geo['image_path'].apply(lambda x:os.path.join(dir_base, x))


import pandas as pd
import os
import random
import json
import matplotlib.pyplot as plt
from PIL import Image

def display_random_samples(df, num_samples=3):
    # 実際に存在する画像パスを持つ行だけに絞り込む
    df_valid = df[df['saved_image_path'].apply(lambda x: os.path.exists(str(x)))]

    if len(df_valid) == 0:
        print("エラー: 'saved_image_path' に指定されたパスに画像ファイルが見つかりません。")
        print("パスのプレフィックス（/content/Temporal など）やファイル名が正しいか再確認してください。")
        return

    # 指定されたサンプル数と有効データ数の小さい方を抽出件数にする
    samples_count = min(num_samples, len(df_valid))
    sampled_df = df_valid.sample(n=samples_count)

    for i, (idx, row) in enumerate(sampled_df.iterrows(), 1):
        print(f"\n{'='*40} サンプル {i} (インデックス: {idx}) {'='*40}")

        # 1. 画像の表示
        img_path = row['saved_image_path']
        try:
            img = Image.open(img_path)
            plt.figure(figsize=(6, 6))
            plt.imshow(img)
            plt.axis('off')
            plt.title(f"Sample {i}: {os.path.basename(img_path)}")
            plt.show()
        except Exception as e:
            print(f"画像の読み込みに失敗しました ({img_path}): {e}")

        # 2. 問題文（プロンプト）の表示
        # カラム名が 'prompts' か 'question' の想定（適宜環境に合わせてください）
        prompt_text = row.get('prompts', row.get('question', 'N/A'))
        print(f"\n【問題 (Prompt)】\n{prompt_text}\n")

        # 3. 選択肢（Options）の表示
        options_raw = row.get('options_list', row.get('options', '[]'))

        # JSON文字列になっている場合はリストにデコードする
        if isinstance(options_raw, str):
            try:
                options = json.loads(options_raw)
            except json.JSONDecodeError:
                options = [options_raw]
        else:
            options = options_raw

        print("【選択肢 (Options)】")
        if isinstance(options, list):
            for j, opt in enumerate(options, 1):
                print(f"  ({j}) {opt}")
        else:
            print(f"  {options}")

        # もし正解ラベル（answer など）のカラムがあれば追加で表示
        if 'answer' in df.columns:
            print(f"\n【正解 (Answer)】: {row['answer']}")

        print(f"{'='*95}\n")

# 実行（表示したいサンプル数を num_samples で指定できます）
display_random_samples(df_geo, num_samples=3)

import pandas as pd
import os
import shutil

def pickup_and_save_samples(df, num_samples=20, output_dir="/content/image_problem", output_csv="/content/selected_problems.csv"):
    # 1. 必要なフォルダの作成
    os.makedirs(output_dir, exist_ok=True)

    # 2. 'saved_image_path' カラムが存在し、かつ実際に画像ファイルが存在する行だけに絞り込む
    if 'saved_image_path' not in df.columns:
        print("エラー: 'saved_image_path' カラムが DataFrame に存在しません。")
        return

    df_valid = df[df['saved_image_path'].apply(lambda x: os.path.exists(str(x)) if pd.notna(x) else False)]

    available_count = len(df_valid)
    print(f"有効な画像付きのデータ件数: {available_count} 件")

    if available_count == 0:
        print("エラー: 有効な画像ファイルが見つかりません。パスを確認してください。")
        return

    # 3. ランダムサンプリング（指定件数よりデータが少ない場合は全件）
    pickup_count = min(num_samples, available_count)
    df_selected = df_valid.sample(n=pickup_count, random_state=None) # 必要に応じて random_state を固定してください

    # 4. 画像のコピーとCSV用のパス書き換え
    new_image_paths = []
    print(f"\n{pickup_count} 個の画像ファイルを {output_dir} にコピーしています...")

    for idx, row in df_selected.iterrows():
        src_path = row['saved_image_path']
        filename = os.path.basename(src_path)
        dst_path = os.path.join(output_dir, filename)

        try:
            shutil.copy(src_path, dst_path)
            new_image_paths.append(dst_path)
        except Exception as e:
            print(f"インデックス {idx} の画像コピーに失敗しました: {e}")
            new_image_paths.append(None)

    # 新しい保存先パスを記録（必要に応じて）
    df_selected['copied_image_path'] = new_image_paths

    # 5. ピックアップした問題のCSV保存
    df_selected.to_csv(output_csv, index=False, encoding='utf-8-sig')

    print(f"\n処理が完了しました！")
    print(f"- コピーされた画像フォルダ: {output_dir} (枚数: {len(os.listdir(output_dir))}枚)")
    print(f"- 選択された問題のCSV: {output_csv}")

# 実行
pickup_and_save_samples(df_geo, num_samples=20)

!zip -r /content/image_problem.zip /content/image_problem

!wget https://huggingface.co/datasets/JX128/image2GPS_project_dataset/resolve/main/data/test-00000-of-00007.parquet?download=true

panquet = "/content/test-00000-of-00007.parquet?download=true"
output_csv = '/content/image2GPS_metadata.csv'
image_directory = '/content/image_image2GPS'
convert_parquet_to_csv_and_images(panquet, output_csv, image_directory)

