# -*- coding: utf-8 -*-
"""omni_diff.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TFcvc1kCkS9BtigNyH3h_hKB-XkgjYQz
"""

!wget https://huggingface.co/datasets/IVC-liuyuan/OmniDiff/blob/main/Render.zip

!unzip /content/Render.zip

!file /content/Render.zip

!wget https://huggingface.co/datasets/IVC-liuyuan/OmniDiff/resolve/main/Render.zip?download=true

!unzip /content/Real.zip?download=true

!unzip /content/Render/test.zip

!file /content/Render/test.zip

# 解凍結果を標準出力に出力し、任意のファイル名で保存
!gzip -dc /content/Render/test.zip > /content/Render/test

# 解凍後のファイルを確認
!file /content/Render/test

# tar アーカイブを解凍（カレントディレクトリに展開）
!tar -xf /content/Render/test

# 解凍先を指定したい場合（例：/content/Render/extracted/）
!mkdir -p /content/Render/extracted
!tar -xf /content/Render/test -C /content/Render/extracted/

!wget https://huggingface.co/datasets/IVC-liuyuan/OmniDiff/resolve/main/Real.zip?download=true

!unzip /content/Real.zip?download=true

# 解凍結果を標準出力に出力し、任意のファイル名で保存
!gzip -dc /content/Real/test.zip > /content/Real/test

# 解凍後のファイルを確認
!file /content/Real/test

# tar アーカイブを解凍（カレントディレクトリに展開）
!tar -xf /content/Real/test

# 解凍先を指定したい場合（例：/content/Render/extracted/）
!mkdir -p /content/Real/extracted
!tar -xf /content/Real/test -C /content/Real/extracted/

!ls /content/Real/extracted/test/*.json

import json

# split.json を読み込む
with open("/content/Real/split.json", "r", encoding="utf-8") as f:
    data = json.load(f)

# "test" キーの値を取得
test_data = data["test"]

# 内容を表示（例：最初の数要素）
print("test 項目の内容:")
print(test_data)

with open("/content/Real/caption.json", "r", encoding="utf-8") as f:
    answers = json.load(f)

!ls /content/Real/extracted/test

import os
import shutil
import random

# 前提: split.json はすでに読み込まれ、test_data にテスト用 ID のリストが入っている
# 例: test_data = [7915, 8049, 8183, ...]

# テスト用 ID からランダムに 30 個をサンプリング
sampled_ids = random.sample(test_data, min(30, len(test_data)))

# 画像が保存されているディレクトリ
img_dir = "/content/Real/extracted/test"
# 出力先ディレクトリ
output_dir = "/content/output"

# 出力ディレクトリがなければ作成
os.makedirs(output_dir, exist_ok=True)

# ペア画像をコピーするリスト
copied_pairs = []

for img_id in sampled_ids:
    # ペアとなる画像ファイル名
    img1 = f"{img_id}.jpg"
    img2 = f"{img_id}_2.jpg"
    img1_path = os.path.join(img_dir, img1)
    img2_path = os.path.join(img_dir, img2)

    # 両方のファイルが存在するか確認
    if os.path.exists(img1_path) and os.path.exists(img2_path):
        # 出力先パス
        out_img1 = os.path.join(output_dir, img1)
        out_img2 = os.path.join(output_dir, img2)

        # コピー
        shutil.copy2(img1_path, out_img1)
        shutil.copy2(img2_path, out_img2)

        copied_pairs.append((img1, img2))
    else:
        print(f"警告: {img1} または {img2} が存在しません。スキップします。")

# 結果の表示
print(f"合計 {len(copied_pairs)} 組のペア画像を {output_dir} に保存しました。")
if copied_pairs:
    print("保存されたペア:")
    for img1, img2 in copied_pairs:
        print(f"  {img1} と {img2}")

import os
import shutil
import random
import json

# 前提:
# - split.json から test_data にテスト用 ID のリストが入っている
# - answers 辞書に {id: アノテーション} の形でデータが入っている

# テスト用 ID からランダムに 30 個をサンプリング
sampled_ids = random.sample(test_data, min(30, len(test_data)))

# 画像が保存されているディレクトリ
img_dir = "/content/Real/extracted/test"
# 出力先ディレクトリ
output_dir = "/content/output"

# 出力ディレクトリがなければ作成
os.makedirs(output_dir, exist_ok=True)

# ペア画像とアノテーションを保存するリスト
copied_pairs = []
selected_annotations = {}

for img_id in sampled_ids:
    # ペアとなる画像ファイル名
    img1 = f"{img_id}.jpg"
    img2 = f"{img_id}_2.jpg"
    img1_path = os.path.join(img_dir, img1)
    img2_path = os.path.join(img_dir, img2)

    # 両方のファイルが存在するか確認
    if os.path.exists(img1_path) and os.path.exists(img2_path):
        # 出力先パス
        out_img1 = os.path.join(output_dir, img1)
        out_img2 = os.path.join(output_dir, img2)

        # 画像をコピー
        shutil.copy2(img1_path, out_img1)
        shutil.copy2(img2_path, out_img2)

        # アノテーションを取得
        if img_id in answers:
            selected_annotations[img_id] = answers[img_id]
        else:
            print(f"警告: ID {img_id} に対応するアノテーションが answers に存在しません。")

        copied_pairs.append((img1, img2))
    else:
        print(f"警告: {img1} または {img2} が存在しません。スキップします。")

# アノテーションを JSON ファイルとして保存
annotations_path = os.path.join(output_dir, "annotations.json")
with open(annotations_path, "w", encoding="utf-8") as f:
    json.dump(selected_annotations, f, ensure_ascii=False, indent=2)

# 結果の表示
print(f"合計 {len(copied_pairs)} 組のペア画像を {output_dir} に保存しました。")
print(f"アノテーションは {annotations_path} に保存しました。")
if copied_pairs:
    print("保存されたペア:")
    for img1, img2 in copied_pairs:
        print(f"  {img1} と {img2}")

!zip -r omni_diff.zip /content/output

